/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*\

File: OCTVC1_RUS_RC.h

Copyright (c) 2019 Octasic Inc. All rights reserved.

Description: Contains the return codes for the RUS API.

This source code is Octasic Confidential. Use of and access to this code
is covered by the Octasic Device Enabling Software License Agreement.
Acknowledgement of the Octasic Device Enabling Software License was
required for access to this code. A copy was also provided with the release.

Release: OCTSDR Software Development Kit OCTSDR_RUS-04.00.02-B3333 (2019/01/02)

$Octasic_Revision: $

\*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/

#ifndef OCTVC1_RUS_RC_H__
#define OCTVC1_RUS_RC_H__


/*****************************  INCLUDE FILES  *******************************/
#include "../octvc1_base.h"
#include "../octvc1_generic_rc.h"
#include "octvc1_rus_base.h"

/****************************************************************************
	RUS return codes
 ****************************************************************************/

/*-------------------------------------------------------------------------------------
 	RFFI error code definition
-------------------------------------------------------------------------------------*/
#define cOCTVC1_RUS_RC_RFFI_BAND_INVALID										 ( 0x0001 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_STANDARD_INVALID									 ( 0x0002 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_STANDARD_NOT_SUPPORTED								 ( 0x0003 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_TRANSMITTER_UARFCN_INVALID							 ( 0x0004 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_TRANSMITTER_NO_MORE									 ( 0x0005 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_TRANSMITTER_ATTENUATION_OUT_OF_RANGE				 ( 0x0006 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_RECEIVER_UARFCN_INVALID								 ( 0x0007 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_RECEIVER_NO_MORE									 ( 0x0008 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_RECEIVER_GAIN_OUT_OF_RANGE							 ( 0x0009 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_CAPTURE_BUFFER_TOO_BIG								 ( 0x000A + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_CAPTURE_BUFFER_LENGTH_OUT_OF_RANGE					 ( 0x000B + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_CAPTURE_ALREARY_STOPPED								 ( 0x000C + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_CAPTURE_ALREARY_STARTED								 ( 0x000D + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_RXGAIN_MODE_INVALID									 ( 0x000E + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_CDMA2K_BAND_NOT_SUPPORTED							 ( 0x000F + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_2ANT_NOT_SUPPORTED									 ( 0x00F0 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_CAPTURE_2ANT_STREAMING_NOT_SUPPORTED				 ( 0x00F1 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_CAPTURE_2ANT_STANDARD_NOT_SUPPORTED					 ( 0x00F2 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_STREAMING_MODE_NOT_SUPPORTED_FOR_CURRENT_STANDARD	 ( 0x00F3 + cOCTVC1_RUS_RC_BASE )

/*-------------------------------------------------------------------------------------
 	PLAYREC error code definition
-------------------------------------------------------------------------------------*/
#define cOCTVC1_RUS_RC_PLAYER_FILE_ADD_FILENAME_INVALID							 ( 0x0301 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_FILE_ADD_NO_MORE									 ( 0x0302 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_FILE_IDENTIFIER_INVALID							 ( 0x0303 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_ALREADY_STARTED									 ( 0x0304 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_ALREADY_STOPPED									 ( 0x0305 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_MUST_BE_STOPPED_PRIOR								 ( 0x0306 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_REQUIRE_RFFI_HANDLE								 ( 0x0307 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_MODE_NOT_SUPPORTED_IN_LOOPBACK					 ( 0x0308 + cOCTVC1_RUS_RC_BASE )

/*-------------------------------------------------------------------------------------
 	WNM error code definition
-------------------------------------------------------------------------------------*/
#define cOCTVC1_RUS_RC_WNM_OBJ_ACCESS_ERROR										 ( 0x0201 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_RFPORT_ID_INVALID									 ( 0x0202 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_STANDARD_INVALID								 ( 0x0203 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_STANDARD_NOT_SUPPORTED						 ( 0x0204 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_BAND_INVALID									 ( 0x0205 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_BAND_NOT_SUPPORTED							 ( 0x0206 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_UARFCN_INVALID								 ( 0x0207 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_RSSI_THRESHOLDINVALID							 ( 0x0208 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_NUM_ENTRY_INVALID								 ( 0x0209 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_NUM_BAND_EXCEED_LIMIT							 ( 0x020A + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_UMTS_CELL_ID_INVALID									 ( 0x020B + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_GSM_CELL_ID_INVALID									 ( 0x020C + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_LTE_CELL_ID_INVALID									 ( 0x020D + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_UNINITIALIZED									 ( 0x020E + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_RUNNING										 ( 0x020F + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_MODE_INVALID									 ( 0x0210 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_MODE_NOT_SUPPORTED							 ( 0x0211 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_RECEIVER_GAIN_MODE_INVALID					 ( 0x0212 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_RECEIVER_GAIN_OUT_OF_RANGE					 ( 0x0213 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_NUM_BCH_PLAYLOAD_BLOCK_OUT_OF_RANGE			 ( 0x0214 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_CMD_SEQUENCE_INVALID							 ( 0x0215 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_CLOSE_ERROR											 ( 0x0216 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_RSP_THRESHOLDINVALID							 ( 0x0217 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_SQ_THRESHOLDINVALID							 ( 0x0218 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_SIBSELECTION_NOT_SUPPORTED					 ( 0x0219 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_RSSI_STANDARD_INVALID								 ( 0x021A + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_RSSI_BAND_INVALID									 ( 0x021B + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_RSSI_BAND_NOT_FOUND									 ( 0x021C + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_RSSI_DUPLICATED_BAND							 ( 0x021D + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_WNMC_RSP_ERROR										 ( 0x021E + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_WNMC_RSP_TIMEOUT										 ( 0x021F + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_MODULE_PROFILE											 ( 0x0220 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_DURATION_TYPE_NOT_SUPPORTED								 ( 0x0221 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_CELL_ID_INVALID								 ( 0x0223 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_MCC_ERROR											 ( 0x0224 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_NR_CELL_ID_INVALID									 ( 0x0225 + cOCTVC1_RUS_RC_BASE )

/*-------------------------------------------------------------------------------------
 	BASS error code definition
-------------------------------------------------------------------------------------*/
#define cOCTVC1_RUS_RC_BASS_OBJ_ACCESS_ERROR									 ( 0x0101 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_RFPORT_ID_INVALID									 ( 0x0102 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_STANDARD_INVALID								 ( 0x0103 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_STANDARD_NOT_SUPPORTED						 ( 0x0104 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_BAND_INVALID									 ( 0x0105 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_BAND_NOT_SUPPORTED							 ( 0x0106 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_UARFCN_INVALID								 ( 0x0107 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_NUM_BAND_EXCEED_LIMIT						 ( 0x0108 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_GSM_CELL_ID_INVAILD									 ( 0x0109 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_UNINITIALIZED								 ( 0x010A + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_RUNNING										 ( 0x010B + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_MODE_INVALID									 ( 0x010C + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_MODE_NOT_SUPPORTED							 ( 0x010D + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_RECEIVER_GAIN_MODE_INVALID					 ( 0x010E + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_RECEIVER_GAIN_OUT_OF_RANGE					 ( 0x010F + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_BASSC_RSP_TIMEOUT									 ( 0x0110 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_BASSC_RSP_ERROR										 ( 0x0111 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_ATTACH_PCI_NOT_SUPPORTED							 ( 0x0112 + cOCTVC1_RUS_RC_BASE )
#define cOCTVC1_RUS_RC_BASS_PROCESS_NOT_CONTROL_CLKSYNC_MGR						 ( 0x0113 + cOCTVC1_RUS_RC_BASE )

/****************************************************************************
	Validate return codes
 ****************************************************************************/
#define cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE											 ( 0xF000 + cOCTVC1_RUS_RC_BASE )

#define cOCTVC1_RUS_RC_RFFI_RX_STATS_INVALID_RTWPD_BM								 ( 0x1 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_RX_STATS_INVALID_RX_GAIN								 ( 0x2 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_TX_STATS_INVALID_POWERD_BM								 ( 0x3 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFI_UMTS_TX_INVALID_GAIND_B									 ( 0x4 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFI_UMTS_RX_INVALID_GAIND_B									 ( 0x5 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFI_LTE_TX_INVALID_GAIND_B									 ( 0x6 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFI_LTE_RX_INVALID_GAIND_B									 ( 0x7 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFI_GSM_TX_INVALID_GAIND_B									 ( 0x8 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFI_GSM_RX_INVALID_GAIND_B									 ( 0x9 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFI_CDMA2000_TX_INVALID_GAIND_B								 ( 0xA + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFI_CDMA2000_RX_INVALID_GAIND_B								 ( 0xB + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_ENTRY_INVALID_RSSI_THRESHOLD						 ( 0xF + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_ENTRY_INVALID_RSPTHRESHOLDD_BM					 ( 0x10 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_ENTRY_INVALID_SQTHRESHOLDD_B						 ( 0x11 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_PARMS_INVALID_MANUAL_RX_GAIND_B					 ( 0x12 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_PARMS_INVALID_UBY_EVENT_SEARCH_STATS_RATE			 ( 0x13 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_SEARCH_STATS_INVALID_MANUAL_RX_GAIND_B					 ( 0x14 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_GSM_CELL_STATS_INVALID_TIME_ADVANCE						 ( 0x15 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_LP_SEC						 ( 0x16 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_LMT_OFF					 ( 0x17 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_DAYLT						 ( 0x18 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_PRAT						 ( 0x19 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__BCCH_NON_TD_INCL		 ( 0x1A + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__NON_TD_FREQ_INCL		 ( 0x1B + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__BRAT_NON_TD			 ( 0x1C + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__CRAT_NON_TD			 ( 0x1D + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__BCCH_CODE_CHAN_NON_TD	 ( 0x1E + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__TD_INCL				 ( 0x1F + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__BRAT_TD				 ( 0x20 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__CRAT_TD				 ( 0x21 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__BCCH_CODE_CHAN_TD		 ( 0x22 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__TD_MODE				 ( 0x23 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR1__TD_POWER_LEVEL		 ( 0x24 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR3__INCL					 ( 0x25 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR3__CENTER_FREQ_INCL		 ( 0x26 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR3__BCCH_CODE_CHAN		 ( 0x27 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR3__PRIMARY_PILOT			 ( 0x28 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR3__PILOT_POWER1			 ( 0x29 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR3__PILOT_POWER2			 ( 0x2A + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_DS_INCL					 ( 0x2B + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_SID						 ( 0x2C + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_NID						 ( 0x2D + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_PILOT_PN					 ( 0x2E + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_CDMA_FREQ					 ( 0x2F + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_EXT_CDMA_FREQ				 ( 0x30 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_SR1__CDMA_FREQ_NON_TD		 ( 0x31 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_SR1__CDMA_FREQ_TD			 ( 0x32 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_SR3__CENTER_FREQ			 ( 0x33 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_BY_SR3__BRAT					 ( 0x34 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_LC_STATE_HI				 ( 0x35 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_LC_STATE_LO					 ( 0x36 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_US_SYS_TIME_HI				 ( 0x37 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_SYS_TIME_LO					 ( 0x38 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_CDMA2000_FSYNC_MSG_INVALID_DS_BLOB						 ( 0x39 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_LTE_BCH_TB_INVALID_US_SFN								 ( 0x3A + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_LTE_BCH_TB_INVALID_UBY_SUB_FRAME_NUMBER					 ( 0x3B + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_NR_BCH_TB_INVALID_US_SFN									 ( 0x3C + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_WNM_NR_BCH_TB_INVALID_BY_SUB_FRAME_NUMBER					 ( 0x3D + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_FILE_ENTRY_ADD_INVALID_FILE_OFFSET					 ( 0x3E + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_FILE_ENTRY_ADD_INVALID_GAIND_B						 ( 0x3F + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_FILE_ENTRY_INFO_INVALID_FILE_OFFSET					 ( 0x40 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_FILE_ENTRY_INFO_INVALID_GAIND_B						 ( 0x41 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_FILE_ENTRY_MODIFY_INVALID_FILE_OFFSET					 ( 0x42 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_PLAYER_FILE_ENTRY_MODIFY_INVALID_GAIND_B						 ( 0x43 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_OPEN_INVALID_RX_GAIN_MODE								 ( 0x44 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_RUS_RC_RFFI_INFO_INVALID_RX_GAIN_MODE								 ( 0x45 + cOCTVC1_RUS_AUTO_VALIDATE_RC_BASE )

#endif /* OCTVC1_RUS_RC_H__ */

