/**************************************************************************
	Generated automatically by Codegenix(TM) - (c) 2000-2004 Dafocus
	EnDec version 1.0.168
	GENERATOR: ed-c-recog
	http://www.Dafocus.it/
**************************************************************************/


#include "ed_c_recog_EPS.h"
#include "ed_lib.h"
#include "EPS_MM_Uplink_EPS.h"
#include "EPS_MM_Downlink_EPS.h"
#include "EPS_SM_Uplink_EPS.h"
#include "EPS_SM_Downlink_EPS.h"
#if ED_COMMON_CRC != 0xC33C6D73
#error Invalid Encodix library files linked; used those distributed with Encodix 1.0.168
#endif


int SETPRESENT_TEPS_MM_Uplink_Data (TEPS_MM_Uplink_Data* sp, TEPS_MM_Uplink_Type toBeSetPresent)
{
	if (sp->Type == toBeSetPresent) return ED_NO_ERRORS;
	FREE_TEPS_MM_Uplink_Data (sp);
	sp->Type = toBeSetPresent;

	switch (sp->Type) {
		case ID_EPS_MM_Uplink_ATTACH_COMPLETE: {
			sp->Data.fld_c_ATTACH_COMPLETE = (c_ATTACH_COMPLETE*)EDAlloc (sizeof (c_ATTACH_COMPLETE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ATTACH_COMPLETE == NULL)
			INIT_c_ATTACH_COMPLETE (sp->Data.fld_c_ATTACH_COMPLETE);
			break;
		}
		
		case ID_EPS_MM_Uplink_ATTACH_REQUEST: {
			sp->Data.fld_c_ATTACH_REQUEST = (c_ATTACH_REQUEST*)EDAlloc (sizeof (c_ATTACH_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ATTACH_REQUEST == NULL)
			INIT_c_ATTACH_REQUEST (sp->Data.fld_c_ATTACH_REQUEST);
			break;
		}
		
		case ID_EPS_MM_Uplink_AUTHENTICATION_FAILURE: {
			sp->Data.fld_c_AUTHENTICATION_FAILURE = (c_AUTHENTICATION_FAILURE*)EDAlloc (sizeof (c_AUTHENTICATION_FAILURE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_AUTHENTICATION_FAILURE == NULL)
			INIT_c_AUTHENTICATION_FAILURE (sp->Data.fld_c_AUTHENTICATION_FAILURE);
			break;
		}
		
		case ID_EPS_MM_Uplink_AUTHENTICATION_RESPONSE: {
			sp->Data.fld_c_AUTHENTICATION_RESPONSE = (c_AUTHENTICATION_RESPONSE*)EDAlloc (sizeof (c_AUTHENTICATION_RESPONSE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_AUTHENTICATION_RESPONSE == NULL)
			INIT_c_AUTHENTICATION_RESPONSE (sp->Data.fld_c_AUTHENTICATION_RESPONSE);
			break;
		}
		
		case ID_EPS_MM_Uplink_EPS_DETACH_ACCEPT_UP: {
			sp->Data.fld_c_EPS_DETACH_ACCEPT_UP = (c_EPS_DETACH_ACCEPT_UP*)EDAlloc (sizeof (c_EPS_DETACH_ACCEPT_UP)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EPS_DETACH_ACCEPT_UP == NULL)
			INIT_c_EPS_DETACH_ACCEPT_UP (sp->Data.fld_c_EPS_DETACH_ACCEPT_UP);
			break;
		}
		
		case ID_EPS_MM_Uplink_EPS_DETACH_REQUEST_UP: {
			sp->Data.fld_c_EPS_DETACH_REQUEST_UP = (c_EPS_DETACH_REQUEST_UP*)EDAlloc (sizeof (c_EPS_DETACH_REQUEST_UP)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EPS_DETACH_REQUEST_UP == NULL)
			INIT_c_EPS_DETACH_REQUEST_UP (sp->Data.fld_c_EPS_DETACH_REQUEST_UP);
			break;
		}
		
		case ID_EPS_MM_Uplink_EMM_STATUS: {
			sp->Data.fld_c_EMM_STATUS = (c_EMM_STATUS*)EDAlloc (sizeof (c_EMM_STATUS)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EMM_STATUS == NULL)
			INIT_c_EMM_STATUS (sp->Data.fld_c_EMM_STATUS);
			break;
		}
		
		case ID_EPS_MM_Uplink_EXTENDED_SERVICE_REQUEST: {
			sp->Data.fld_c_EXTENDED_SERVICE_REQUEST = (c_EXTENDED_SERVICE_REQUEST*)EDAlloc (sizeof (c_EXTENDED_SERVICE_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EXTENDED_SERVICE_REQUEST == NULL)
			INIT_c_EXTENDED_SERVICE_REQUEST (sp->Data.fld_c_EXTENDED_SERVICE_REQUEST);
			break;
		}
		
		case ID_EPS_MM_Uplink_GUTI_REALLOCATION_COMPLETE: {
			sp->Data.fld_c_GUTI_REALLOCATION_COMPLETE = (c_GUTI_REALLOCATION_COMPLETE*)EDAlloc (sizeof (c_GUTI_REALLOCATION_COMPLETE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_GUTI_REALLOCATION_COMPLETE == NULL)
			INIT_c_GUTI_REALLOCATION_COMPLETE (sp->Data.fld_c_GUTI_REALLOCATION_COMPLETE);
			break;
		}
		
		case ID_EPS_MM_Uplink_IDENTITY_RESPONSE: {
			sp->Data.fld_c_IDENTITY_RESPONSE = (c_IDENTITY_RESPONSE*)EDAlloc (sizeof (c_IDENTITY_RESPONSE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_IDENTITY_RESPONSE == NULL)
			INIT_c_IDENTITY_RESPONSE (sp->Data.fld_c_IDENTITY_RESPONSE);
			break;
		}
		
		case ID_EPS_MM_Uplink_SECURITY_MODE_COMPLETE: {
			sp->Data.fld_c_SECURITY_MODE_COMPLETE = (c_SECURITY_MODE_COMPLETE*)EDAlloc (sizeof (c_SECURITY_MODE_COMPLETE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_SECURITY_MODE_COMPLETE == NULL)
			INIT_c_SECURITY_MODE_COMPLETE (sp->Data.fld_c_SECURITY_MODE_COMPLETE);
			break;
		}
		
		case ID_EPS_MM_Uplink_SECURITY_MODE_REJECT: {
			sp->Data.fld_c_SECURITY_MODE_REJECT = (c_SECURITY_MODE_REJECT*)EDAlloc (sizeof (c_SECURITY_MODE_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_SECURITY_MODE_REJECT == NULL)
			INIT_c_SECURITY_MODE_REJECT (sp->Data.fld_c_SECURITY_MODE_REJECT);
			break;
		}
		
		case ID_EPS_MM_Uplink_SECURITY_PROTECTED_NAS_MESSAGE: {
			sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE = (c_SECURITY_PROTECTED_NAS_MESSAGE*)EDAlloc (sizeof (c_SECURITY_PROTECTED_NAS_MESSAGE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE == NULL)
			INIT_c_SECURITY_PROTECTED_NAS_MESSAGE (sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE);
			break;
		}
		
		case ID_EPS_MM_Uplink_SERVICE_REQUEST: {
			sp->Data.fld_c_SERVICE_REQUEST = (c_SERVICE_REQUEST*)EDAlloc (sizeof (c_SERVICE_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_SERVICE_REQUEST == NULL)
			INIT_c_SERVICE_REQUEST (sp->Data.fld_c_SERVICE_REQUEST);
			break;
		}
		
		case ID_EPS_MM_Uplink_TRACKING_AREA_UPDATE_COMPLETE: {
			sp->Data.fld_c_TRACKING_AREA_UPDATE_COMPLETE = (c_TRACKING_AREA_UPDATE_COMPLETE*)EDAlloc (sizeof (c_TRACKING_AREA_UPDATE_COMPLETE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_TRACKING_AREA_UPDATE_COMPLETE == NULL)
			INIT_c_TRACKING_AREA_UPDATE_COMPLETE (sp->Data.fld_c_TRACKING_AREA_UPDATE_COMPLETE);
			break;
		}
		
		case ID_EPS_MM_Uplink_TRACKING_AREA_UPDATE_REQUEST: {
			sp->Data.fld_c_TRACKING_AREA_UPDATE_REQUEST = (c_TRACKING_AREA_UPDATE_REQUEST*)EDAlloc (sizeof (c_TRACKING_AREA_UPDATE_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_TRACKING_AREA_UPDATE_REQUEST == NULL)
			INIT_c_TRACKING_AREA_UPDATE_REQUEST (sp->Data.fld_c_TRACKING_AREA_UPDATE_REQUEST);
			break;
		}
		
		case ID_EPS_MM_Uplink_UPLINK_NAS_TRANSPORT: {
			sp->Data.fld_c_UPLINK_NAS_TRANSPORT = (c_UPLINK_NAS_TRANSPORT*)EDAlloc (sizeof (c_UPLINK_NAS_TRANSPORT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_UPLINK_NAS_TRANSPORT == NULL)
			INIT_c_UPLINK_NAS_TRANSPORT (sp->Data.fld_c_UPLINK_NAS_TRANSPORT);
			break;
		}
		
		case ID_EPS_MM_Uplink_UPLINK_GENERIC_NAS_TRANSPORT: {
			sp->Data.fld_c_UPLINK_GENERIC_NAS_TRANSPORT = (c_UPLINK_GENERIC_NAS_TRANSPORT*)EDAlloc (sizeof (c_UPLINK_GENERIC_NAS_TRANSPORT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_UPLINK_GENERIC_NAS_TRANSPORT == NULL)
			INIT_c_UPLINK_GENERIC_NAS_TRANSPORT (sp->Data.fld_c_UPLINK_GENERIC_NAS_TRANSPORT);
			break;
		}
		
		case ID_EPS_MM_Uplink_CONTROL_PLANE_SERVICE_REQUEST: {
			sp->Data.fld_c_CONTROL_PLANE_SERVICE_REQUEST = (c_CONTROL_PLANE_SERVICE_REQUEST*)EDAlloc (sizeof (c_CONTROL_PLANE_SERVICE_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_CONTROL_PLANE_SERVICE_REQUEST == NULL)
			INIT_c_CONTROL_PLANE_SERVICE_REQUEST (sp->Data.fld_c_CONTROL_PLANE_SERVICE_REQUEST);
			break;
		}
		
		default:;
	}
return ED_NO_ERRORS;
}

void FREE_TEPS_MM_Uplink_Data (TEPS_MM_Uplink_Data* sp)
{
	switch (sp->Type) {
		case ID_EPS_MM_Uplink_ATTACH_COMPLETE: {
			FREE_c_ATTACH_COMPLETE (sp->Data.fld_c_ATTACH_COMPLETE);
	EDFree (sp->Data.fld_c_ATTACH_COMPLETE );
			break;
		}
		
		case ID_EPS_MM_Uplink_ATTACH_REQUEST: {
			FREE_c_ATTACH_REQUEST (sp->Data.fld_c_ATTACH_REQUEST);
	EDFree (sp->Data.fld_c_ATTACH_REQUEST );
			break;
		}
		
		case ID_EPS_MM_Uplink_AUTHENTICATION_FAILURE: {
			FREE_c_AUTHENTICATION_FAILURE (sp->Data.fld_c_AUTHENTICATION_FAILURE);
	EDFree (sp->Data.fld_c_AUTHENTICATION_FAILURE );
			break;
		}
		
		case ID_EPS_MM_Uplink_AUTHENTICATION_RESPONSE: {
			FREE_c_AUTHENTICATION_RESPONSE (sp->Data.fld_c_AUTHENTICATION_RESPONSE);
	EDFree (sp->Data.fld_c_AUTHENTICATION_RESPONSE );
			break;
		}
		
		case ID_EPS_MM_Uplink_EPS_DETACH_ACCEPT_UP: {
			FREE_c_EPS_DETACH_ACCEPT_UP (sp->Data.fld_c_EPS_DETACH_ACCEPT_UP);
	EDFree (sp->Data.fld_c_EPS_DETACH_ACCEPT_UP );
			break;
		}
		
		case ID_EPS_MM_Uplink_EPS_DETACH_REQUEST_UP: {
			FREE_c_EPS_DETACH_REQUEST_UP (sp->Data.fld_c_EPS_DETACH_REQUEST_UP);
	EDFree (sp->Data.fld_c_EPS_DETACH_REQUEST_UP );
			break;
		}
		
		case ID_EPS_MM_Uplink_EMM_STATUS: {
			FREE_c_EMM_STATUS (sp->Data.fld_c_EMM_STATUS);
	EDFree (sp->Data.fld_c_EMM_STATUS );
			break;
		}
		
		case ID_EPS_MM_Uplink_EXTENDED_SERVICE_REQUEST: {
			FREE_c_EXTENDED_SERVICE_REQUEST (sp->Data.fld_c_EXTENDED_SERVICE_REQUEST);
	EDFree (sp->Data.fld_c_EXTENDED_SERVICE_REQUEST );
			break;
		}
		
		case ID_EPS_MM_Uplink_GUTI_REALLOCATION_COMPLETE: {
			FREE_c_GUTI_REALLOCATION_COMPLETE (sp->Data.fld_c_GUTI_REALLOCATION_COMPLETE);
	EDFree (sp->Data.fld_c_GUTI_REALLOCATION_COMPLETE );
			break;
		}
		
		case ID_EPS_MM_Uplink_IDENTITY_RESPONSE: {
			FREE_c_IDENTITY_RESPONSE (sp->Data.fld_c_IDENTITY_RESPONSE);
	EDFree (sp->Data.fld_c_IDENTITY_RESPONSE );
			break;
		}
		
		case ID_EPS_MM_Uplink_SECURITY_MODE_COMPLETE: {
			FREE_c_SECURITY_MODE_COMPLETE (sp->Data.fld_c_SECURITY_MODE_COMPLETE);
	EDFree (sp->Data.fld_c_SECURITY_MODE_COMPLETE );
			break;
		}
		
		case ID_EPS_MM_Uplink_SECURITY_MODE_REJECT: {
			FREE_c_SECURITY_MODE_REJECT (sp->Data.fld_c_SECURITY_MODE_REJECT);
	EDFree (sp->Data.fld_c_SECURITY_MODE_REJECT );
			break;
		}
		
		case ID_EPS_MM_Uplink_SECURITY_PROTECTED_NAS_MESSAGE: {
			FREE_c_SECURITY_PROTECTED_NAS_MESSAGE (sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE);
	EDFree (sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE );
			break;
		}
		
		case ID_EPS_MM_Uplink_SERVICE_REQUEST: {
			FREE_c_SERVICE_REQUEST (sp->Data.fld_c_SERVICE_REQUEST);
	EDFree (sp->Data.fld_c_SERVICE_REQUEST );
			break;
		}
		
		case ID_EPS_MM_Uplink_TRACKING_AREA_UPDATE_COMPLETE: {
			FREE_c_TRACKING_AREA_UPDATE_COMPLETE (sp->Data.fld_c_TRACKING_AREA_UPDATE_COMPLETE);
	EDFree (sp->Data.fld_c_TRACKING_AREA_UPDATE_COMPLETE );
			break;
		}
		
		case ID_EPS_MM_Uplink_TRACKING_AREA_UPDATE_REQUEST: {
			FREE_c_TRACKING_AREA_UPDATE_REQUEST (sp->Data.fld_c_TRACKING_AREA_UPDATE_REQUEST);
	EDFree (sp->Data.fld_c_TRACKING_AREA_UPDATE_REQUEST );
			break;
		}
		
		case ID_EPS_MM_Uplink_UPLINK_NAS_TRANSPORT: {
			FREE_c_UPLINK_NAS_TRANSPORT (sp->Data.fld_c_UPLINK_NAS_TRANSPORT);
	EDFree (sp->Data.fld_c_UPLINK_NAS_TRANSPORT );
			break;
		}
		
		case ID_EPS_MM_Uplink_UPLINK_GENERIC_NAS_TRANSPORT: {
			FREE_c_UPLINK_GENERIC_NAS_TRANSPORT (sp->Data.fld_c_UPLINK_GENERIC_NAS_TRANSPORT);
	EDFree (sp->Data.fld_c_UPLINK_GENERIC_NAS_TRANSPORT );
			break;
		}
		
		case ID_EPS_MM_Uplink_CONTROL_PLANE_SERVICE_REQUEST: {
			FREE_c_CONTROL_PLANE_SERVICE_REQUEST (sp->Data.fld_c_CONTROL_PLANE_SERVICE_REQUEST);
	EDFree (sp->Data.fld_c_CONTROL_PLANE_SERVICE_REQUEST );
			break;
		}
		
		default:;
	}

	sp->Type = ID_EPS_MM_Uplink_Unrecognized;
}

int SETPRESENT_TEPS_MM_Downlink_Data (TEPS_MM_Downlink_Data* sp, TEPS_MM_Downlink_Type toBeSetPresent)
{
	if (sp->Type == toBeSetPresent) return ED_NO_ERRORS;
	FREE_TEPS_MM_Downlink_Data (sp);
	sp->Type = toBeSetPresent;

	switch (sp->Type) {
		case ID_EPS_MM_Downlink_ATTACH_ACCEPT: {
			sp->Data.fld_c_ATTACH_ACCEPT = (c_ATTACH_ACCEPT*)EDAlloc (sizeof (c_ATTACH_ACCEPT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ATTACH_ACCEPT == NULL)
			INIT_c_ATTACH_ACCEPT (sp->Data.fld_c_ATTACH_ACCEPT);
			break;
		}
		
		case ID_EPS_MM_Downlink_ATTACH_REJECT: {
			sp->Data.fld_c_ATTACH_REJECT = (c_ATTACH_REJECT*)EDAlloc (sizeof (c_ATTACH_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ATTACH_REJECT == NULL)
			INIT_c_ATTACH_REJECT (sp->Data.fld_c_ATTACH_REJECT);
			break;
		}
		
		case ID_EPS_MM_Downlink_AUTHENTICATION_REJECT: {
			sp->Data.fld_c_AUTHENTICATION_REJECT = (c_AUTHENTICATION_REJECT*)EDAlloc (sizeof (c_AUTHENTICATION_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_AUTHENTICATION_REJECT == NULL)
			INIT_c_AUTHENTICATION_REJECT (sp->Data.fld_c_AUTHENTICATION_REJECT);
			break;
		}
		
		case ID_EPS_MM_Downlink_AUTHENTICATION_REQUEST: {
			sp->Data.fld_c_AUTHENTICATION_REQUEST = (c_AUTHENTICATION_REQUEST*)EDAlloc (sizeof (c_AUTHENTICATION_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_AUTHENTICATION_REQUEST == NULL)
			INIT_c_AUTHENTICATION_REQUEST (sp->Data.fld_c_AUTHENTICATION_REQUEST);
			break;
		}
		
		case ID_EPS_MM_Downlink_CS_SERVICE_NOTIFICATION: {
			sp->Data.fld_c_CS_SERVICE_NOTIFICATION = (c_CS_SERVICE_NOTIFICATION*)EDAlloc (sizeof (c_CS_SERVICE_NOTIFICATION)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_CS_SERVICE_NOTIFICATION == NULL)
			INIT_c_CS_SERVICE_NOTIFICATION (sp->Data.fld_c_CS_SERVICE_NOTIFICATION);
			break;
		}
		
		case ID_EPS_MM_Downlink_EPS_DETACH_ACCEPT_DN: {
			sp->Data.fld_c_EPS_DETACH_ACCEPT_DN = (c_EPS_DETACH_ACCEPT_DN*)EDAlloc (sizeof (c_EPS_DETACH_ACCEPT_DN)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EPS_DETACH_ACCEPT_DN == NULL)
			INIT_c_EPS_DETACH_ACCEPT_DN (sp->Data.fld_c_EPS_DETACH_ACCEPT_DN);
			break;
		}
		
		case ID_EPS_MM_Downlink_EPS_DETACH_REQUEST_DN: {
			sp->Data.fld_c_EPS_DETACH_REQUEST_DN = (c_EPS_DETACH_REQUEST_DN*)EDAlloc (sizeof (c_EPS_DETACH_REQUEST_DN)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EPS_DETACH_REQUEST_DN == NULL)
			INIT_c_EPS_DETACH_REQUEST_DN (sp->Data.fld_c_EPS_DETACH_REQUEST_DN);
			break;
		}
		
		case ID_EPS_MM_Downlink_DOWNLINK_NAS_TRANSPORT: {
			sp->Data.fld_c_DOWNLINK_NAS_TRANSPORT = (c_DOWNLINK_NAS_TRANSPORT*)EDAlloc (sizeof (c_DOWNLINK_NAS_TRANSPORT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_DOWNLINK_NAS_TRANSPORT == NULL)
			INIT_c_DOWNLINK_NAS_TRANSPORT (sp->Data.fld_c_DOWNLINK_NAS_TRANSPORT);
			break;
		}
		
		case ID_EPS_MM_Downlink_EMM_INFORMATION: {
			sp->Data.fld_c_EMM_INFORMATION = (c_EMM_INFORMATION*)EDAlloc (sizeof (c_EMM_INFORMATION)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EMM_INFORMATION == NULL)
			INIT_c_EMM_INFORMATION (sp->Data.fld_c_EMM_INFORMATION);
			break;
		}
		
		case ID_EPS_MM_Downlink_EMM_STATUS: {
			sp->Data.fld_c_EMM_STATUS = (c_EMM_STATUS*)EDAlloc (sizeof (c_EMM_STATUS)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EMM_STATUS == NULL)
			INIT_c_EMM_STATUS (sp->Data.fld_c_EMM_STATUS);
			break;
		}
		
		case ID_EPS_MM_Downlink_GUTI_REALLOCATION_COMMAND: {
			sp->Data.fld_c_GUTI_REALLOCATION_COMMAND = (c_GUTI_REALLOCATION_COMMAND*)EDAlloc (sizeof (c_GUTI_REALLOCATION_COMMAND)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_GUTI_REALLOCATION_COMMAND == NULL)
			INIT_c_GUTI_REALLOCATION_COMMAND (sp->Data.fld_c_GUTI_REALLOCATION_COMMAND);
			break;
		}
		
		case ID_EPS_MM_Downlink_IDENTITY_REQUEST: {
			sp->Data.fld_c_IDENTITY_REQUEST = (c_IDENTITY_REQUEST*)EDAlloc (sizeof (c_IDENTITY_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_IDENTITY_REQUEST == NULL)
			INIT_c_IDENTITY_REQUEST (sp->Data.fld_c_IDENTITY_REQUEST);
			break;
		}
		
		case ID_EPS_MM_Downlink_SECURITY_MODE_COMMAND: {
			sp->Data.fld_c_SECURITY_MODE_COMMAND = (c_SECURITY_MODE_COMMAND*)EDAlloc (sizeof (c_SECURITY_MODE_COMMAND)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_SECURITY_MODE_COMMAND == NULL)
			INIT_c_SECURITY_MODE_COMMAND (sp->Data.fld_c_SECURITY_MODE_COMMAND);
			break;
		}
		
		case ID_EPS_MM_Downlink_SECURITY_PROTECTED_NAS_MESSAGE: {
			sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE = (c_SECURITY_PROTECTED_NAS_MESSAGE*)EDAlloc (sizeof (c_SECURITY_PROTECTED_NAS_MESSAGE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE == NULL)
			INIT_c_SECURITY_PROTECTED_NAS_MESSAGE (sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE);
			break;
		}
		
		case ID_EPS_MM_Downlink_SERVICE_REJECT: {
			sp->Data.fld_c_SERVICE_REJECT = (c_SERVICE_REJECT*)EDAlloc (sizeof (c_SERVICE_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_SERVICE_REJECT == NULL)
			INIT_c_SERVICE_REJECT (sp->Data.fld_c_SERVICE_REJECT);
			break;
		}
		
		case ID_EPS_MM_Downlink_TRACKING_AREA_UPDATE_ACCEPT: {
			sp->Data.fld_c_TRACKING_AREA_UPDATE_ACCEPT = (c_TRACKING_AREA_UPDATE_ACCEPT*)EDAlloc (sizeof (c_TRACKING_AREA_UPDATE_ACCEPT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_TRACKING_AREA_UPDATE_ACCEPT == NULL)
			INIT_c_TRACKING_AREA_UPDATE_ACCEPT (sp->Data.fld_c_TRACKING_AREA_UPDATE_ACCEPT);
			break;
		}
		
		case ID_EPS_MM_Downlink_TRACKING_AREA_UPDATE_REJECT: {
			sp->Data.fld_c_TRACKING_AREA_UPDATE_REJECT = (c_TRACKING_AREA_UPDATE_REJECT*)EDAlloc (sizeof (c_TRACKING_AREA_UPDATE_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_TRACKING_AREA_UPDATE_REJECT == NULL)
			INIT_c_TRACKING_AREA_UPDATE_REJECT (sp->Data.fld_c_TRACKING_AREA_UPDATE_REJECT);
			break;
		}
		
		case ID_EPS_MM_Downlink_DOWNLINK_GENERIC_NAS_TRANSPORT: {
			sp->Data.fld_c_DOWNLINK_GENERIC_NAS_TRANSPORT = (c_DOWNLINK_GENERIC_NAS_TRANSPORT*)EDAlloc (sizeof (c_DOWNLINK_GENERIC_NAS_TRANSPORT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_DOWNLINK_GENERIC_NAS_TRANSPORT == NULL)
			INIT_c_DOWNLINK_GENERIC_NAS_TRANSPORT (sp->Data.fld_c_DOWNLINK_GENERIC_NAS_TRANSPORT);
			break;
		}
		
		case ID_EPS_MM_Downlink_SERVICE_ACCEPT: {
			sp->Data.fld_c_SERVICE_ACCEPT = (c_SERVICE_ACCEPT*)EDAlloc (sizeof (c_SERVICE_ACCEPT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_SERVICE_ACCEPT == NULL)
			INIT_c_SERVICE_ACCEPT (sp->Data.fld_c_SERVICE_ACCEPT);
			break;
		}
		
		default:;
	}
return ED_NO_ERRORS;
}

void FREE_TEPS_MM_Downlink_Data (TEPS_MM_Downlink_Data* sp)
{
	switch (sp->Type) {
		case ID_EPS_MM_Downlink_ATTACH_ACCEPT: {
			FREE_c_ATTACH_ACCEPT (sp->Data.fld_c_ATTACH_ACCEPT);
	EDFree (sp->Data.fld_c_ATTACH_ACCEPT );
			break;
		}
		
		case ID_EPS_MM_Downlink_ATTACH_REJECT: {
			FREE_c_ATTACH_REJECT (sp->Data.fld_c_ATTACH_REJECT);
	EDFree (sp->Data.fld_c_ATTACH_REJECT );
			break;
		}
		
		case ID_EPS_MM_Downlink_AUTHENTICATION_REJECT: {
			FREE_c_AUTHENTICATION_REJECT (sp->Data.fld_c_AUTHENTICATION_REJECT);
	EDFree (sp->Data.fld_c_AUTHENTICATION_REJECT );
			break;
		}
		
		case ID_EPS_MM_Downlink_AUTHENTICATION_REQUEST: {
			FREE_c_AUTHENTICATION_REQUEST (sp->Data.fld_c_AUTHENTICATION_REQUEST);
	EDFree (sp->Data.fld_c_AUTHENTICATION_REQUEST );
			break;
		}
		
		case ID_EPS_MM_Downlink_CS_SERVICE_NOTIFICATION: {
			FREE_c_CS_SERVICE_NOTIFICATION (sp->Data.fld_c_CS_SERVICE_NOTIFICATION);
	EDFree (sp->Data.fld_c_CS_SERVICE_NOTIFICATION );
			break;
		}
		
		case ID_EPS_MM_Downlink_EPS_DETACH_ACCEPT_DN: {
			FREE_c_EPS_DETACH_ACCEPT_DN (sp->Data.fld_c_EPS_DETACH_ACCEPT_DN);
	EDFree (sp->Data.fld_c_EPS_DETACH_ACCEPT_DN );
			break;
		}
		
		case ID_EPS_MM_Downlink_EPS_DETACH_REQUEST_DN: {
			FREE_c_EPS_DETACH_REQUEST_DN (sp->Data.fld_c_EPS_DETACH_REQUEST_DN);
	EDFree (sp->Data.fld_c_EPS_DETACH_REQUEST_DN );
			break;
		}
		
		case ID_EPS_MM_Downlink_DOWNLINK_NAS_TRANSPORT: {
			FREE_c_DOWNLINK_NAS_TRANSPORT (sp->Data.fld_c_DOWNLINK_NAS_TRANSPORT);
	EDFree (sp->Data.fld_c_DOWNLINK_NAS_TRANSPORT );
			break;
		}
		
		case ID_EPS_MM_Downlink_EMM_INFORMATION: {
			FREE_c_EMM_INFORMATION (sp->Data.fld_c_EMM_INFORMATION);
	EDFree (sp->Data.fld_c_EMM_INFORMATION );
			break;
		}
		
		case ID_EPS_MM_Downlink_EMM_STATUS: {
			FREE_c_EMM_STATUS (sp->Data.fld_c_EMM_STATUS);
	EDFree (sp->Data.fld_c_EMM_STATUS );
			break;
		}
		
		case ID_EPS_MM_Downlink_GUTI_REALLOCATION_COMMAND: {
			FREE_c_GUTI_REALLOCATION_COMMAND (sp->Data.fld_c_GUTI_REALLOCATION_COMMAND);
	EDFree (sp->Data.fld_c_GUTI_REALLOCATION_COMMAND );
			break;
		}
		
		case ID_EPS_MM_Downlink_IDENTITY_REQUEST: {
			FREE_c_IDENTITY_REQUEST (sp->Data.fld_c_IDENTITY_REQUEST);
	EDFree (sp->Data.fld_c_IDENTITY_REQUEST );
			break;
		}
		
		case ID_EPS_MM_Downlink_SECURITY_MODE_COMMAND: {
			FREE_c_SECURITY_MODE_COMMAND (sp->Data.fld_c_SECURITY_MODE_COMMAND);
	EDFree (sp->Data.fld_c_SECURITY_MODE_COMMAND );
			break;
		}
		
		case ID_EPS_MM_Downlink_SECURITY_PROTECTED_NAS_MESSAGE: {
			FREE_c_SECURITY_PROTECTED_NAS_MESSAGE (sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE);
	EDFree (sp->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE );
			break;
		}
		
		case ID_EPS_MM_Downlink_SERVICE_REJECT: {
			FREE_c_SERVICE_REJECT (sp->Data.fld_c_SERVICE_REJECT);
	EDFree (sp->Data.fld_c_SERVICE_REJECT );
			break;
		}
		
		case ID_EPS_MM_Downlink_TRACKING_AREA_UPDATE_ACCEPT: {
			FREE_c_TRACKING_AREA_UPDATE_ACCEPT (sp->Data.fld_c_TRACKING_AREA_UPDATE_ACCEPT);
	EDFree (sp->Data.fld_c_TRACKING_AREA_UPDATE_ACCEPT );
			break;
		}
		
		case ID_EPS_MM_Downlink_TRACKING_AREA_UPDATE_REJECT: {
			FREE_c_TRACKING_AREA_UPDATE_REJECT (sp->Data.fld_c_TRACKING_AREA_UPDATE_REJECT);
	EDFree (sp->Data.fld_c_TRACKING_AREA_UPDATE_REJECT );
			break;
		}
		
		case ID_EPS_MM_Downlink_DOWNLINK_GENERIC_NAS_TRANSPORT: {
			FREE_c_DOWNLINK_GENERIC_NAS_TRANSPORT (sp->Data.fld_c_DOWNLINK_GENERIC_NAS_TRANSPORT);
	EDFree (sp->Data.fld_c_DOWNLINK_GENERIC_NAS_TRANSPORT );
			break;
		}
		
		case ID_EPS_MM_Downlink_SERVICE_ACCEPT: {
			FREE_c_SERVICE_ACCEPT (sp->Data.fld_c_SERVICE_ACCEPT);
	EDFree (sp->Data.fld_c_SERVICE_ACCEPT );
			break;
		}
		
		default:;
	}

	sp->Type = ID_EPS_MM_Downlink_Unrecognized;
}

int SETPRESENT_TEPS_SM_Uplink_Data (TEPS_SM_Uplink_Data* sp, TEPS_SM_Uplink_Type toBeSetPresent)
{
	if (sp->Type == toBeSetPresent) return ED_NO_ERRORS;
	FREE_TEPS_SM_Uplink_Data (sp);
	sp->Type = toBeSetPresent;

	switch (sp->Type) {
		case ID_EPS_SM_Uplink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT: {
			sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT = (c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT*)EDAlloc (sizeof (c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT == NULL)
			INIT_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT);
			break;
		}
		
		case ID_EPS_SM_Uplink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT: {
			sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT = (c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT*)EDAlloc (sizeof (c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT == NULL)
			INIT_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT);
			break;
		}
		
		case ID_EPS_SM_Uplink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT: {
			sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT = (c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT*)EDAlloc (sizeof (c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT == NULL)
			INIT_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT);
			break;
		}
		
		case ID_EPS_SM_Uplink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT: {
			sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT = (c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT*)EDAlloc (sizeof (c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT == NULL)
			INIT_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT);
			break;
		}
		
		case ID_EPS_SM_Uplink_BEARER_RESOURCE_ALLOCATION_REQUEST: {
			sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REQUEST = (c_BEARER_RESOURCE_ALLOCATION_REQUEST*)EDAlloc (sizeof (c_BEARER_RESOURCE_ALLOCATION_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REQUEST == NULL)
			INIT_c_BEARER_RESOURCE_ALLOCATION_REQUEST (sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Uplink_BEARER_RESOURCE_MODIFICATION_REQUEST: {
			sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REQUEST = (c_BEARER_RESOURCE_MODIFICATION_REQUEST*)EDAlloc (sizeof (c_BEARER_RESOURCE_MODIFICATION_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REQUEST == NULL)
			INIT_c_BEARER_RESOURCE_MODIFICATION_REQUEST (sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Uplink_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT: {
			sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT = (c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT*)EDAlloc (sizeof (c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT == NULL)
			INIT_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT (sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT);
			break;
		}
		
		case ID_EPS_SM_Uplink_ESM_DUMMY_MESSAGE: {
			sp->Data.fld_c_ESM_DUMMY_MESSAGE = (c_ESM_DUMMY_MESSAGE*)EDAlloc (sizeof (c_ESM_DUMMY_MESSAGE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ESM_DUMMY_MESSAGE == NULL)
			INIT_c_ESM_DUMMY_MESSAGE (sp->Data.fld_c_ESM_DUMMY_MESSAGE);
			break;
		}
		
		case ID_EPS_SM_Uplink_ESM_INFORMATION_RESPONSE: {
			sp->Data.fld_c_ESM_INFORMATION_RESPONSE = (c_ESM_INFORMATION_RESPONSE*)EDAlloc (sizeof (c_ESM_INFORMATION_RESPONSE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ESM_INFORMATION_RESPONSE == NULL)
			INIT_c_ESM_INFORMATION_RESPONSE (sp->Data.fld_c_ESM_INFORMATION_RESPONSE);
			break;
		}
		
		case ID_EPS_SM_Uplink_ESM_STATUS: {
			sp->Data.fld_c_ESM_STATUS = (c_ESM_STATUS*)EDAlloc (sizeof (c_ESM_STATUS)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ESM_STATUS == NULL)
			INIT_c_ESM_STATUS (sp->Data.fld_c_ESM_STATUS);
			break;
		}
		
		case ID_EPS_SM_Uplink_MODIFY_EPS_BEARER_CONTEXT_ACCEPT: {
			sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT = (c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT*)EDAlloc (sizeof (c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT == NULL)
			INIT_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT);
			break;
		}
		
		case ID_EPS_SM_Uplink_MODIFY_EPS_BEARER_CONTEXT_REJECT: {
			sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REJECT = (c_MODIFY_EPS_BEARER_CONTEXT_REJECT*)EDAlloc (sizeof (c_MODIFY_EPS_BEARER_CONTEXT_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REJECT == NULL)
			INIT_c_MODIFY_EPS_BEARER_CONTEXT_REJECT (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REJECT);
			break;
		}
		
		case ID_EPS_SM_Uplink_PDN_CONNECTIVITY_REQUEST: {
			sp->Data.fld_c_PDN_CONNECTIVITY_REQUEST = (c_PDN_CONNECTIVITY_REQUEST*)EDAlloc (sizeof (c_PDN_CONNECTIVITY_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_PDN_CONNECTIVITY_REQUEST == NULL)
			INIT_c_PDN_CONNECTIVITY_REQUEST (sp->Data.fld_c_PDN_CONNECTIVITY_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Uplink_PDN_DISCONNECT_REQUEST: {
			sp->Data.fld_c_PDN_DISCONNECT_REQUEST = (c_PDN_DISCONNECT_REQUEST*)EDAlloc (sizeof (c_PDN_DISCONNECT_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_PDN_DISCONNECT_REQUEST == NULL)
			INIT_c_PDN_DISCONNECT_REQUEST (sp->Data.fld_c_PDN_DISCONNECT_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Uplink_REMOTE_UE_REPORT: {
			sp->Data.fld_c_REMOTE_UE_REPORT = (c_REMOTE_UE_REPORT*)EDAlloc (sizeof (c_REMOTE_UE_REPORT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_REMOTE_UE_REPORT == NULL)
			INIT_c_REMOTE_UE_REPORT (sp->Data.fld_c_REMOTE_UE_REPORT);
			break;
		}
		
		case ID_EPS_SM_Uplink_ESM_DATA_TRANSPORT: {
			sp->Data.fld_c_ESM_DATA_TRANSPORT = (c_ESM_DATA_TRANSPORT*)EDAlloc (sizeof (c_ESM_DATA_TRANSPORT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ESM_DATA_TRANSPORT == NULL)
			INIT_c_ESM_DATA_TRANSPORT (sp->Data.fld_c_ESM_DATA_TRANSPORT);
			break;
		}
		
		default:;
	}
return ED_NO_ERRORS;
}

void FREE_TEPS_SM_Uplink_Data (TEPS_SM_Uplink_Data* sp)
{
	switch (sp->Type) {
		case ID_EPS_SM_Uplink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT: {
			FREE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT);
	EDFree (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT );
			break;
		}
		
		case ID_EPS_SM_Uplink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT: {
			FREE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT);
	EDFree (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT );
			break;
		}
		
		case ID_EPS_SM_Uplink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT: {
			FREE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT);
	EDFree (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT );
			break;
		}
		
		case ID_EPS_SM_Uplink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT: {
			FREE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT);
	EDFree (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT );
			break;
		}
		
		case ID_EPS_SM_Uplink_BEARER_RESOURCE_ALLOCATION_REQUEST: {
			FREE_c_BEARER_RESOURCE_ALLOCATION_REQUEST (sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REQUEST);
	EDFree (sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Uplink_BEARER_RESOURCE_MODIFICATION_REQUEST: {
			FREE_c_BEARER_RESOURCE_MODIFICATION_REQUEST (sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REQUEST);
	EDFree (sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Uplink_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT: {
			FREE_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT (sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT);
	EDFree (sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT );
			break;
		}
		
		case ID_EPS_SM_Uplink_ESM_DUMMY_MESSAGE: {
			FREE_c_ESM_DUMMY_MESSAGE (sp->Data.fld_c_ESM_DUMMY_MESSAGE);
	EDFree (sp->Data.fld_c_ESM_DUMMY_MESSAGE );
			break;
		}
		
		case ID_EPS_SM_Uplink_ESM_INFORMATION_RESPONSE: {
			FREE_c_ESM_INFORMATION_RESPONSE (sp->Data.fld_c_ESM_INFORMATION_RESPONSE);
	EDFree (sp->Data.fld_c_ESM_INFORMATION_RESPONSE );
			break;
		}
		
		case ID_EPS_SM_Uplink_ESM_STATUS: {
			FREE_c_ESM_STATUS (sp->Data.fld_c_ESM_STATUS);
	EDFree (sp->Data.fld_c_ESM_STATUS );
			break;
		}
		
		case ID_EPS_SM_Uplink_MODIFY_EPS_BEARER_CONTEXT_ACCEPT: {
			FREE_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT);
	EDFree (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT );
			break;
		}
		
		case ID_EPS_SM_Uplink_MODIFY_EPS_BEARER_CONTEXT_REJECT: {
			FREE_c_MODIFY_EPS_BEARER_CONTEXT_REJECT (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REJECT);
	EDFree (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REJECT );
			break;
		}
		
		case ID_EPS_SM_Uplink_PDN_CONNECTIVITY_REQUEST: {
			FREE_c_PDN_CONNECTIVITY_REQUEST (sp->Data.fld_c_PDN_CONNECTIVITY_REQUEST);
	EDFree (sp->Data.fld_c_PDN_CONNECTIVITY_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Uplink_PDN_DISCONNECT_REQUEST: {
			FREE_c_PDN_DISCONNECT_REQUEST (sp->Data.fld_c_PDN_DISCONNECT_REQUEST);
	EDFree (sp->Data.fld_c_PDN_DISCONNECT_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Uplink_REMOTE_UE_REPORT: {
			FREE_c_REMOTE_UE_REPORT (sp->Data.fld_c_REMOTE_UE_REPORT);
	EDFree (sp->Data.fld_c_REMOTE_UE_REPORT );
			break;
		}
		
		case ID_EPS_SM_Uplink_ESM_DATA_TRANSPORT: {
			FREE_c_ESM_DATA_TRANSPORT (sp->Data.fld_c_ESM_DATA_TRANSPORT);
	EDFree (sp->Data.fld_c_ESM_DATA_TRANSPORT );
			break;
		}
		
		default:;
	}

	sp->Type = ID_EPS_SM_Uplink_Unrecognized;
}

int SETPRESENT_TEPS_SM_Downlink_Data (TEPS_SM_Downlink_Data* sp, TEPS_SM_Downlink_Type toBeSetPresent)
{
	if (sp->Type == toBeSetPresent) return ED_NO_ERRORS;
	FREE_TEPS_SM_Downlink_Data (sp);
	sp->Type = toBeSetPresent;

	switch (sp->Type) {
		case ID_EPS_SM_Downlink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST: {
			sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST = (c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST*)EDAlloc (sizeof (c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST == NULL)
			INIT_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Downlink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST: {
			sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST = (c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST*)EDAlloc (sizeof (c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST == NULL)
			INIT_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Downlink_BEARER_RESOURCE_ALLOCATION_REJECT: {
			sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REJECT = (c_BEARER_RESOURCE_ALLOCATION_REJECT*)EDAlloc (sizeof (c_BEARER_RESOURCE_ALLOCATION_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REJECT == NULL)
			INIT_c_BEARER_RESOURCE_ALLOCATION_REJECT (sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REJECT);
			break;
		}
		
		case ID_EPS_SM_Downlink_BEARER_RESOURCE_MODIFICATION_REJECT: {
			sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REJECT = (c_BEARER_RESOURCE_MODIFICATION_REJECT*)EDAlloc (sizeof (c_BEARER_RESOURCE_MODIFICATION_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REJECT == NULL)
			INIT_c_BEARER_RESOURCE_MODIFICATION_REJECT (sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REJECT);
			break;
		}
		
		case ID_EPS_SM_Downlink_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST: {
			sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST = (c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST*)EDAlloc (sizeof (c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST == NULL)
			INIT_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST (sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Downlink_ESM_DUMMY_MESSAGE: {
			sp->Data.fld_c_ESM_DUMMY_MESSAGE = (c_ESM_DUMMY_MESSAGE*)EDAlloc (sizeof (c_ESM_DUMMY_MESSAGE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ESM_DUMMY_MESSAGE == NULL)
			INIT_c_ESM_DUMMY_MESSAGE (sp->Data.fld_c_ESM_DUMMY_MESSAGE);
			break;
		}
		
		case ID_EPS_SM_Downlink_ESM_INFORMATION_REQUEST: {
			sp->Data.fld_c_ESM_INFORMATION_REQUEST = (c_ESM_INFORMATION_REQUEST*)EDAlloc (sizeof (c_ESM_INFORMATION_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ESM_INFORMATION_REQUEST == NULL)
			INIT_c_ESM_INFORMATION_REQUEST (sp->Data.fld_c_ESM_INFORMATION_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Downlink_ESM_STATUS: {
			sp->Data.fld_c_ESM_STATUS = (c_ESM_STATUS*)EDAlloc (sizeof (c_ESM_STATUS)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ESM_STATUS == NULL)
			INIT_c_ESM_STATUS (sp->Data.fld_c_ESM_STATUS);
			break;
		}
		
		case ID_EPS_SM_Downlink_MODIFY_EPS_BEARER_CONTEXT_REQUEST: {
			sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST = (c_MODIFY_EPS_BEARER_CONTEXT_REQUEST*)EDAlloc (sizeof (c_MODIFY_EPS_BEARER_CONTEXT_REQUEST)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST == NULL)
			INIT_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST);
			break;
		}
		
		case ID_EPS_SM_Downlink_EPS_NOTIFICATION: {
			sp->Data.fld_c_EPS_NOTIFICATION = (c_EPS_NOTIFICATION*)EDAlloc (sizeof (c_EPS_NOTIFICATION)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_EPS_NOTIFICATION == NULL)
			INIT_c_EPS_NOTIFICATION (sp->Data.fld_c_EPS_NOTIFICATION);
			break;
		}
		
		case ID_EPS_SM_Downlink_PDN_CONNECTIVITY_REJECT: {
			sp->Data.fld_c_PDN_CONNECTIVITY_REJECT = (c_PDN_CONNECTIVITY_REJECT*)EDAlloc (sizeof (c_PDN_CONNECTIVITY_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_PDN_CONNECTIVITY_REJECT == NULL)
			INIT_c_PDN_CONNECTIVITY_REJECT (sp->Data.fld_c_PDN_CONNECTIVITY_REJECT);
			break;
		}
		
		case ID_EPS_SM_Downlink_PDN_DISCONNECT_REJECT: {
			sp->Data.fld_c_PDN_DISCONNECT_REJECT = (c_PDN_DISCONNECT_REJECT*)EDAlloc (sizeof (c_PDN_DISCONNECT_REJECT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_PDN_DISCONNECT_REJECT == NULL)
			INIT_c_PDN_DISCONNECT_REJECT (sp->Data.fld_c_PDN_DISCONNECT_REJECT);
			break;
		}
		
		case ID_EPS_SM_Downlink_REMOTE_UE_REPORT_RESPONSE: {
			sp->Data.fld_c_REMOTE_UE_REPORT_RESPONSE = (c_REMOTE_UE_REPORT_RESPONSE*)EDAlloc (sizeof (c_REMOTE_UE_REPORT_RESPONSE)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_REMOTE_UE_REPORT_RESPONSE == NULL)
			INIT_c_REMOTE_UE_REPORT_RESPONSE (sp->Data.fld_c_REMOTE_UE_REPORT_RESPONSE);
			break;
		}
		
		case ID_EPS_SM_Downlink_ESM_DATA_TRANSPORT: {
			sp->Data.fld_c_ESM_DATA_TRANSPORT = (c_ESM_DATA_TRANSPORT*)EDAlloc (sizeof (c_ESM_DATA_TRANSPORT)); ED_CHECK_OUT_OF_MEMORY_DISCARD(sp->Data.fld_c_ESM_DATA_TRANSPORT == NULL)
			INIT_c_ESM_DATA_TRANSPORT (sp->Data.fld_c_ESM_DATA_TRANSPORT);
			break;
		}
		
		default:;
	}
return ED_NO_ERRORS;
}

void FREE_TEPS_SM_Downlink_Data (TEPS_SM_Downlink_Data* sp)
{
	switch (sp->Type) {
		case ID_EPS_SM_Downlink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST: {
			FREE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST);
	EDFree (sp->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Downlink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST: {
			FREE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST);
	EDFree (sp->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Downlink_BEARER_RESOURCE_ALLOCATION_REJECT: {
			FREE_c_BEARER_RESOURCE_ALLOCATION_REJECT (sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REJECT);
	EDFree (sp->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REJECT );
			break;
		}
		
		case ID_EPS_SM_Downlink_BEARER_RESOURCE_MODIFICATION_REJECT: {
			FREE_c_BEARER_RESOURCE_MODIFICATION_REJECT (sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REJECT);
	EDFree (sp->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REJECT );
			break;
		}
		
		case ID_EPS_SM_Downlink_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST: {
			FREE_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST (sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST);
	EDFree (sp->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Downlink_ESM_DUMMY_MESSAGE: {
			FREE_c_ESM_DUMMY_MESSAGE (sp->Data.fld_c_ESM_DUMMY_MESSAGE);
	EDFree (sp->Data.fld_c_ESM_DUMMY_MESSAGE );
			break;
		}
		
		case ID_EPS_SM_Downlink_ESM_INFORMATION_REQUEST: {
			FREE_c_ESM_INFORMATION_REQUEST (sp->Data.fld_c_ESM_INFORMATION_REQUEST);
	EDFree (sp->Data.fld_c_ESM_INFORMATION_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Downlink_ESM_STATUS: {
			FREE_c_ESM_STATUS (sp->Data.fld_c_ESM_STATUS);
	EDFree (sp->Data.fld_c_ESM_STATUS );
			break;
		}
		
		case ID_EPS_SM_Downlink_MODIFY_EPS_BEARER_CONTEXT_REQUEST: {
			FREE_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST);
	EDFree (sp->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST );
			break;
		}
		
		case ID_EPS_SM_Downlink_EPS_NOTIFICATION: {
			FREE_c_EPS_NOTIFICATION (sp->Data.fld_c_EPS_NOTIFICATION);
	EDFree (sp->Data.fld_c_EPS_NOTIFICATION );
			break;
		}
		
		case ID_EPS_SM_Downlink_PDN_CONNECTIVITY_REJECT: {
			FREE_c_PDN_CONNECTIVITY_REJECT (sp->Data.fld_c_PDN_CONNECTIVITY_REJECT);
	EDFree (sp->Data.fld_c_PDN_CONNECTIVITY_REJECT );
			break;
		}
		
		case ID_EPS_SM_Downlink_PDN_DISCONNECT_REJECT: {
			FREE_c_PDN_DISCONNECT_REJECT (sp->Data.fld_c_PDN_DISCONNECT_REJECT);
	EDFree (sp->Data.fld_c_PDN_DISCONNECT_REJECT );
			break;
		}
		
		case ID_EPS_SM_Downlink_REMOTE_UE_REPORT_RESPONSE: {
			FREE_c_REMOTE_UE_REPORT_RESPONSE (sp->Data.fld_c_REMOTE_UE_REPORT_RESPONSE);
	EDFree (sp->Data.fld_c_REMOTE_UE_REPORT_RESPONSE );
			break;
		}
		
		case ID_EPS_SM_Downlink_ESM_DATA_TRANSPORT: {
			FREE_c_ESM_DATA_TRANSPORT (sp->Data.fld_c_ESM_DATA_TRANSPORT);
	EDFree (sp->Data.fld_c_ESM_DATA_TRANSPORT );
			break;
		}
		
		default:;
	}

	sp->Type = ID_EPS_SM_Downlink_Unrecognized;
}

#ifdef ED_REVERSED_INTEGER
#error ED_REVERSED_INTEGER is defined!
#endif


int SetDecode_EPS_MM_Uplink (const char* buffer, TEPS_MM_Uplink_Data* data, int bitLen)
{
	int retLen = 0;
	
	/*-----------------------------------------------------------------
		Key is set to a single value containing protocol discriminator,
		skip indicator and message type.
		For example, message ASSIGNMENT_COMMAND has:
			skip indicator         = 0000 (0x0)
			protocol discriminator = 0110 (0x6)
			message type           = 00101110 (0x2E)
		In this case, key will be set to 0x602E.
		Skip indicator could be in some cases a transaction identifier.
		In such cases, it will be set to 0 for matching purposes.
	------------------------------------------------------------------*/
	unsigned /****/ int key /*1*/ = ((((unsigned char)buffer [0]) << 8) | ((unsigned char)buffer [1]))/*2*/;/*3*/
		data->ProtocolDiscriminator = (int)(((unsigned char)buffer [0]) & 0x0f);
	data->MessageType = (int)((unsigned char)buffer [1]);
	
	ED_WARNING_REMOVER(key);
	/* Specific behaviour for TS24.301: recognize messages without Message Type */
	switch (((unsigned char)buffer [0]) >> 4) {
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 12:
		case 13:
		case 14:
		case 15:
	
			/* Set the message type to 0 */
			key &= 0xFF00;
			break;
	}
	switch (key) {
			/* Detect signal ATTACH_COMPLETE */
		case 0x0743: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_ATTACH_COMPLETE), != ED_NO_ERRORS)
			INIT_c_ATTACH_COMPLETE (data->Data.fld_c_ATTACH_COMPLETE);
			retLen = DECODE_c_ATTACH_COMPLETE (buffer, 0, data->Data.fld_c_ATTACH_COMPLETE, bitLen);
		
			return retLen;
		}
		/* Detect signal ATTACH_REQUEST */
		case 0x0741: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_ATTACH_REQUEST), != ED_NO_ERRORS)
			INIT_c_ATTACH_REQUEST (data->Data.fld_c_ATTACH_REQUEST);
			retLen = DECODE_c_ATTACH_REQUEST (buffer, 0, data->Data.fld_c_ATTACH_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal AUTHENTICATION_FAILURE */
		case 0x075C: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_AUTHENTICATION_FAILURE), != ED_NO_ERRORS)
			INIT_c_AUTHENTICATION_FAILURE (data->Data.fld_c_AUTHENTICATION_FAILURE);
			retLen = DECODE_c_AUTHENTICATION_FAILURE (buffer, 0, data->Data.fld_c_AUTHENTICATION_FAILURE, bitLen);
		
			return retLen;
		}
		/* Detect signal AUTHENTICATION_RESPONSE */
		case 0x0753: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_AUTHENTICATION_RESPONSE), != ED_NO_ERRORS)
			INIT_c_AUTHENTICATION_RESPONSE (data->Data.fld_c_AUTHENTICATION_RESPONSE);
			retLen = DECODE_c_AUTHENTICATION_RESPONSE (buffer, 0, data->Data.fld_c_AUTHENTICATION_RESPONSE, bitLen);
		
			return retLen;
		}
		/* Detect signal EPS_DETACH_ACCEPT_UP */
		case 0x0746: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_EPS_DETACH_ACCEPT_UP), != ED_NO_ERRORS)
			INIT_c_EPS_DETACH_ACCEPT_UP (data->Data.fld_c_EPS_DETACH_ACCEPT_UP);
			retLen = DECODE_c_EPS_DETACH_ACCEPT_UP (buffer, 0, data->Data.fld_c_EPS_DETACH_ACCEPT_UP, bitLen);
		
			return retLen;
		}
		/* Detect signal EPS_DETACH_REQUEST_UP */
		case 0x0745: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_EPS_DETACH_REQUEST_UP), != ED_NO_ERRORS)
			INIT_c_EPS_DETACH_REQUEST_UP (data->Data.fld_c_EPS_DETACH_REQUEST_UP);
			retLen = DECODE_c_EPS_DETACH_REQUEST_UP (buffer, 0, data->Data.fld_c_EPS_DETACH_REQUEST_UP, bitLen);
		
			return retLen;
		}
		/* Detect signal EMM_STATUS */
		case 0x0760: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_EMM_STATUS), != ED_NO_ERRORS)
			INIT_c_EMM_STATUS (data->Data.fld_c_EMM_STATUS);
			retLen = DECODE_c_EMM_STATUS (buffer, 0, data->Data.fld_c_EMM_STATUS, bitLen);
		
			return retLen;
		}
		/* Detect signal EXTENDED_SERVICE_REQUEST */
		case 0x074C: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_EXTENDED_SERVICE_REQUEST), != ED_NO_ERRORS)
			INIT_c_EXTENDED_SERVICE_REQUEST (data->Data.fld_c_EXTENDED_SERVICE_REQUEST);
			retLen = DECODE_c_EXTENDED_SERVICE_REQUEST (buffer, 0, data->Data.fld_c_EXTENDED_SERVICE_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal GUTI_REALLOCATION_COMPLETE */
		case 0x0751: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_GUTI_REALLOCATION_COMPLETE), != ED_NO_ERRORS)
			INIT_c_GUTI_REALLOCATION_COMPLETE (data->Data.fld_c_GUTI_REALLOCATION_COMPLETE);
			retLen = DECODE_c_GUTI_REALLOCATION_COMPLETE (buffer, 0, data->Data.fld_c_GUTI_REALLOCATION_COMPLETE, bitLen);
		
			return retLen;
		}
		/* Detect signal IDENTITY_RESPONSE */
		case 0x0756: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_IDENTITY_RESPONSE), != ED_NO_ERRORS)
			INIT_c_IDENTITY_RESPONSE (data->Data.fld_c_IDENTITY_RESPONSE);
			retLen = DECODE_c_IDENTITY_RESPONSE (buffer, 0, data->Data.fld_c_IDENTITY_RESPONSE, bitLen);
		
			return retLen;
		}
		/* Detect signal SECURITY_MODE_COMPLETE */
		case 0x075E:
		case 0x475E: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_SECURITY_MODE_COMPLETE), != ED_NO_ERRORS)
			INIT_c_SECURITY_MODE_COMPLETE (data->Data.fld_c_SECURITY_MODE_COMPLETE);
			retLen = DECODE_c_SECURITY_MODE_COMPLETE (buffer, 0, data->Data.fld_c_SECURITY_MODE_COMPLETE, bitLen);
		
			return retLen;
		}
		/* Detect signal SECURITY_MODE_REJECT */
		case 0x075F: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_SECURITY_MODE_REJECT), != ED_NO_ERRORS)
			INIT_c_SECURITY_MODE_REJECT (data->Data.fld_c_SECURITY_MODE_REJECT);
			retLen = DECODE_c_SECURITY_MODE_REJECT (buffer, 0, data->Data.fld_c_SECURITY_MODE_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal SECURITY_PROTECTED_NAS_MESSAGE */
		case 0x1700:
		case 0x2700:
		case 0x3700:
		case 0x4700:
		case 0x5700: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_SECURITY_PROTECTED_NAS_MESSAGE), != ED_NO_ERRORS)
			INIT_c_SECURITY_PROTECTED_NAS_MESSAGE (data->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE);
			retLen = DECODE_c_SECURITY_PROTECTED_NAS_MESSAGE (buffer, 0, data->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE, bitLen);
		
			return retLen;
		}
		/* Detect signal SERVICE_REQUEST */
		case 0xC700:
		case 0xD700:
		case 0xE700:
		case 0xF700: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_SERVICE_REQUEST), != ED_NO_ERRORS)
			INIT_c_SERVICE_REQUEST (data->Data.fld_c_SERVICE_REQUEST);
			retLen = DECODE_c_SERVICE_REQUEST (buffer, 0, data->Data.fld_c_SERVICE_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal TRACKING_AREA_UPDATE_COMPLETE */
		case 0x074A: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_TRACKING_AREA_UPDATE_COMPLETE), != ED_NO_ERRORS)
			INIT_c_TRACKING_AREA_UPDATE_COMPLETE (data->Data.fld_c_TRACKING_AREA_UPDATE_COMPLETE);
			retLen = DECODE_c_TRACKING_AREA_UPDATE_COMPLETE (buffer, 0, data->Data.fld_c_TRACKING_AREA_UPDATE_COMPLETE, bitLen);
		
			return retLen;
		}
		/* Detect signal TRACKING_AREA_UPDATE_REQUEST */
		case 0x0748: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_TRACKING_AREA_UPDATE_REQUEST), != ED_NO_ERRORS)
			INIT_c_TRACKING_AREA_UPDATE_REQUEST (data->Data.fld_c_TRACKING_AREA_UPDATE_REQUEST);
			retLen = DECODE_c_TRACKING_AREA_UPDATE_REQUEST (buffer, 0, data->Data.fld_c_TRACKING_AREA_UPDATE_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal UPLINK_NAS_TRANSPORT */
		case 0x0763: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_UPLINK_NAS_TRANSPORT), != ED_NO_ERRORS)
			INIT_c_UPLINK_NAS_TRANSPORT (data->Data.fld_c_UPLINK_NAS_TRANSPORT);
			retLen = DECODE_c_UPLINK_NAS_TRANSPORT (buffer, 0, data->Data.fld_c_UPLINK_NAS_TRANSPORT, bitLen);
		
			return retLen;
		}
		/* Detect signal UPLINK_GENERIC_NAS_TRANSPORT */
		case 0x0769: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_UPLINK_GENERIC_NAS_TRANSPORT), != ED_NO_ERRORS)
			INIT_c_UPLINK_GENERIC_NAS_TRANSPORT (data->Data.fld_c_UPLINK_GENERIC_NAS_TRANSPORT);
			retLen = DECODE_c_UPLINK_GENERIC_NAS_TRANSPORT (buffer, 0, data->Data.fld_c_UPLINK_GENERIC_NAS_TRANSPORT, bitLen);
		
			return retLen;
		}
		/* Detect signal CONTROL_PLANE_SERVICE_REQUEST */
		case 0x074D: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Uplink_Data (data, ID_EPS_MM_Uplink_CONTROL_PLANE_SERVICE_REQUEST), != ED_NO_ERRORS)
			INIT_c_CONTROL_PLANE_SERVICE_REQUEST (data->Data.fld_c_CONTROL_PLANE_SERVICE_REQUEST);
			retLen = DECODE_c_CONTROL_PLANE_SERVICE_REQUEST (buffer, 0, data->Data.fld_c_CONTROL_PLANE_SERVICE_REQUEST, bitLen);
		
			return retLen;
		}

		default:;
	}
	data->Type = ID_EPS_MM_Uplink_Unrecognized;

	return ED_UNKNOWN_MESSAGE;
}
			
#ifndef ED_EXCLUDE_1_0_33_COMPATIBILITY
	int Decode_EPS_MM_Uplink (const char* buffer, int len, TEPS_MM_Uplink_Data* data)
	{
		if (SetDecode_EPS_MM_Uplink (buffer, data, len*8) < 0) {
			return ED_FALSE;
		}
		else {
			return ED_TRUE;
		}
	}
#endif

/* Set encoder */
int SetEncode_EPS_MM_Uplink (char* buffer, ED_EXLONG bitOffset, TEPS_MM_Uplink_Data* data)
{
	int retLen = ED_UNKNOWN_MESSAGE;
	ED_WARNING_REMOVER(bitOffset);
	
	switch (data->Type) {
		case ID_EPS_MM_Uplink_ATTACH_COMPLETE: {
			retLen = ENCODE_c_ATTACH_COMPLETE (buffer, 0, data->Data.fld_c_ATTACH_COMPLETE);
			break;
		}
		case ID_EPS_MM_Uplink_ATTACH_REQUEST: {
			retLen = ENCODE_c_ATTACH_REQUEST (buffer, 0, data->Data.fld_c_ATTACH_REQUEST);
			break;
		}
		case ID_EPS_MM_Uplink_AUTHENTICATION_FAILURE: {
			retLen = ENCODE_c_AUTHENTICATION_FAILURE (buffer, 0, data->Data.fld_c_AUTHENTICATION_FAILURE);
			break;
		}
		case ID_EPS_MM_Uplink_AUTHENTICATION_RESPONSE: {
			retLen = ENCODE_c_AUTHENTICATION_RESPONSE (buffer, 0, data->Data.fld_c_AUTHENTICATION_RESPONSE);
			break;
		}
		case ID_EPS_MM_Uplink_EPS_DETACH_ACCEPT_UP: {
			retLen = ENCODE_c_EPS_DETACH_ACCEPT_UP (buffer, 0, data->Data.fld_c_EPS_DETACH_ACCEPT_UP);
			break;
		}
		case ID_EPS_MM_Uplink_EPS_DETACH_REQUEST_UP: {
			retLen = ENCODE_c_EPS_DETACH_REQUEST_UP (buffer, 0, data->Data.fld_c_EPS_DETACH_REQUEST_UP);
			break;
		}
		case ID_EPS_MM_Uplink_EMM_STATUS: {
			retLen = ENCODE_c_EMM_STATUS (buffer, 0, data->Data.fld_c_EMM_STATUS);
			break;
		}
		case ID_EPS_MM_Uplink_EXTENDED_SERVICE_REQUEST: {
			retLen = ENCODE_c_EXTENDED_SERVICE_REQUEST (buffer, 0, data->Data.fld_c_EXTENDED_SERVICE_REQUEST);
			break;
		}
		case ID_EPS_MM_Uplink_GUTI_REALLOCATION_COMPLETE: {
			retLen = ENCODE_c_GUTI_REALLOCATION_COMPLETE (buffer, 0, data->Data.fld_c_GUTI_REALLOCATION_COMPLETE);
			break;
		}
		case ID_EPS_MM_Uplink_IDENTITY_RESPONSE: {
			retLen = ENCODE_c_IDENTITY_RESPONSE (buffer, 0, data->Data.fld_c_IDENTITY_RESPONSE);
			break;
		}
		case ID_EPS_MM_Uplink_SECURITY_MODE_COMPLETE: {
			retLen = ENCODE_c_SECURITY_MODE_COMPLETE (buffer, 0, data->Data.fld_c_SECURITY_MODE_COMPLETE);
			break;
		}
		case ID_EPS_MM_Uplink_SECURITY_MODE_REJECT: {
			retLen = ENCODE_c_SECURITY_MODE_REJECT (buffer, 0, data->Data.fld_c_SECURITY_MODE_REJECT);
			break;
		}
		case ID_EPS_MM_Uplink_SECURITY_PROTECTED_NAS_MESSAGE: {
			retLen = ENCODE_c_SECURITY_PROTECTED_NAS_MESSAGE (buffer, 0, data->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE);
			break;
		}
		case ID_EPS_MM_Uplink_SERVICE_REQUEST: {
			retLen = ENCODE_c_SERVICE_REQUEST (buffer, 0, data->Data.fld_c_SERVICE_REQUEST);
			break;
		}
		case ID_EPS_MM_Uplink_TRACKING_AREA_UPDATE_COMPLETE: {
			retLen = ENCODE_c_TRACKING_AREA_UPDATE_COMPLETE (buffer, 0, data->Data.fld_c_TRACKING_AREA_UPDATE_COMPLETE);
			break;
		}
		case ID_EPS_MM_Uplink_TRACKING_AREA_UPDATE_REQUEST: {
			retLen = ENCODE_c_TRACKING_AREA_UPDATE_REQUEST (buffer, 0, data->Data.fld_c_TRACKING_AREA_UPDATE_REQUEST);
			break;
		}
		case ID_EPS_MM_Uplink_UPLINK_NAS_TRANSPORT: {
			retLen = ENCODE_c_UPLINK_NAS_TRANSPORT (buffer, 0, data->Data.fld_c_UPLINK_NAS_TRANSPORT);
			break;
		}
		case ID_EPS_MM_Uplink_UPLINK_GENERIC_NAS_TRANSPORT: {
			retLen = ENCODE_c_UPLINK_GENERIC_NAS_TRANSPORT (buffer, 0, data->Data.fld_c_UPLINK_GENERIC_NAS_TRANSPORT);
			break;
		}
		case ID_EPS_MM_Uplink_CONTROL_PLANE_SERVICE_REQUEST: {
			retLen = ENCODE_c_CONTROL_PLANE_SERVICE_REQUEST (buffer, 0, data->Data.fld_c_CONTROL_PLANE_SERVICE_REQUEST);
			break;
		}

		default:;
	}
	return retLen;
}
#ifdef ED_REVERSED_INTEGER
#error ED_REVERSED_INTEGER is defined!
#endif


int SetDecode_EPS_MM_Downlink (const char* buffer, TEPS_MM_Downlink_Data* data, int bitLen)
{
	int retLen = 0;
	
	/*-----------------------------------------------------------------
		Key is set to a single value containing protocol discriminator,
		skip indicator and message type.
		For example, message ASSIGNMENT_COMMAND has:
			skip indicator         = 0000 (0x0)
			protocol discriminator = 0110 (0x6)
			message type           = 00101110 (0x2E)
		In this case, key will be set to 0x602E.
		Skip indicator could be in some cases a transaction identifier.
		In such cases, it will be set to 0 for matching purposes.
	------------------------------------------------------------------*/
	unsigned /****/ int key /*1*/ = ((((unsigned char)buffer [0]) << 8) | ((unsigned char)buffer [1]))/*2*/;/*3*/
		data->ProtocolDiscriminator = (int)(((unsigned char)buffer [0]) & 0x0f);
	data->MessageType = (int)((unsigned char)buffer [1]);
	
	ED_WARNING_REMOVER(key);
	/* Specific behaviour for TS24.301: recognize messages without Message Type */
	switch (((unsigned char)buffer [0]) >> 4) {
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
	
			/* Set the message type to 0 */
			key &= 0xFF00;
			break;
	}
	switch (key) {
			/* Detect signal ATTACH_ACCEPT */
		case 0x0742: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_ATTACH_ACCEPT), != ED_NO_ERRORS)
			INIT_c_ATTACH_ACCEPT (data->Data.fld_c_ATTACH_ACCEPT);
			retLen = DECODE_c_ATTACH_ACCEPT (buffer, 0, data->Data.fld_c_ATTACH_ACCEPT, bitLen);
		
			return retLen;
		}
		/* Detect signal ATTACH_REJECT */
		case 0x0744: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_ATTACH_REJECT), != ED_NO_ERRORS)
			INIT_c_ATTACH_REJECT (data->Data.fld_c_ATTACH_REJECT);
			retLen = DECODE_c_ATTACH_REJECT (buffer, 0, data->Data.fld_c_ATTACH_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal AUTHENTICATION_REJECT */
		case 0x0754: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_AUTHENTICATION_REJECT), != ED_NO_ERRORS)
			INIT_c_AUTHENTICATION_REJECT (data->Data.fld_c_AUTHENTICATION_REJECT);
			retLen = DECODE_c_AUTHENTICATION_REJECT (buffer, 0, data->Data.fld_c_AUTHENTICATION_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal AUTHENTICATION_REQUEST */
		case 0x0752: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_AUTHENTICATION_REQUEST), != ED_NO_ERRORS)
			INIT_c_AUTHENTICATION_REQUEST (data->Data.fld_c_AUTHENTICATION_REQUEST);
			retLen = DECODE_c_AUTHENTICATION_REQUEST (buffer, 0, data->Data.fld_c_AUTHENTICATION_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal CS_SERVICE_NOTIFICATION */
		case 0x0764: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_CS_SERVICE_NOTIFICATION), != ED_NO_ERRORS)
			INIT_c_CS_SERVICE_NOTIFICATION (data->Data.fld_c_CS_SERVICE_NOTIFICATION);
			retLen = DECODE_c_CS_SERVICE_NOTIFICATION (buffer, 0, data->Data.fld_c_CS_SERVICE_NOTIFICATION, bitLen);
		
			return retLen;
		}
		/* Detect signal EPS_DETACH_ACCEPT_DN */
		case 0x0746: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_EPS_DETACH_ACCEPT_DN), != ED_NO_ERRORS)
			INIT_c_EPS_DETACH_ACCEPT_DN (data->Data.fld_c_EPS_DETACH_ACCEPT_DN);
			retLen = DECODE_c_EPS_DETACH_ACCEPT_DN (buffer, 0, data->Data.fld_c_EPS_DETACH_ACCEPT_DN, bitLen);
		
			return retLen;
		}
		/* Detect signal EPS_DETACH_REQUEST_DN */
		case 0x0745: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_EPS_DETACH_REQUEST_DN), != ED_NO_ERRORS)
			INIT_c_EPS_DETACH_REQUEST_DN (data->Data.fld_c_EPS_DETACH_REQUEST_DN);
			retLen = DECODE_c_EPS_DETACH_REQUEST_DN (buffer, 0, data->Data.fld_c_EPS_DETACH_REQUEST_DN, bitLen);
		
			return retLen;
		}
		/* Detect signal DOWNLINK_NAS_TRANSPORT */
		case 0x0762: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_DOWNLINK_NAS_TRANSPORT), != ED_NO_ERRORS)
			INIT_c_DOWNLINK_NAS_TRANSPORT (data->Data.fld_c_DOWNLINK_NAS_TRANSPORT);
			retLen = DECODE_c_DOWNLINK_NAS_TRANSPORT (buffer, 0, data->Data.fld_c_DOWNLINK_NAS_TRANSPORT, bitLen);
		
			return retLen;
		}
		/* Detect signal EMM_INFORMATION */
		case 0x0761: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_EMM_INFORMATION), != ED_NO_ERRORS)
			INIT_c_EMM_INFORMATION (data->Data.fld_c_EMM_INFORMATION);
			retLen = DECODE_c_EMM_INFORMATION (buffer, 0, data->Data.fld_c_EMM_INFORMATION, bitLen);
		
			return retLen;
		}
		/* Detect signal EMM_STATUS */
		case 0x0760: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_EMM_STATUS), != ED_NO_ERRORS)
			INIT_c_EMM_STATUS (data->Data.fld_c_EMM_STATUS);
			retLen = DECODE_c_EMM_STATUS (buffer, 0, data->Data.fld_c_EMM_STATUS, bitLen);
		
			return retLen;
		}
		/* Detect signal GUTI_REALLOCATION_COMMAND */
		case 0x0750: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_GUTI_REALLOCATION_COMMAND), != ED_NO_ERRORS)
			INIT_c_GUTI_REALLOCATION_COMMAND (data->Data.fld_c_GUTI_REALLOCATION_COMMAND);
			retLen = DECODE_c_GUTI_REALLOCATION_COMMAND (buffer, 0, data->Data.fld_c_GUTI_REALLOCATION_COMMAND, bitLen);
		
			return retLen;
		}
		/* Detect signal IDENTITY_REQUEST */
		case 0x0755: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_IDENTITY_REQUEST), != ED_NO_ERRORS)
			INIT_c_IDENTITY_REQUEST (data->Data.fld_c_IDENTITY_REQUEST);
			retLen = DECODE_c_IDENTITY_REQUEST (buffer, 0, data->Data.fld_c_IDENTITY_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal SECURITY_MODE_COMMAND */
		case 0x075D:
		case 0x375D: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_SECURITY_MODE_COMMAND), != ED_NO_ERRORS)
			INIT_c_SECURITY_MODE_COMMAND (data->Data.fld_c_SECURITY_MODE_COMMAND);
			retLen = DECODE_c_SECURITY_MODE_COMMAND (buffer, 0, data->Data.fld_c_SECURITY_MODE_COMMAND, bitLen);
		
			return retLen;
		}
		/* Detect signal SECURITY_PROTECTED_NAS_MESSAGE */
		case 0x1700:
		case 0x2700:
		case 0x3700:
		case 0x4700:
		case 0x5700: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_SECURITY_PROTECTED_NAS_MESSAGE), != ED_NO_ERRORS)
			INIT_c_SECURITY_PROTECTED_NAS_MESSAGE (data->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE);
			retLen = DECODE_c_SECURITY_PROTECTED_NAS_MESSAGE (buffer, 0, data->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE, bitLen);
		
			return retLen;
		}
		/* Detect signal SERVICE_REJECT */
		case 0x074E: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_SERVICE_REJECT), != ED_NO_ERRORS)
			INIT_c_SERVICE_REJECT (data->Data.fld_c_SERVICE_REJECT);
			retLen = DECODE_c_SERVICE_REJECT (buffer, 0, data->Data.fld_c_SERVICE_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal TRACKING_AREA_UPDATE_ACCEPT */
		case 0x0749: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_TRACKING_AREA_UPDATE_ACCEPT), != ED_NO_ERRORS)
			INIT_c_TRACKING_AREA_UPDATE_ACCEPT (data->Data.fld_c_TRACKING_AREA_UPDATE_ACCEPT);
			retLen = DECODE_c_TRACKING_AREA_UPDATE_ACCEPT (buffer, 0, data->Data.fld_c_TRACKING_AREA_UPDATE_ACCEPT, bitLen);
		
			return retLen;
		}
		/* Detect signal TRACKING_AREA_UPDATE_REJECT */
		case 0x074B: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_TRACKING_AREA_UPDATE_REJECT), != ED_NO_ERRORS)
			INIT_c_TRACKING_AREA_UPDATE_REJECT (data->Data.fld_c_TRACKING_AREA_UPDATE_REJECT);
			retLen = DECODE_c_TRACKING_AREA_UPDATE_REJECT (buffer, 0, data->Data.fld_c_TRACKING_AREA_UPDATE_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal DOWNLINK_GENERIC_NAS_TRANSPORT */
		case 0x0768: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_DOWNLINK_GENERIC_NAS_TRANSPORT), != ED_NO_ERRORS)
			INIT_c_DOWNLINK_GENERIC_NAS_TRANSPORT (data->Data.fld_c_DOWNLINK_GENERIC_NAS_TRANSPORT);
			retLen = DECODE_c_DOWNLINK_GENERIC_NAS_TRANSPORT (buffer, 0, data->Data.fld_c_DOWNLINK_GENERIC_NAS_TRANSPORT, bitLen);
		
			return retLen;
		}
		/* Detect signal SERVICE_ACCEPT */
		case 0x074F: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_MM_Downlink_Data (data, ID_EPS_MM_Downlink_SERVICE_ACCEPT), != ED_NO_ERRORS)
			INIT_c_SERVICE_ACCEPT (data->Data.fld_c_SERVICE_ACCEPT);
			retLen = DECODE_c_SERVICE_ACCEPT (buffer, 0, data->Data.fld_c_SERVICE_ACCEPT, bitLen);
		
			return retLen;
		}

		default:;
	}
	data->Type = ID_EPS_MM_Downlink_Unrecognized;

	return ED_UNKNOWN_MESSAGE;
}
			
#ifndef ED_EXCLUDE_1_0_33_COMPATIBILITY
	int Decode_EPS_MM_Downlink (const char* buffer, int len, TEPS_MM_Downlink_Data* data)
	{
		if (SetDecode_EPS_MM_Downlink (buffer, data, len*8) < 0) {
			return ED_FALSE;
		}
		else {
			return ED_TRUE;
		}
	}
#endif

/* Set encoder */
int SetEncode_EPS_MM_Downlink (char* buffer, ED_EXLONG bitOffset, TEPS_MM_Downlink_Data* data)
{
	int retLen = ED_UNKNOWN_MESSAGE;
	ED_WARNING_REMOVER(bitOffset);
	
	switch (data->Type) {
		case ID_EPS_MM_Downlink_ATTACH_ACCEPT: {
			retLen = ENCODE_c_ATTACH_ACCEPT (buffer, 0, data->Data.fld_c_ATTACH_ACCEPT);
			break;
		}
		case ID_EPS_MM_Downlink_ATTACH_REJECT: {
			retLen = ENCODE_c_ATTACH_REJECT (buffer, 0, data->Data.fld_c_ATTACH_REJECT);
			break;
		}
		case ID_EPS_MM_Downlink_AUTHENTICATION_REJECT: {
			retLen = ENCODE_c_AUTHENTICATION_REJECT (buffer, 0, data->Data.fld_c_AUTHENTICATION_REJECT);
			break;
		}
		case ID_EPS_MM_Downlink_AUTHENTICATION_REQUEST: {
			retLen = ENCODE_c_AUTHENTICATION_REQUEST (buffer, 0, data->Data.fld_c_AUTHENTICATION_REQUEST);
			break;
		}
		case ID_EPS_MM_Downlink_CS_SERVICE_NOTIFICATION: {
			retLen = ENCODE_c_CS_SERVICE_NOTIFICATION (buffer, 0, data->Data.fld_c_CS_SERVICE_NOTIFICATION);
			break;
		}
		case ID_EPS_MM_Downlink_EPS_DETACH_ACCEPT_DN: {
			retLen = ENCODE_c_EPS_DETACH_ACCEPT_DN (buffer, 0, data->Data.fld_c_EPS_DETACH_ACCEPT_DN);
			break;
		}
		case ID_EPS_MM_Downlink_EPS_DETACH_REQUEST_DN: {
			retLen = ENCODE_c_EPS_DETACH_REQUEST_DN (buffer, 0, data->Data.fld_c_EPS_DETACH_REQUEST_DN);
			break;
		}
		case ID_EPS_MM_Downlink_DOWNLINK_NAS_TRANSPORT: {
			retLen = ENCODE_c_DOWNLINK_NAS_TRANSPORT (buffer, 0, data->Data.fld_c_DOWNLINK_NAS_TRANSPORT);
			break;
		}
		case ID_EPS_MM_Downlink_EMM_INFORMATION: {
			retLen = ENCODE_c_EMM_INFORMATION (buffer, 0, data->Data.fld_c_EMM_INFORMATION);
			break;
		}
		case ID_EPS_MM_Downlink_EMM_STATUS: {
			retLen = ENCODE_c_EMM_STATUS (buffer, 0, data->Data.fld_c_EMM_STATUS);
			break;
		}
		case ID_EPS_MM_Downlink_GUTI_REALLOCATION_COMMAND: {
			retLen = ENCODE_c_GUTI_REALLOCATION_COMMAND (buffer, 0, data->Data.fld_c_GUTI_REALLOCATION_COMMAND);
			break;
		}
		case ID_EPS_MM_Downlink_IDENTITY_REQUEST: {
			retLen = ENCODE_c_IDENTITY_REQUEST (buffer, 0, data->Data.fld_c_IDENTITY_REQUEST);
			break;
		}
		case ID_EPS_MM_Downlink_SECURITY_MODE_COMMAND: {
			retLen = ENCODE_c_SECURITY_MODE_COMMAND (buffer, 0, data->Data.fld_c_SECURITY_MODE_COMMAND);
			break;
		}
		case ID_EPS_MM_Downlink_SECURITY_PROTECTED_NAS_MESSAGE: {
			retLen = ENCODE_c_SECURITY_PROTECTED_NAS_MESSAGE (buffer, 0, data->Data.fld_c_SECURITY_PROTECTED_NAS_MESSAGE);
			break;
		}
		case ID_EPS_MM_Downlink_SERVICE_REJECT: {
			retLen = ENCODE_c_SERVICE_REJECT (buffer, 0, data->Data.fld_c_SERVICE_REJECT);
			break;
		}
		case ID_EPS_MM_Downlink_TRACKING_AREA_UPDATE_ACCEPT: {
			retLen = ENCODE_c_TRACKING_AREA_UPDATE_ACCEPT (buffer, 0, data->Data.fld_c_TRACKING_AREA_UPDATE_ACCEPT);
			break;
		}
		case ID_EPS_MM_Downlink_TRACKING_AREA_UPDATE_REJECT: {
			retLen = ENCODE_c_TRACKING_AREA_UPDATE_REJECT (buffer, 0, data->Data.fld_c_TRACKING_AREA_UPDATE_REJECT);
			break;
		}
		case ID_EPS_MM_Downlink_DOWNLINK_GENERIC_NAS_TRANSPORT: {
			retLen = ENCODE_c_DOWNLINK_GENERIC_NAS_TRANSPORT (buffer, 0, data->Data.fld_c_DOWNLINK_GENERIC_NAS_TRANSPORT);
			break;
		}
		case ID_EPS_MM_Downlink_SERVICE_ACCEPT: {
			retLen = ENCODE_c_SERVICE_ACCEPT (buffer, 0, data->Data.fld_c_SERVICE_ACCEPT);
			break;
		}

		default:;
	}
	return retLen;
}
#ifdef ED_REVERSED_INTEGER
#error ED_REVERSED_INTEGER is defined!
#endif


int SetDecode_EPS_SM_Uplink (const char* buffer, TEPS_SM_Uplink_Data* data, int bitLen)
{
	int retLen = 0;
	
	/*-----------------------------------------------------------------
		Key is set to a single value containing protocol discriminator,
		skip indicator and message type.
		For example, message ASSIGNMENT_COMMAND has:
			skip indicator         = 0000 (0x0)
			protocol discriminator = 0110 (0x6)
			message type           = 00101110 (0x2E)
		In this case, key will be set to 0x602E.
		Skip indicator could be in some cases a transaction identifier.
		In such cases, it will be set to 0 for matching purposes.
	------------------------------------------------------------------*/
	unsigned /****/ int key /*1*/ = ((((unsigned char)buffer [0]) << 8) | ((unsigned char)buffer [2]))& 0x0FFF/*2*/;/*3*/
		data->ProtocolDiscriminator = (int)(((unsigned char)buffer [0]) & 0x0f);
	data->MessageType = (int)((unsigned char)buffer [1]);
	
	ED_WARNING_REMOVER(key);
	switch (key) {
			/* Detect signal ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT */
		case 0x02C6: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT), != ED_NO_ERRORS)
			INIT_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT (data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT);
			retLen = DECODE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT (buffer, 0, data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT, bitLen);
		
			return retLen;
		}
		/* Detect signal ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT */
		case 0x02C7: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT), != ED_NO_ERRORS)
			INIT_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT (data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT);
			retLen = DECODE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT (buffer, 0, data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT */
		case 0x02C2: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT), != ED_NO_ERRORS)
			INIT_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT (data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT);
			retLen = DECODE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT (buffer, 0, data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT, bitLen);
		
			return retLen;
		}
		/* Detect signal ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT */
		case 0x02C3: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT), != ED_NO_ERRORS)
			INIT_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT (data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT);
			retLen = DECODE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT (buffer, 0, data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal BEARER_RESOURCE_ALLOCATION_REQUEST */
		case 0x02D4: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_BEARER_RESOURCE_ALLOCATION_REQUEST), != ED_NO_ERRORS)
			INIT_c_BEARER_RESOURCE_ALLOCATION_REQUEST (data->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REQUEST);
			retLen = DECODE_c_BEARER_RESOURCE_ALLOCATION_REQUEST (buffer, 0, data->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal BEARER_RESOURCE_MODIFICATION_REQUEST */
		case 0x02D6: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_BEARER_RESOURCE_MODIFICATION_REQUEST), != ED_NO_ERRORS)
			INIT_c_BEARER_RESOURCE_MODIFICATION_REQUEST (data->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REQUEST);
			retLen = DECODE_c_BEARER_RESOURCE_MODIFICATION_REQUEST (buffer, 0, data->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT */
		case 0x02CE: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT), != ED_NO_ERRORS)
			INIT_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT (data->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT);
			retLen = DECODE_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT (buffer, 0, data->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT, bitLen);
		
			return retLen;
		}
		/* Detect signal ESM_DUMMY_MESSAGE */
		case 0x02DC: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_ESM_DUMMY_MESSAGE), != ED_NO_ERRORS)
			INIT_c_ESM_DUMMY_MESSAGE (data->Data.fld_c_ESM_DUMMY_MESSAGE);
			retLen = DECODE_c_ESM_DUMMY_MESSAGE (buffer, 0, data->Data.fld_c_ESM_DUMMY_MESSAGE, bitLen);
		
			return retLen;
		}
		/* Detect signal ESM_INFORMATION_RESPONSE */
		case 0x02DA: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_ESM_INFORMATION_RESPONSE), != ED_NO_ERRORS)
			INIT_c_ESM_INFORMATION_RESPONSE (data->Data.fld_c_ESM_INFORMATION_RESPONSE);
			retLen = DECODE_c_ESM_INFORMATION_RESPONSE (buffer, 0, data->Data.fld_c_ESM_INFORMATION_RESPONSE, bitLen);
		
			return retLen;
		}
		/* Detect signal ESM_STATUS */
		case 0x02E8: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_ESM_STATUS), != ED_NO_ERRORS)
			INIT_c_ESM_STATUS (data->Data.fld_c_ESM_STATUS);
			retLen = DECODE_c_ESM_STATUS (buffer, 0, data->Data.fld_c_ESM_STATUS, bitLen);
		
			return retLen;
		}
		/* Detect signal MODIFY_EPS_BEARER_CONTEXT_ACCEPT */
		case 0x02CA: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_MODIFY_EPS_BEARER_CONTEXT_ACCEPT), != ED_NO_ERRORS)
			INIT_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT (data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT);
			retLen = DECODE_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT (buffer, 0, data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT, bitLen);
		
			return retLen;
		}
		/* Detect signal MODIFY_EPS_BEARER_CONTEXT_REJECT */
		case 0x02CB: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_MODIFY_EPS_BEARER_CONTEXT_REJECT), != ED_NO_ERRORS)
			INIT_c_MODIFY_EPS_BEARER_CONTEXT_REJECT (data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REJECT);
			retLen = DECODE_c_MODIFY_EPS_BEARER_CONTEXT_REJECT (buffer, 0, data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal PDN_CONNECTIVITY_REQUEST */
		case 0x02D0: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_PDN_CONNECTIVITY_REQUEST), != ED_NO_ERRORS)
			INIT_c_PDN_CONNECTIVITY_REQUEST (data->Data.fld_c_PDN_CONNECTIVITY_REQUEST);
			retLen = DECODE_c_PDN_CONNECTIVITY_REQUEST (buffer, 0, data->Data.fld_c_PDN_CONNECTIVITY_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal PDN_DISCONNECT_REQUEST */
		case 0x02D2: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_PDN_DISCONNECT_REQUEST), != ED_NO_ERRORS)
			INIT_c_PDN_DISCONNECT_REQUEST (data->Data.fld_c_PDN_DISCONNECT_REQUEST);
			retLen = DECODE_c_PDN_DISCONNECT_REQUEST (buffer, 0, data->Data.fld_c_PDN_DISCONNECT_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal REMOTE_UE_REPORT */
		case 0x02E9: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_REMOTE_UE_REPORT), != ED_NO_ERRORS)
			INIT_c_REMOTE_UE_REPORT (data->Data.fld_c_REMOTE_UE_REPORT);
			retLen = DECODE_c_REMOTE_UE_REPORT (buffer, 0, data->Data.fld_c_REMOTE_UE_REPORT, bitLen);
		
			return retLen;
		}
		/* Detect signal ESM_DATA_TRANSPORT */
		case 0x02EB: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Uplink_Data (data, ID_EPS_SM_Uplink_ESM_DATA_TRANSPORT), != ED_NO_ERRORS)
			INIT_c_ESM_DATA_TRANSPORT (data->Data.fld_c_ESM_DATA_TRANSPORT);
			retLen = DECODE_c_ESM_DATA_TRANSPORT (buffer, 0, data->Data.fld_c_ESM_DATA_TRANSPORT, bitLen);
		
			return retLen;
		}

		default:;
	}
	data->Type = ID_EPS_SM_Uplink_Unrecognized;

	return ED_UNKNOWN_MESSAGE;
}
			
#ifndef ED_EXCLUDE_1_0_33_COMPATIBILITY
	int Decode_EPS_SM_Uplink (const char* buffer, int len, TEPS_SM_Uplink_Data* data)
	{
		if (SetDecode_EPS_SM_Uplink (buffer, data, len*8) < 0) {
			return ED_FALSE;
		}
		else {
			return ED_TRUE;
		}
	}
#endif

/* Set encoder */
int SetEncode_EPS_SM_Uplink (char* buffer, ED_EXLONG bitOffset, TEPS_SM_Uplink_Data* data)
{
	int retLen = ED_UNKNOWN_MESSAGE;
	ED_WARNING_REMOVER(bitOffset);
	
	switch (data->Type) {
		case ID_EPS_SM_Uplink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT: {
			retLen = ENCODE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT (buffer, 0, data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_ACCEPT);
			break;
		}
		case ID_EPS_SM_Uplink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT: {
			retLen = ENCODE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT (buffer, 0, data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REJECT);
			break;
		}
		case ID_EPS_SM_Uplink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT: {
			retLen = ENCODE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT (buffer, 0, data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_ACCEPT);
			break;
		}
		case ID_EPS_SM_Uplink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT: {
			retLen = ENCODE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT (buffer, 0, data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REJECT);
			break;
		}
		case ID_EPS_SM_Uplink_BEARER_RESOURCE_ALLOCATION_REQUEST: {
			retLen = ENCODE_c_BEARER_RESOURCE_ALLOCATION_REQUEST (buffer, 0, data->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REQUEST);
			break;
		}
		case ID_EPS_SM_Uplink_BEARER_RESOURCE_MODIFICATION_REQUEST: {
			retLen = ENCODE_c_BEARER_RESOURCE_MODIFICATION_REQUEST (buffer, 0, data->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REQUEST);
			break;
		}
		case ID_EPS_SM_Uplink_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT: {
			retLen = ENCODE_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT (buffer, 0, data->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_ACCEPT);
			break;
		}
		case ID_EPS_SM_Uplink_ESM_DUMMY_MESSAGE: {
			retLen = ENCODE_c_ESM_DUMMY_MESSAGE (buffer, 0, data->Data.fld_c_ESM_DUMMY_MESSAGE);
			break;
		}
		case ID_EPS_SM_Uplink_ESM_INFORMATION_RESPONSE: {
			retLen = ENCODE_c_ESM_INFORMATION_RESPONSE (buffer, 0, data->Data.fld_c_ESM_INFORMATION_RESPONSE);
			break;
		}
		case ID_EPS_SM_Uplink_ESM_STATUS: {
			retLen = ENCODE_c_ESM_STATUS (buffer, 0, data->Data.fld_c_ESM_STATUS);
			break;
		}
		case ID_EPS_SM_Uplink_MODIFY_EPS_BEARER_CONTEXT_ACCEPT: {
			retLen = ENCODE_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT (buffer, 0, data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_ACCEPT);
			break;
		}
		case ID_EPS_SM_Uplink_MODIFY_EPS_BEARER_CONTEXT_REJECT: {
			retLen = ENCODE_c_MODIFY_EPS_BEARER_CONTEXT_REJECT (buffer, 0, data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REJECT);
			break;
		}
		case ID_EPS_SM_Uplink_PDN_CONNECTIVITY_REQUEST: {
			retLen = ENCODE_c_PDN_CONNECTIVITY_REQUEST (buffer, 0, data->Data.fld_c_PDN_CONNECTIVITY_REQUEST);
			break;
		}
		case ID_EPS_SM_Uplink_PDN_DISCONNECT_REQUEST: {
			retLen = ENCODE_c_PDN_DISCONNECT_REQUEST (buffer, 0, data->Data.fld_c_PDN_DISCONNECT_REQUEST);
			break;
		}
		case ID_EPS_SM_Uplink_REMOTE_UE_REPORT: {
			retLen = ENCODE_c_REMOTE_UE_REPORT (buffer, 0, data->Data.fld_c_REMOTE_UE_REPORT);
			break;
		}
		case ID_EPS_SM_Uplink_ESM_DATA_TRANSPORT: {
			retLen = ENCODE_c_ESM_DATA_TRANSPORT (buffer, 0, data->Data.fld_c_ESM_DATA_TRANSPORT);
			break;
		}

		default:;
	}
	return retLen;
}
#ifdef ED_REVERSED_INTEGER
#error ED_REVERSED_INTEGER is defined!
#endif


int SetDecode_EPS_SM_Downlink (const char* buffer, TEPS_SM_Downlink_Data* data, int bitLen)
{
	int retLen = 0;
	
	/*-----------------------------------------------------------------
		Key is set to a single value containing protocol discriminator,
		skip indicator and message type.
		For example, message ASSIGNMENT_COMMAND has:
			skip indicator         = 0000 (0x0)
			protocol discriminator = 0110 (0x6)
			message type           = 00101110 (0x2E)
		In this case, key will be set to 0x602E.
		Skip indicator could be in some cases a transaction identifier.
		In such cases, it will be set to 0 for matching purposes.
	------------------------------------------------------------------*/
	unsigned /****/ int key /*1*/ = ((((unsigned char)buffer [0]) << 8) | ((unsigned char)buffer [2]))& 0x0FFF/*2*/;/*3*/
		data->ProtocolDiscriminator = (int)(((unsigned char)buffer [0]) & 0x0f);
	data->MessageType = (int)((unsigned char)buffer [1]);
	
	ED_WARNING_REMOVER(key);
	switch (key) {
			/* Detect signal ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST */
		case 0x02C5: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST), != ED_NO_ERRORS)
			INIT_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST (data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST);
			retLen = DECODE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST (buffer, 0, data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST */
		case 0x02C1: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST), != ED_NO_ERRORS)
			INIT_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST (data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST);
			retLen = DECODE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST (buffer, 0, data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal BEARER_RESOURCE_ALLOCATION_REJECT */
		case 0x02D5: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_BEARER_RESOURCE_ALLOCATION_REJECT), != ED_NO_ERRORS)
			INIT_c_BEARER_RESOURCE_ALLOCATION_REJECT (data->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REJECT);
			retLen = DECODE_c_BEARER_RESOURCE_ALLOCATION_REJECT (buffer, 0, data->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal BEARER_RESOURCE_MODIFICATION_REJECT */
		case 0x02D7: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_BEARER_RESOURCE_MODIFICATION_REJECT), != ED_NO_ERRORS)
			INIT_c_BEARER_RESOURCE_MODIFICATION_REJECT (data->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REJECT);
			retLen = DECODE_c_BEARER_RESOURCE_MODIFICATION_REJECT (buffer, 0, data->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST */
		case 0x02CD: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST), != ED_NO_ERRORS)
			INIT_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST (data->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST);
			retLen = DECODE_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST (buffer, 0, data->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal ESM_DUMMY_MESSAGE */
		case 0x02DC: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_ESM_DUMMY_MESSAGE), != ED_NO_ERRORS)
			INIT_c_ESM_DUMMY_MESSAGE (data->Data.fld_c_ESM_DUMMY_MESSAGE);
			retLen = DECODE_c_ESM_DUMMY_MESSAGE (buffer, 0, data->Data.fld_c_ESM_DUMMY_MESSAGE, bitLen);
		
			return retLen;
		}
		/* Detect signal ESM_INFORMATION_REQUEST */
		case 0x02D9: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_ESM_INFORMATION_REQUEST), != ED_NO_ERRORS)
			INIT_c_ESM_INFORMATION_REQUEST (data->Data.fld_c_ESM_INFORMATION_REQUEST);
			retLen = DECODE_c_ESM_INFORMATION_REQUEST (buffer, 0, data->Data.fld_c_ESM_INFORMATION_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal ESM_STATUS */
		case 0x02E8: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_ESM_STATUS), != ED_NO_ERRORS)
			INIT_c_ESM_STATUS (data->Data.fld_c_ESM_STATUS);
			retLen = DECODE_c_ESM_STATUS (buffer, 0, data->Data.fld_c_ESM_STATUS, bitLen);
		
			return retLen;
		}
		/* Detect signal MODIFY_EPS_BEARER_CONTEXT_REQUEST */
		case 0x02C9: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_MODIFY_EPS_BEARER_CONTEXT_REQUEST), != ED_NO_ERRORS)
			INIT_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST (data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST);
			retLen = DECODE_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST (buffer, 0, data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST, bitLen);
		
			return retLen;
		}
		/* Detect signal EPS_NOTIFICATION */
		case 0x02DB: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_EPS_NOTIFICATION), != ED_NO_ERRORS)
			INIT_c_EPS_NOTIFICATION (data->Data.fld_c_EPS_NOTIFICATION);
			retLen = DECODE_c_EPS_NOTIFICATION (buffer, 0, data->Data.fld_c_EPS_NOTIFICATION, bitLen);
		
			return retLen;
		}
		/* Detect signal PDN_CONNECTIVITY_REJECT */
		case 0x02D1: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_PDN_CONNECTIVITY_REJECT), != ED_NO_ERRORS)
			INIT_c_PDN_CONNECTIVITY_REJECT (data->Data.fld_c_PDN_CONNECTIVITY_REJECT);
			retLen = DECODE_c_PDN_CONNECTIVITY_REJECT (buffer, 0, data->Data.fld_c_PDN_CONNECTIVITY_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal PDN_DISCONNECT_REJECT */
		case 0x02D3: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_PDN_DISCONNECT_REJECT), != ED_NO_ERRORS)
			INIT_c_PDN_DISCONNECT_REJECT (data->Data.fld_c_PDN_DISCONNECT_REJECT);
			retLen = DECODE_c_PDN_DISCONNECT_REJECT (buffer, 0, data->Data.fld_c_PDN_DISCONNECT_REJECT, bitLen);
		
			return retLen;
		}
		/* Detect signal REMOTE_UE_REPORT_RESPONSE */
		case 0x02EA: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_REMOTE_UE_REPORT_RESPONSE), != ED_NO_ERRORS)
			INIT_c_REMOTE_UE_REPORT_RESPONSE (data->Data.fld_c_REMOTE_UE_REPORT_RESPONSE);
			retLen = DECODE_c_REMOTE_UE_REPORT_RESPONSE (buffer, 0, data->Data.fld_c_REMOTE_UE_REPORT_RESPONSE, bitLen);
		
			return retLen;
		}
		/* Detect signal ESM_DATA_TRANSPORT */
		case 0x02EB: {
			ED_CHECK_OUT_OF_MEMORY_KEEP/*COOMK08*/(/*SETP5*/SETPRESENT_TEPS_SM_Downlink_Data (data, ID_EPS_SM_Downlink_ESM_DATA_TRANSPORT), != ED_NO_ERRORS)
			INIT_c_ESM_DATA_TRANSPORT (data->Data.fld_c_ESM_DATA_TRANSPORT);
			retLen = DECODE_c_ESM_DATA_TRANSPORT (buffer, 0, data->Data.fld_c_ESM_DATA_TRANSPORT, bitLen);
		
			return retLen;
		}

		default:;
	}
	data->Type = ID_EPS_SM_Downlink_Unrecognized;

	return ED_UNKNOWN_MESSAGE;
}
			
#ifndef ED_EXCLUDE_1_0_33_COMPATIBILITY
	int Decode_EPS_SM_Downlink (const char* buffer, int len, TEPS_SM_Downlink_Data* data)
	{
		if (SetDecode_EPS_SM_Downlink (buffer, data, len*8) < 0) {
			return ED_FALSE;
		}
		else {
			return ED_TRUE;
		}
	}
#endif

/* Set encoder */
int SetEncode_EPS_SM_Downlink (char* buffer, ED_EXLONG bitOffset, TEPS_SM_Downlink_Data* data)
{
	int retLen = ED_UNKNOWN_MESSAGE;
	ED_WARNING_REMOVER(bitOffset);
	
	switch (data->Type) {
		case ID_EPS_SM_Downlink_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST: {
			retLen = ENCODE_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST (buffer, 0, data->Data.fld_c_ACTIVATE_DEDICATED_EPS_BEARER_CONTEXT_REQUEST);
			break;
		}
		case ID_EPS_SM_Downlink_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST: {
			retLen = ENCODE_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST (buffer, 0, data->Data.fld_c_ACTIVATE_DEFAULT_EPS_BEARER_CONTEXT_REQUEST);
			break;
		}
		case ID_EPS_SM_Downlink_BEARER_RESOURCE_ALLOCATION_REJECT: {
			retLen = ENCODE_c_BEARER_RESOURCE_ALLOCATION_REJECT (buffer, 0, data->Data.fld_c_BEARER_RESOURCE_ALLOCATION_REJECT);
			break;
		}
		case ID_EPS_SM_Downlink_BEARER_RESOURCE_MODIFICATION_REJECT: {
			retLen = ENCODE_c_BEARER_RESOURCE_MODIFICATION_REJECT (buffer, 0, data->Data.fld_c_BEARER_RESOURCE_MODIFICATION_REJECT);
			break;
		}
		case ID_EPS_SM_Downlink_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST: {
			retLen = ENCODE_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST (buffer, 0, data->Data.fld_c_DEACTIVATE_EPS_BEARER_CONTEXT_REQUEST);
			break;
		}
		case ID_EPS_SM_Downlink_ESM_DUMMY_MESSAGE: {
			retLen = ENCODE_c_ESM_DUMMY_MESSAGE (buffer, 0, data->Data.fld_c_ESM_DUMMY_MESSAGE);
			break;
		}
		case ID_EPS_SM_Downlink_ESM_INFORMATION_REQUEST: {
			retLen = ENCODE_c_ESM_INFORMATION_REQUEST (buffer, 0, data->Data.fld_c_ESM_INFORMATION_REQUEST);
			break;
		}
		case ID_EPS_SM_Downlink_ESM_STATUS: {
			retLen = ENCODE_c_ESM_STATUS (buffer, 0, data->Data.fld_c_ESM_STATUS);
			break;
		}
		case ID_EPS_SM_Downlink_MODIFY_EPS_BEARER_CONTEXT_REQUEST: {
			retLen = ENCODE_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST (buffer, 0, data->Data.fld_c_MODIFY_EPS_BEARER_CONTEXT_REQUEST);
			break;
		}
		case ID_EPS_SM_Downlink_EPS_NOTIFICATION: {
			retLen = ENCODE_c_EPS_NOTIFICATION (buffer, 0, data->Data.fld_c_EPS_NOTIFICATION);
			break;
		}
		case ID_EPS_SM_Downlink_PDN_CONNECTIVITY_REJECT: {
			retLen = ENCODE_c_PDN_CONNECTIVITY_REJECT (buffer, 0, data->Data.fld_c_PDN_CONNECTIVITY_REJECT);
			break;
		}
		case ID_EPS_SM_Downlink_PDN_DISCONNECT_REJECT: {
			retLen = ENCODE_c_PDN_DISCONNECT_REJECT (buffer, 0, data->Data.fld_c_PDN_DISCONNECT_REJECT);
			break;
		}
		case ID_EPS_SM_Downlink_REMOTE_UE_REPORT_RESPONSE: {
			retLen = ENCODE_c_REMOTE_UE_REPORT_RESPONSE (buffer, 0, data->Data.fld_c_REMOTE_UE_REPORT_RESPONSE);
			break;
		}
		case ID_EPS_SM_Downlink_ESM_DATA_TRANSPORT: {
			retLen = ENCODE_c_ESM_DATA_TRANSPORT (buffer, 0, data->Data.fld_c_ESM_DATA_TRANSPORT);
			break;
		}

		default:;
	}
	return retLen;
}

