/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

File: octvc1_lte_api_swap.h	

Copyright (c) 2019 Octasic Inc. All rights reserved.	

Description:	

This source code is Octasic Confidential. Use of and access to this code
is covered by the Octasic Device Enabling Software License Agreement.
Acknowledgement of the Octasic Device Enabling Software License was
required for access to this code. A copy was also provided with the release.	

Release: OCTSDR Software Development Kit OCTSDR_LTE_APP-04.03.00-B3607 (2019/04/16)	

\*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/	
#ifndef __OCTVC1_LTE_API_SWAP_H__
#define __OCTVC1_LTE_API_SWAP_H__

#ifdef __cplusplus
extern "C" {
#endif

/*****************************  INCLUDE FILES  *******************************/
#include "../octvc1_swap_hdrs.h"
#include "octvc1_lte_api.h"

/*********************************  MACROS  **********************************/


#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MODULE_PROC_CONFIG_TYPE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_MODULE_PROC_CONFIG_TYPE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_DUPLEX_MODE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_DUPLEX_MODE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_CP_TYPE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_CP_TYPE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BANDWIDTH_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_BANDWIDTH_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_TDD_UL_DL_CONFIG_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_TDD_UL_DL_CONFIG_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_TDD_SPECIAL_SF_CONFIG_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_TDD_SPECIAL_SF_CONFIG_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_COMPLIANCE_TYPE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_COMPLIANCE_TYPE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_CELL_STATE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_CELL_STATE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_CELL_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_CELL_CONFIG * pOCTVC1_LTE_CELL_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_CELL_CONFIG)\
	{ mOCTVC1_LTE_DUPLEX_MODE_ENUM_SWAP( &((tOCTVC1_LTE_CELL_CONFIG *)pOCTVC1_LTE_CELL_CONFIG)->ulDuplexMode ); }  \
	{ mOCTVC1_LTE_CP_TYPE_ENUM_SWAP( &((tOCTVC1_LTE_CELL_CONFIG *)pOCTVC1_LTE_CELL_CONFIG)->ulCpType ); }  \
	{ mOCTVC1_LTE_BANDWIDTH_ENUM_SWAP( &((tOCTVC1_LTE_CELL_CONFIG *)pOCTVC1_LTE_CELL_CONFIG)->ulBwId ); }  \
}
#else
#define mOCTVC1_LTE_CELL_CONFIG_SWAP( pOCTVC1_LTE_CELL_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_CELL_TDD_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_CELL_TDD_CONFIG * pOCTVC1_LTE_CELL_TDD_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_CELL_TDD_CONFIG)\
	{ mOCTVC1_LTE_TDD_UL_DL_CONFIG_ENUM_SWAP( &((tOCTVC1_LTE_CELL_TDD_CONFIG *)pOCTVC1_LTE_CELL_TDD_CONFIG)->ulUplinkDownlinkConfigIdx ); }  \
	{ mOCTVC1_LTE_TDD_SPECIAL_SF_CONFIG_ENUM_SWAP( &((tOCTVC1_LTE_CELL_TDD_CONFIG *)pOCTVC1_LTE_CELL_TDD_CONFIG)->ulSpecialSubframeConfigIdx ); }  \
}
#else
#define mOCTVC1_LTE_CELL_TDD_CONFIG_SWAP( pOCTVC1_LTE_CELL_TDD_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_CELL_STATS_DOWNLINK_SWAP( _f_pParms ){ 	tOCTVC1_LTE_CELL_STATS_DOWNLINK * pOCTVC1_LTE_CELL_STATS_DOWNLINK = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_CELL_STATS_DOWNLINK)\
	((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulTtiCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulTtiCnt); \
	((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulCrntiTtiCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulCrntiTtiCnt); \
	((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulTbCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulTbCnt); \
	((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulAckCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulAckCnt); \
	((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulNackCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulNackCnt); \
	((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulDtxCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulDtxCnt); \
	((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulUeCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulUeCnt); \
	((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulKbitsCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_DOWNLINK *)pOCTVC1_LTE_CELL_STATS_DOWNLINK)->ulKbitsCnt); \
}
#else
#define mOCTVC1_LTE_CELL_STATS_DOWNLINK_SWAP( pOCTVC1_LTE_CELL_STATS_DOWNLINK )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_CELL_STATS_UPLINK_SWAP( _f_pParms ){ 	tOCTVC1_LTE_CELL_STATS_UPLINK * pOCTVC1_LTE_CELL_STATS_UPLINK = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_CELL_STATS_UPLINK)\
	((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulTtiCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulTtiCnt); \
	((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulCrntiTtiCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulCrntiTtiCnt); \
	((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulTbCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulTbCnt); \
	((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulCrcPassCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulCrcPassCnt); \
	((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulCrcFailCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulCrcFailCnt); \
	((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulUeCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulUeCnt); \
	((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulPrbCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulPrbCnt); \
	((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulKbitsCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_CELL_STATS_UPLINK *)pOCTVC1_LTE_CELL_STATS_UPLINK)->ulKbitsCnt); \
}
#else
#define mOCTVC1_LTE_CELL_STATS_UPLINK_SWAP( pOCTVC1_LTE_CELL_STATS_UPLINK )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_RF_CONFIG_SOURCE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_RF_CONFIG_SOURCE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_RF_ANTENNA_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_RF_ANTENNA_CONFIG * pOCTVC1_LTE_RF_ANTENNA_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_RF_ANTENNA_CONFIG)\
	((tOCTVC1_LTE_RF_ANTENNA_CONFIG *)pOCTVC1_LTE_RF_ANTENNA_CONFIG)->ulPhysicalAntennaId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_RF_ANTENNA_CONFIG *)pOCTVC1_LTE_RF_ANTENNA_CONFIG)->ulPhysicalAntennaId); \
}
#else
#define mOCTVC1_LTE_RF_ANTENNA_CONFIG_SWAP( pOCTVC1_LTE_RF_ANTENNA_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_RF_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_RF_CONFIG * pOCTVC1_LTE_RF_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_RF_CONFIG)\
	{ mOCTVC1_LTE_RF_CONFIG_SOURCE_ENUM_SWAP( &((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulConfigSource ); }  \
	((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulDownlinkEarfcn = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulDownlinkEarfcn); \
	((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulUplinkEarfcn = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulUplinkEarfcn); \
	((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulDownlinkFrequencyKhz = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulDownlinkFrequencyKhz); \
	((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulUplinkFrequencyKhz = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_RF_CONFIG *)pOCTVC1_LTE_RF_CONFIG)->ulUplinkFrequencyKhz); \
}
#else
#define mOCTVC1_LTE_RF_CONFIG_SWAP( pOCTVC1_LTE_RF_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG * pOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG)\
	((tOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG *)pOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG)->ulSfnSwitchOnGpioEnableFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG *)pOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG)->ulSfnSwitchOnGpioEnableFlag); \
	((tOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG *)pOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG)->ulSfnSwitchValue = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG *)pOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG)->ulSfnSwitchValue); \
}
#else
#define mOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG_SWAP( pOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_PHY_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_PHY_CONFIG * pOCTVC1_LTE_PHY_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_PHY_CONFIG)\
	((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulDownlinkCfrEnableFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulDownlinkCfrEnableFlag); \
	((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulUplinkHarqEnableFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulUplinkHarqEnableFlag); \
	((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulFrameTriggerGpioEnableFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulFrameTriggerGpioEnableFlag); \
	((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulTxDiversityEnableFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulTxDiversityEnableFlag); \
	((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulRxDiversityEnableFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->ulRxDiversityEnableFlag); \
	{ mOCTVC1_LTE_PHY_SFN_SWITCH_CONFIG_SWAP( &((tOCTVC1_LTE_PHY_CONFIG *)pOCTVC1_LTE_PHY_CONFIG)->SfnSwitchConfig ); }  \
}
#else
#define mOCTVC1_LTE_PHY_CONFIG_SWAP( pOCTVC1_LTE_PHY_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_STATE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_BASS_STATE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_STATE_SYNC_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_BASS_STATE_SYNC_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_RX_LEVEL_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_BASS_RX_LEVEL_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_BLACKLIST_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_BASS_BLACKLIST_CONFIG * pOCTVC1_LTE_BASS_BLACKLIST_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_BASS_BLACKLIST_CONFIG)\
	((tOCTVC1_LTE_BASS_BLACKLIST_CONFIG *)pOCTVC1_LTE_BASS_BLACKLIST_CONFIG)->ulNumPhysicalCellId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_BLACKLIST_CONFIG *)pOCTVC1_LTE_BASS_BLACKLIST_CONFIG)->ulNumPhysicalCellId); \
	{ tOCT_UINT32 iOCTVC1_LTE_BASS_BLACKLIST_CONFIG; \
	for( iOCTVC1_LTE_BASS_BLACKLIST_CONFIG=0; \
		iOCTVC1_LTE_BASS_BLACKLIST_CONFIG<(cOCTVC1_LTE_BASS_MAX_BLACKLIST_CELL);iOCTVC1_LTE_BASS_BLACKLIST_CONFIG++ ) \
	((tOCTVC1_LTE_BASS_BLACKLIST_CONFIG *)pOCTVC1_LTE_BASS_BLACKLIST_CONFIG)->aPhysicalCellIdList[iOCTVC1_LTE_BASS_BLACKLIST_CONFIG] = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_BLACKLIST_CONFIG *)pOCTVC1_LTE_BASS_BLACKLIST_CONFIG)->aPhysicalCellIdList[iOCTVC1_LTE_BASS_BLACKLIST_CONFIG]);}\
}
#else
#define mOCTVC1_LTE_BASS_BLACKLIST_CONFIG_SWAP( pOCTVC1_LTE_BASS_BLACKLIST_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_BASS_CONFIG * pOCTVC1_LTE_BASS_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_BASS_CONFIG)\
	((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulSpecificPciFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulSpecificPciFlag); \
	((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulPhysicalCellId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulPhysicalCellId); \
	((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulFrameOffset = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulFrameOffset); \
	((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulRxGainFixedFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulRxGainFixedFlag); \
	((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->lSnrThreshold = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->lSnrThreshold); \
	((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulTrackingPeriod = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->ulTrackingPeriod); \
	{ mOCTVC1_LTE_BASS_BLACKLIST_CONFIG_SWAP( &((tOCTVC1_LTE_BASS_CONFIG *)pOCTVC1_LTE_BASS_CONFIG)->tBlackListConfig ); }  \
}
#else
#define mOCTVC1_LTE_BASS_CONFIG_SWAP( pOCTVC1_LTE_BASS_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_CELL_STATS_SWAP( _f_pParms ){ 	tOCTVC1_LTE_BASS_CELL_STATS * pOCTVC1_LTE_BASS_CELL_STATS = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_BASS_CELL_STATS)\
	((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->ulPhysicalCellId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->ulPhysicalCellId); \
	{ mOCTVC1_LTE_DUPLEX_MODE_ENUM_SWAP( &((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->ulDuplexMode ); }  \
	{ mOCTVC1_LTE_CP_TYPE_ENUM_SWAP( &((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->ulCpType ); }  \
	((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->ulLinearPdpPower = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->ulLinearPdpPower); \
	((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->sSnr = \
		mOCT_SWAP16_IF_LE(((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->sSnr);  \
	((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->usReserved = \
		mOCT_SWAP16_IF_LE(((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->usReserved);  \
	((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->lAverageFrequencyError = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->lAverageFrequencyError); \
	((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->ulRelFrameDelay = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CELL_STATS *)pOCTVC1_LTE_BASS_CELL_STATS)->ulRelFrameDelay); \
}
#else
#define mOCTVC1_LTE_BASS_CELL_STATS_SWAP( pOCTVC1_LTE_BASS_CELL_STATS )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_EVENT_CELL_INFO_SWAP( _f_pParms ){ 	tOCTVC1_LTE_BASS_EVENT_CELL_INFO * pOCTVC1_LTE_BASS_EVENT_CELL_INFO = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_BASS_EVENT_CELL_INFO)\
	((tOCTVC1_LTE_BASS_EVENT_CELL_INFO *)pOCTVC1_LTE_BASS_EVENT_CELL_INFO)->ulPhysicalCellId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_EVENT_CELL_INFO *)pOCTVC1_LTE_BASS_EVENT_CELL_INFO)->ulPhysicalCellId); \
	((tOCTVC1_LTE_BASS_EVENT_CELL_INFO *)pOCTVC1_LTE_BASS_EVENT_CELL_INFO)->sSnr = \
		mOCT_SWAP16_IF_LE(((tOCTVC1_LTE_BASS_EVENT_CELL_INFO *)pOCTVC1_LTE_BASS_EVENT_CELL_INFO)->sSnr);  \
	((tOCTVC1_LTE_BASS_EVENT_CELL_INFO *)pOCTVC1_LTE_BASS_EVENT_CELL_INFO)->usReserved = \
		mOCT_SWAP16_IF_LE(((tOCTVC1_LTE_BASS_EVENT_CELL_INFO *)pOCTVC1_LTE_BASS_EVENT_CELL_INFO)->usReserved);  \
}
#else
#define mOCTVC1_LTE_BASS_EVENT_CELL_INFO_SWAP( pOCTVC1_LTE_BASS_EVENT_CELL_INFO )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_CHANNEL_STATS_SWAP( _f_pParms ){ 	tOCTVC1_LTE_BASS_CHANNEL_STATS * pOCTVC1_LTE_BASS_CHANNEL_STATS = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_BASS_CHANNEL_STATS)\
	{ mOCTVC1_LTE_BASS_RX_LEVEL_ENUM_SWAP( &((tOCTVC1_LTE_BASS_CHANNEL_STATS *)pOCTVC1_LTE_BASS_CHANNEL_STATS)->ulRxLevelIndicator ); }  \
	((tOCTVC1_LTE_BASS_CHANNEL_STATS *)pOCTVC1_LTE_BASS_CHANNEL_STATS)->ulNumCell = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CHANNEL_STATS *)pOCTVC1_LTE_BASS_CHANNEL_STATS)->ulNumCell); \
	{ tOCT_UINT32 jOCTVC1_LTE_BASS_CHANNEL_STATS; \
	for( jOCTVC1_LTE_BASS_CHANNEL_STATS=0; \
		jOCTVC1_LTE_BASS_CHANNEL_STATS<(cOCTVC1_LTE_BASS_MAX_NUM_CELL);jOCTVC1_LTE_BASS_CHANNEL_STATS++ ) \
	{ mOCTVC1_LTE_BASS_CELL_STATS_SWAP( &((tOCTVC1_LTE_BASS_CHANNEL_STATS *)pOCTVC1_LTE_BASS_CHANNEL_STATS)->aCellList[jOCTVC1_LTE_BASS_CHANNEL_STATS] ); }} \
}
#else
#define mOCTVC1_LTE_BASS_CHANNEL_STATS_SWAP( pOCTVC1_LTE_BASS_CHANNEL_STATS )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_CONTROL_STATS_SWAP( _f_pParms ){ 	tOCTVC1_LTE_BASS_CONTROL_STATS * pOCTVC1_LTE_BASS_CONTROL_STATS = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_BASS_CONTROL_STATS)\
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulActiveSourceCellFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulActiveSourceCellFlag); \
	{ mOCTVC1_LTE_BASS_CELL_STATS_SWAP( &((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ChannelInfo ); }  \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulCellSourceLostCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulCellSourceLostCnt); \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->lFrequencyCorrectionError = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->lFrequencyCorrectionError); \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulFrequencyCorrectionCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulFrequencyCorrectionCnt); \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulTrackingErrorCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulTrackingErrorCnt); \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulTrackingTotalCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulTrackingTotalCnt); \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->lRxGaindB = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->lRxGaindB); \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulReserved = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulReserved); \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulReserved1 = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulReserved1); \
	((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulReserved2 = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_BASS_CONTROL_STATS *)pOCTVC1_LTE_BASS_CONTROL_STATS)->ulReserved2); \
}
#else
#define mOCTVC1_LTE_BASS_CONTROL_STATS_SWAP( pOCTVC1_LTE_BASS_CONTROL_STATS )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_BASS_STATS_SWAP( _f_pParms ){ 	tOCTVC1_LTE_BASS_STATS * pOCTVC1_LTE_BASS_STATS = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_BASS_STATS)\
	{ mOCTVC1_LTE_BASS_STATE_ENUM_SWAP( &((tOCTVC1_LTE_BASS_STATS *)pOCTVC1_LTE_BASS_STATS)->ulState ); }  \
	{ mOCTVC1_LTE_BASS_STATE_SYNC_ENUM_SWAP( &((tOCTVC1_LTE_BASS_STATS *)pOCTVC1_LTE_BASS_STATS)->ulStateSync ); }  \
	{ mOCTVC1_LTE_BASS_CHANNEL_STATS_SWAP( &((tOCTVC1_LTE_BASS_STATS *)pOCTVC1_LTE_BASS_STATS)->ChannelInfo ); }  \
	{ mOCTVC1_LTE_BASS_CONTROL_STATS_SWAP( &((tOCTVC1_LTE_BASS_STATS *)pOCTVC1_LTE_BASS_STATS)->ControlInfo ); }  \
}
#else
#define mOCTVC1_LTE_BASS_STATS_SWAP( pOCTVC1_LTE_BASS_STATS )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_PHY_FRAME_SYNC_STATS_SWAP( _f_pParms ){ 	tOCTVC1_LTE_PHY_FRAME_SYNC_STATS * pOCTVC1_LTE_PHY_FRAME_SYNC_STATS = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_PHY_FRAME_SYNC_STATS)\
	((tOCTVC1_LTE_PHY_FRAME_SYNC_STATS *)pOCTVC1_LTE_PHY_FRAME_SYNC_STATS)->ulSfnSwitchOnGpioCheckCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_FRAME_SYNC_STATS *)pOCTVC1_LTE_PHY_FRAME_SYNC_STATS)->ulSfnSwitchOnGpioCheckCnt); \
	((tOCTVC1_LTE_PHY_FRAME_SYNC_STATS *)pOCTVC1_LTE_PHY_FRAME_SYNC_STATS)->ulSfnSwitchOnGpioRequestCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_FRAME_SYNC_STATS *)pOCTVC1_LTE_PHY_FRAME_SYNC_STATS)->ulSfnSwitchOnGpioRequestCnt); \
	((tOCTVC1_LTE_PHY_FRAME_SYNC_STATS *)pOCTVC1_LTE_PHY_FRAME_SYNC_STATS)->ulSfnSwitchOnGpioErrorCnt = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_PHY_FRAME_SYNC_STATS *)pOCTVC1_LTE_PHY_FRAME_SYNC_STATS)->ulSfnSwitchOnGpioErrorCnt); \
}
#else
#define mOCTVC1_LTE_PHY_FRAME_SYNC_STATS_SWAP( pOCTVC1_LTE_PHY_FRAME_SYNC_STATS )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_TEST_MODULE_STATE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_TEST_MODULE_STATE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_PHY_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_PHY_CONFIG * pOCTVC1_LTE_FAPI_PHY_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_PHY_CONFIG)\
	((tOCTVC1_LTE_FAPI_PHY_CONFIG *)pOCTVC1_LTE_FAPI_PHY_CONFIG)->ulFapiConfigHoldFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PHY_CONFIG *)pOCTVC1_LTE_FAPI_PHY_CONFIG)->ulFapiConfigHoldFlag); \
}
#else
#define mOCTVC1_LTE_FAPI_PHY_CONFIG_SWAP( pOCTVC1_LTE_FAPI_PHY_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_ETM_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_ETM_CONFIG * pOCTVC1_LTE_ETM_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_ETM_CONFIG)\
	((tOCTVC1_LTE_ETM_CONFIG *)pOCTVC1_LTE_ETM_CONFIG)->ulEpreIndex = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_ETM_CONFIG *)pOCTVC1_LTE_ETM_CONFIG)->ulEpreIndex); \
}
#else
#define mOCTVC1_LTE_ETM_CONFIG_SWAP( pOCTVC1_LTE_ETM_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_PHY_STATE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_LTE_FAPI_PHY_STATE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_CELL_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_CELL_CONFIG * pOCTVC1_LTE_FAPI_CELL_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_CELL_CONFIG)\
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulDuplexingMode = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulDuplexingMode); \
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulDownlinkCyclicPrefixType = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulDownlinkCyclicPrefixType); \
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulUplinkCyclicPrefixType = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulUplinkCyclicPrefixType); \
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulDownlinkChannelBandwidth = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulDownlinkChannelBandwidth); \
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulUplinkChannelBandwidth = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulUplinkChannelBandwidth); \
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulTxAntennaPort = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulTxAntennaPort); \
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulRxAntennaPort = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulRxAntennaPort); \
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulRefSignalPower = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulRefSignalPower); \
	((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulPhysicalCellId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_CELL_CONFIG *)pOCTVC1_LTE_FAPI_CELL_CONFIG)->ulPhysicalCellId); \
}
#else
#define mOCTVC1_LTE_FAPI_CELL_CONFIG_SWAP( pOCTVC1_LTE_FAPI_CELL_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_PHICH_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_PHICH_CONFIG * pOCTVC1_LTE_FAPI_PHICH_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_PHICH_CONFIG)\
	((tOCTVC1_LTE_FAPI_PHICH_CONFIG *)pOCTVC1_LTE_FAPI_PHICH_CONFIG)->ulResource = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PHICH_CONFIG *)pOCTVC1_LTE_FAPI_PHICH_CONFIG)->ulResource); \
	((tOCTVC1_LTE_FAPI_PHICH_CONFIG *)pOCTVC1_LTE_FAPI_PHICH_CONFIG)->ulDuration = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PHICH_CONFIG *)pOCTVC1_LTE_FAPI_PHICH_CONFIG)->ulDuration); \
	((tOCTVC1_LTE_FAPI_PHICH_CONFIG *)pOCTVC1_LTE_FAPI_PHICH_CONFIG)->ulPowerOffset = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PHICH_CONFIG *)pOCTVC1_LTE_FAPI_PHICH_CONFIG)->ulPowerOffset); \
}
#else
#define mOCTVC1_LTE_FAPI_PHICH_CONFIG_SWAP( pOCTVC1_LTE_FAPI_PHICH_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_PCFICH_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_PCFICH_CONFIG * pOCTVC1_LTE_FAPI_PCFICH_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_PCFICH_CONFIG)\
	((tOCTVC1_LTE_FAPI_PCFICH_CONFIG *)pOCTVC1_LTE_FAPI_PCFICH_CONFIG)->ulPowerOffset = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PCFICH_CONFIG *)pOCTVC1_LTE_FAPI_PCFICH_CONFIG)->ulPowerOffset); \
}
#else
#define mOCTVC1_LTE_FAPI_PCFICH_CONFIG_SWAP( pOCTVC1_LTE_FAPI_PCFICH_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG * pOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG)\
	((tOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG)->ulPssPowerOffset = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG)->ulPssPowerOffset); \
	((tOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG)->ulSssPowerOffset = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG)->ulSssPowerOffset); \
}
#else
#define mOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG_SWAP( pOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_PRACH_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_PRACH_CONFIG * pOCTVC1_LTE_FAPI_PRACH_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_PRACH_CONFIG)\
	((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulConfigIndex = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulConfigIndex); \
	((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulRootSequenceIndex = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulRootSequenceIndex); \
	((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulZeroCorrelationZoneConfig = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulZeroCorrelationZoneConfig); \
	((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulHighSpeedFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulHighSpeedFlag); \
	((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulFrequencyOffset = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PRACH_CONFIG *)pOCTVC1_LTE_FAPI_PRACH_CONFIG)->ulFrequencyOffset); \
}
#else
#define mOCTVC1_LTE_FAPI_PRACH_CONFIG_SWAP( pOCTVC1_LTE_FAPI_PRACH_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_PUSCH_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_PUSCH_CONFIG * pOCTVC1_LTE_FAPI_PUSCH_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_PUSCH_CONFIG)\
	((tOCTVC1_LTE_FAPI_PUSCH_CONFIG *)pOCTVC1_LTE_FAPI_PUSCH_CONFIG)->ulHoppingMode = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PUSCH_CONFIG *)pOCTVC1_LTE_FAPI_PUSCH_CONFIG)->ulHoppingMode); \
	((tOCTVC1_LTE_FAPI_PUSCH_CONFIG *)pOCTVC1_LTE_FAPI_PUSCH_CONFIG)->ulHoppingOffset = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PUSCH_CONFIG *)pOCTVC1_LTE_FAPI_PUSCH_CONFIG)->ulHoppingOffset); \
	((tOCTVC1_LTE_FAPI_PUSCH_CONFIG *)pOCTVC1_LTE_FAPI_PUSCH_CONFIG)->ulHoppingNumSubBand = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PUSCH_CONFIG *)pOCTVC1_LTE_FAPI_PUSCH_CONFIG)->ulHoppingNumSubBand); \
}
#else
#define mOCTVC1_LTE_FAPI_PUSCH_CONFIG_SWAP( pOCTVC1_LTE_FAPI_PUSCH_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_PUCCH_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_PUCCH_CONFIG * pOCTVC1_LTE_FAPI_PUCCH_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_PUCCH_CONFIG)\
	((tOCTVC1_LTE_FAPI_PUCCH_CONFIG *)pOCTVC1_LTE_FAPI_PUCCH_CONFIG)->ulDeltaShift = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PUCCH_CONFIG *)pOCTVC1_LTE_FAPI_PUCCH_CONFIG)->ulDeltaShift); \
	((tOCTVC1_LTE_FAPI_PUCCH_CONFIG *)pOCTVC1_LTE_FAPI_PUCCH_CONFIG)->ulNumCqiRb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PUCCH_CONFIG *)pOCTVC1_LTE_FAPI_PUCCH_CONFIG)->ulNumCqiRb); \
	((tOCTVC1_LTE_FAPI_PUCCH_CONFIG *)pOCTVC1_LTE_FAPI_PUCCH_CONFIG)->ulNumAnCs = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PUCCH_CONFIG *)pOCTVC1_LTE_FAPI_PUCCH_CONFIG)->ulNumAnCs); \
	((tOCTVC1_LTE_FAPI_PUCCH_CONFIG *)pOCTVC1_LTE_FAPI_PUCCH_CONFIG)->ulN1An = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_PUCCH_CONFIG *)pOCTVC1_LTE_FAPI_PUCCH_CONFIG)->ulN1An); \
}
#else
#define mOCTVC1_LTE_FAPI_PUCCH_CONFIG_SWAP( pOCTVC1_LTE_FAPI_PUCCH_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_SRS_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_SRS_CONFIG * pOCTVC1_LTE_FAPI_SRS_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_SRS_CONFIG)\
	((tOCTVC1_LTE_FAPI_SRS_CONFIG *)pOCTVC1_LTE_FAPI_SRS_CONFIG)->ulBandwidthConfiguration = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_SRS_CONFIG *)pOCTVC1_LTE_FAPI_SRS_CONFIG)->ulBandwidthConfiguration); \
	((tOCTVC1_LTE_FAPI_SRS_CONFIG *)pOCTVC1_LTE_FAPI_SRS_CONFIG)->ulMaxUpPts = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_SRS_CONFIG *)pOCTVC1_LTE_FAPI_SRS_CONFIG)->ulMaxUpPts); \
	((tOCTVC1_LTE_FAPI_SRS_CONFIG *)pOCTVC1_LTE_FAPI_SRS_CONFIG)->ulSubframeConfiguration = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_SRS_CONFIG *)pOCTVC1_LTE_FAPI_SRS_CONFIG)->ulSubframeConfiguration); \
	((tOCTVC1_LTE_FAPI_SRS_CONFIG *)pOCTVC1_LTE_FAPI_SRS_CONFIG)->ulAckNackSimulaneousTx = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_SRS_CONFIG *)pOCTVC1_LTE_FAPI_SRS_CONFIG)->ulAckNackSimulaneousTx); \
}
#else
#define mOCTVC1_LTE_FAPI_SRS_CONFIG_SWAP( pOCTVC1_LTE_FAPI_SRS_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG * pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG)\
	((tOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG)->ulRsHopping = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG)->ulRsHopping); \
	((tOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG)->ulRsGroupAssignment = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG)->ulRsGroupAssignment); \
	((tOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG)->ulRsCyclicShift1Dmrs = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG *)pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG)->ulRsCyclicShift1Dmrs); \
}
#else
#define mOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG_SWAP( pOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_TDD_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_TDD_CONFIG * pOCTVC1_LTE_FAPI_TDD_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_TDD_CONFIG)\
	((tOCTVC1_LTE_FAPI_TDD_CONFIG *)pOCTVC1_LTE_FAPI_TDD_CONFIG)->ulSubframeAssignment = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_TDD_CONFIG *)pOCTVC1_LTE_FAPI_TDD_CONFIG)->ulSubframeAssignment); \
	((tOCTVC1_LTE_FAPI_TDD_CONFIG *)pOCTVC1_LTE_FAPI_TDD_CONFIG)->ulSpecialSubframePattern = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_FAPI_TDD_CONFIG *)pOCTVC1_LTE_FAPI_TDD_CONFIG)->ulSpecialSubframePattern); \
}
#else
#define mOCTVC1_LTE_FAPI_TDD_CONFIG_SWAP( pOCTVC1_LTE_FAPI_TDD_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG * pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)\
	{ mOCTVC1_LTE_FAPI_PHY_STATE_ENUM_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->ulState ); }  \
	{ mOCTVC1_LTE_FAPI_CELL_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->Cell ); }  \
	{ mOCTVC1_LTE_FAPI_TDD_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->Tdd ); }  \
	{ mOCTVC1_LTE_FAPI_PHICH_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->Phich ); }  \
	{ mOCTVC1_LTE_FAPI_PCFICH_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->Pcfich ); }  \
	{ mOCTVC1_LTE_FAPI_DL_PHY_SIGNAL_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->DownlinkPhySignal ); }  \
	{ mOCTVC1_LTE_FAPI_PRACH_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->Prach ); }  \
	{ mOCTVC1_LTE_FAPI_PUSCH_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->Pusch ); }  \
	{ mOCTVC1_LTE_FAPI_PUCCH_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->Pucch ); }  \
	{ mOCTVC1_LTE_FAPI_SRS_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->Srs ); }  \
	{ mOCTVC1_LTE_FAPI_UL_PHY_SIGNAL_CONFIG_SWAP( &((tOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG *)pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG)->UplinkPhySignal ); }  \
}
#else
#define mOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG_SWAP( pOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CMD * pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CMD *)pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CMD)->Header ); }  \
}
#else
#define mOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CMD_SWAP( pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP * pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP *)pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP)->Header ); }  \
	{ mOCTVC1_LTE_MODULE_PROC_CONFIG_TYPE_ENUM_SWAP( &((tOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP *)pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP)->ulBootProcConfigType ); }  \
}
#else
#define mOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP_SWAP( pOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD * pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD *)pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD)->Header ); }  \
	{ mOCTVC1_LTE_MODULE_PROC_CONFIG_TYPE_ENUM_SWAP( &((tOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD *)pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD)->ulBootProcConfigType ); }  \
}
#else
#define mOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD_SWAP( pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_RSP * pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_RSP *)pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_RSP)->Header ); }  \
}
#else
#define mOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_RSP_SWAP( pOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_OPEN_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD * pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->ulUserId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->ulUserId); \
	((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->ulRfPortIndex = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->ulRfPortIndex); \
	{ mOCTVC1_LTE_CELL_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->CellConfig ); }  \
	{ mOCTVC1_LTE_CELL_TDD_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->CellTddConfig ); }  \
	{ mOCTVC1_LTE_RF_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->RfConfig ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->bTxOuputScPwrEqual = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->bTxOuputScPwrEqual); \
	((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->bUseExtFirCoeff = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->bUseExtFirCoeff); \
	((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->ulFrameBorderAlignEnableFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->ulFrameBorderAlignEnableFlag); \
	((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->ulFrameBorderDelaySamples = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->ulFrameBorderDelaySamples); \
	{ mOCTVC1_LTE_PHY_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->PhyConfig ); }  \
	{ mOCTVC1_LTE_BASS_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_OPEN_CMD *)pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD)->BassConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_OPEN_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_OPEN_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_OPEN_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_OPEN_RSP * pOCTVC1_LTE_MSG_ENODEB_OPEN_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_OPEN_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_OPEN_RSP *)pOCTVC1_LTE_MSG_ENODEB_OPEN_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_OPEN_RSP *)pOCTVC1_LTE_MSG_ENODEB_OPEN_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_OPEN_RSP *)pOCTVC1_LTE_MSG_ENODEB_OPEN_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_OPEN_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_OPEN_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD * pOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD *)pOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD *)pOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD *)pOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_CLOSE_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP * pOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP *)pOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP *)pOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP *)pOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_CLOSE_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_CMD * pOCTVC1_LTE_MSG_ENODEB_INFO_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_RSP * pOCTVC1_LTE_MSG_ENODEB_INFO_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RSP)->hEnodeb); \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RSP)->ulUserId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RSP)->ulUserId); \
	{ mOCTVC1_LTE_COMPLIANCE_TYPE_ENUM_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RSP)->ulStandardComplianceType ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_LIST_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_LIST_CMD * pOCTVC1_LTE_MSG_ENODEB_LIST_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_LIST_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_LIST_CMD *)pOCTVC1_LTE_MSG_ENODEB_LIST_CMD)->Header ); }  \
	{ mOCTVC1_CURSOR_HANDLE_OBJECT_GET_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_LIST_CMD *)pOCTVC1_LTE_MSG_ENODEB_LIST_CMD)->ObjectCursor ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_LIST_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_LIST_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_LIST_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_LIST_RSP * pOCTVC1_LTE_MSG_ENODEB_LIST_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_LIST_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_LIST_RSP *)pOCTVC1_LTE_MSG_ENODEB_LIST_RSP)->Header ); }  \
	{ mOCTVC1_CURSOR_HANDLE_OBJECT_GET_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_LIST_RSP *)pOCTVC1_LTE_MSG_ENODEB_LIST_RSP)->ObjectCursor ); }  \
	{ mOCTVC1_LIST_HANDLE_OBJECT_GET_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_LIST_RSP *)pOCTVC1_LTE_MSG_ENODEB_LIST_RSP)->ObjectList ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_LIST_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_LIST_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD * pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP * pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP)->hEnodeb); \
	{ mOCTVC1_LTE_CELL_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP)->CellConfig ); }  \
	{ mOCTVC1_LTE_CELL_TDD_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP)->CellTddConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_CELL_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD * pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD)->hEnodeb); \
	((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD)->ulResetStatsFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD)->ulResetStatsFlag); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP * pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP)->hEnodeb); \
	{ mOCTVC1_LTE_CELL_STATE_ENUM_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP)->ulState ); }  \
	{ mOCTVC1_LTE_CELL_STATS_DOWNLINK_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP)->Downlink ); }  \
	{ mOCTVC1_LTE_CELL_STATS_UPLINK_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP)->Uplink ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_STATS_CELL_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD * pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD)->hEnodeb); \
	{ mOCTVC1_LTE_CELL_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD)->CellConfig ); }  \
	{ mOCTVC1_LTE_CELL_TDD_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD)->CellTddConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP * pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD * pOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_START_CELL_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP * pOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_START_CELL_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD * pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD *)pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP * pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP *)pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_STOP_CELL_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD * pOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_RF_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP * pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->hEnodeb); \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->ulRfPortIndex = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->ulRfPortIndex); \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->ulRfBandId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->ulRfBandId); \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->bUseExtFirCoeff = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->bUseExtFirCoeff); \
	{ mOCTVC1_LTE_RF_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->RfConfig ); }  \
	{ tOCT_UINT32 jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP; \
	for( jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP=0; \
		jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP<((2));jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP++ ) \
	{ mOCTVC1_LTE_RF_ANTENNA_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->aTxLogicalAntennaConfig[jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP] ); }} \
	{ tOCT_UINT32 jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP; \
	for( jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP=0; \
		jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP<((2));jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP++ ) \
	{ mOCTVC1_LTE_RF_ANTENNA_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP)->aRxLogicalAntennaConfig[jOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP] ); }} \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_RF_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD * pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD)->hEnodeb); \
	{ mOCTVC1_LTE_RF_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD)->RfConfig ); }  \
	{ tOCT_UINT32 jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD; \
	for( jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD=0; \
		jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD<((2));jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD++ ) \
	{ mOCTVC1_LTE_RF_ANTENNA_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD)->aTxLogicalAntennaConfig[jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD] ); }} \
	{ tOCT_UINT32 jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD; \
	for( jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD=0; \
		jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD<((2));jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD++ ) \
	{ mOCTVC1_LTE_RF_ANTENNA_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD)->aRxLogicalAntennaConfig[jOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD] ); }} \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP * pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD * pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP * pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->hEnodeb); \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->bTxOuputScPwrEqual = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->bTxOuputScPwrEqual); \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->ulFrameBorderAlignEnableFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->ulFrameBorderAlignEnableFlag); \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->ulFrameBorderDelaySamples = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->ulFrameBorderDelaySamples); \
	{ mOCTVC1_LTE_PHY_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP)->PhyConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_PHY_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD * pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD)->hEnodeb); \
	{ mOCTVC1_LTE_PHY_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD)->PhyConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP * pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD * pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP * pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP)->hEnodeb); \
	{ mOCTVC1_LTE_PHY_FRAME_SYNC_STATS_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP)->FrameSync ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_STATS_PHY_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD * pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP * pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP)->hEnodeb); \
	{ mOCTVC1_LTE_ETM_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP)->EtmConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_ETM_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD * pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD)->hEnodeb); \
	{ mOCTVC1_LTE_ETM_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD)->EtmConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP * pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD * pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP * pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP)->hEnodeb); \
	{ mOCTVC1_LTE_FAPI_PHY_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP)->FapiPhyConfig ); }  \
	{ mOCTVC1_LTE_FAPI_CELL_PARAM_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP)->FapiCellConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD * pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD)->hEnodeb); \
	{ mOCTVC1_LTE_FAPI_PHY_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD)->FapiPhyConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP * pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP *)pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD * pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP * pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP)->hEnodeb); \
	{ mOCTVC1_LTE_BASS_CONFIG_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP)->BassConfig ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_INFO_BASS_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD * pOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_START_BASS_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP * pOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP)->hEnodeb); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_START_BASS_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD * pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD)->hEnodeb); \
	((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD)->ulResetStatsFlag = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD)->ulResetStatsFlag); \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD_SWAP( pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP_SWAP( _f_pParms ){ 	tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP * pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP)->Header ); }  \
	((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP)->hEnodeb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP)->hEnodeb); \
	{ mOCTVC1_LTE_BASS_STATS_SWAP( &((tOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP *)pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP)->BassStats ); }  \
}
#else
#define mOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP_SWAP( pOCTVC1_LTE_MSG_ENODEB_STATS_BASS_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#ifdef __cplusplus
}

#endif

#endif /* __OCTVC1_LTE_API_SWAP_H__ */
