/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*\

File: OCTVC1_LTE_RC.h

Copyright (c) 2019 Octasic Inc. All rights reserved.

Description: Contains the return codes for the LTE API.

This source code is Octasic Confidential. Use of and access to this code
is covered by the Octasic Device Enabling Software License Agreement.
Acknowledgement of the Octasic Device Enabling Software License was
required for access to this code. A copy was also provided with the release.

Release: OCTSDR Software Development Kit OCTSDR_LTE_APP-04.03.00-B3607 (2019/04/16)

$Octasic_Revision: $

\*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/

#ifndef OCTVC1_LTE_RC_H__
#define OCTVC1_LTE_RC_H__


/*****************************  INCLUDE FILES  *******************************/
#include "../octvc1_base.h"
#include "../octvc1_generic_rc.h"
#include "octvc1_lte_base.h"

/****************************************************************************
	LTE return codes
 ****************************************************************************/

/****************************************************************************
	MODULE return codes
 ****************************************************************************/
#define cOCTVC1_LTE_MODULE_RC_BASE							 ( 0x0100 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_MODULE_INTERNAL_ERROR				 ( 0x0000 + cOCTVC1_LTE_MODULE_RC_BASE )
#define cOCTVC1_LTE_RC_MODULE_STATE_INVALID					 ( 0x0001 + cOCTVC1_LTE_MODULE_RC_BASE )
#define cOCTVC1_LTE_RC_MODULE_CONFIG_NOT_SUPPORTED			 ( 0x0002 + cOCTVC1_LTE_MODULE_RC_BASE )
#define cOCTVC1_LTE_RC_MODULE_CONFIG_ERROR					 ( 0x0003 + cOCTVC1_LTE_MODULE_RC_BASE )
#define cOCTVC1_LTE_RC_MODULE_PROFILE_TYPE_NOT_SUPPORTED	 ( 0x0004 + cOCTVC1_LTE_MODULE_RC_BASE )
#define cOCTVC1_LTE_RC_MODULE_PROFILE_TYPE_INVALID			 ( 0x0005 + cOCTVC1_LTE_MODULE_RC_BASE )
#define cOCTVC1_LTE_RC_MODULE_CONTEXT_ERROR					 ( 0x0006 + cOCTVC1_LTE_MODULE_RC_BASE )
#define cOCTVC1_LTE_RC_MODULE_LICENSE_INVALID				 ( 0x0007 + cOCTVC1_LTE_MODULE_RC_BASE )

/****************************************************************************
	ENODEB return codes
 ****************************************************************************/
#define cOCTVC1_LTE_ENODEB_RC_BASE								 ( 0x0200 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_ENODEB_INTERNAL_ERROR					 ( 0x0000 + cOCTVC1_LTE_ENODEB_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CONFIG_NOT_SUPPORTED				 ( 0x0001 + cOCTVC1_LTE_ENODEB_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_STANDARD_COMPLIANCE_TYPE_INVALID	 ( 0x0002 + cOCTVC1_LTE_ENODEB_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_OPEN_RF_SCRIPT_NOT_FOUND			 ( 0x0011 + cOCTVC1_LTE_ENODEB_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_OPEN_RF_PORT_ALREADY_USED			 ( 0x0012 + cOCTVC1_LTE_ENODEB_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_OPEN_RF_PORT_CONFIG_ERROR			 ( 0x0013 + cOCTVC1_LTE_ENODEB_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_OPEN_FIR_COEFF_NOT_FOUND			 ( 0x0014 + cOCTVC1_LTE_ENODEB_RC_BASE )

/****************************************************************************
	ENODEB_CELL return codes
 ****************************************************************************/
#define cOCTVC1_LTE_ENODEB_CELL_RC_BASE						 ( 0x0300 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_ENODEB_CELL_INTERNAL_ERROR			 ( 0x0000 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_HAB_ERROR				 ( 0x0001 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_CORE_ERROR				 ( 0x0002 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_CONFIG_INVALID			 ( 0x0011 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_CONFIG_NOT_SUPPORTED		 ( 0x0012 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_CONFIG_ERROR				 ( 0x0013 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_CONFIG_BW_UNSUPPORTED	 ( 0x0014 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_TDD_CONFIG_INVALID		 ( 0x0021 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_TDD_CONFIG_ERROR			 ( 0x0022 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_STATE_ALREADY_SETUP		 ( 0x0041 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_STATE_INVALID			 ( 0x0042 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_STATE_RUNNING			 ( 0x0043 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_SETUP_INTERNAL_ERROR		 ( 0x0051 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_CELL_DELETE_INTERNAL_ERROR	 ( 0x0061 + cOCTVC1_LTE_ENODEB_CELL_RC_BASE )

/****************************************************************************
	ENODEB_RF return codes
 ****************************************************************************/
#define cOCTVC1_LTE_ENODEB_RF_RC_BASE										 ( 0x0400 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_ERROR								 ( 0x0011 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_UNSUPPORTED							 ( 0x0012 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_TX_FREQUENCY_OUT_OF_RANGE			 ( 0x0013 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_TX_ATTENUATION_OUT_OF_RANGE			 ( 0x0014 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_TX_CALIBRATION_NOT_SUPPORTED_BY_HW	 ( 0x0015 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_RX_FREQUENCY_OUT_OF_RANGE			 ( 0x0016 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_RX_GAIN_OUT_OF_RANGE				 ( 0x0017 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_PCB_INFO_ERROR						 ( 0x0018 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_DL_EARFCN_INVALID					 ( 0x0019 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_DL_EARFCN_INVALID_FOR_DOWNLINK		 ( 0x0020 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_DL_EARFCN_NOT_FOUND					 ( 0x0021 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_UL_EARFCN_INVALID					 ( 0x0022 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_UL_EARFCN_INVALID_FOR_UPLINK		 ( 0x0023 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_UL_EARFCN_NOT_FOUND					 ( 0x0024 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_EARFCN_NOT_FOUND					 ( 0x0025 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_EARFCN_REQUIRED						 ( 0x0026 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_EARFCN_PAIR_BAND_MISMATCH			 ( 0x0027 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_3GPP_ERROR							 ( 0x0028 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_3GPP_EARFCN_INVALID_FOR_DUPLEXMODE	 ( 0x0029 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_3GPP_EARFCN_INVALID_FOR_BW			 ( 0x002a + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_3GPP_EARFCN_PAIR_INVALID			 ( 0x002b + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_CONFIG_SOURCE_INVALID						 ( 0x002c + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_TX_ANTENNA_ID_INVALID						 ( 0x0031 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_TX_ANTENNA_ID_CONFLICT						 ( 0x0032 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_RX_ANTENNA_ID_INVALID						 ( 0x0033 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_RX_ANTENNA_ID_CONFLICT						 ( 0x0034 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_RADIO_TX_CONFIG_ERROR						 ( 0x0041 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_RADIO_RX_CONFIG_ERROR						 ( 0x0042 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_RADIO_INIT_FAIL							 ( 0x0043 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_RF_RADIO_TERMINATE_FAIL						 ( 0x0044 + cOCTVC1_LTE_ENODEB_RF_RC_BASE )

/****************************************************************************
	ENODEB_PHY return codes
 ****************************************************************************/
#define cOCTVC1_LTE_ENODEB_PHY_RC_BASE						 ( 0x0500 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_ENODEB_PHY_CONFIG_INVALID			 ( 0x0011 + cOCTVC1_LTE_ENODEB_PHY_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_PHY_CONFIG_NOT_SUPPORTED		 ( 0x0012 + cOCTVC1_LTE_ENODEB_PHY_RC_BASE )

/****************************************************************************
	TEST return codes
 ****************************************************************************/
#define cOCTVC1_LTE_TEST_RC_BASE							 ( 0x0600 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_TEST_INTERNAL_ERROR					 ( 0x0000 + cOCTVC1_LTE_TEST_RC_BASE )
#define cOCTVC1_LTE_RC_TEST_ALREADY_RUNNING					 ( 0x0001 + cOCTVC1_LTE_TEST_RC_BASE )

/****************************************************************************
	ETM return codes
 ****************************************************************************/
#define cOCTVC1_LTE_ETM_RC_BASE								 ( 0x0700 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_ETM_CONFIG_INVALID					 ( 0x0000 + cOCTVC1_LTE_ETM_RC_BASE )
#define cOCTVC1_LTE_RC_ETM_CONFIG_NOT_SUPPORTED				 ( 0x0001 + cOCTVC1_LTE_ETM_RC_BASE )
#define cOCTVC1_LTE_RC_ETM_TDD_CONFIG_INVALID				 ( 0x0002 + cOCTVC1_LTE_ETM_RC_BASE )

/****************************************************************************
	ENODEB_BASS return codes
 ****************************************************************************/
#define cOCTVC1_LTE_ENODEB_BASS_RC_BASE							 ( 0x0800 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_ENODEB_BASS_CONFIG_INVALID				 ( 0x0000 + cOCTVC1_LTE_ENODEB_BASS_RC_BASE )
#define cOCTVC1_LTE_RC_ENODEB_BASS_CONFIG_INVALID_FRAME_OFFSET	 ( 0x0001 + cOCTVC1_LTE_ENODEB_BASS_RC_BASE )

/****************************************************************************
	Validate return codes
 ****************************************************************************/
#define cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE									 ( 0xF000 + cOCTVC1_LTE_RC_BASE )

#define cOCTVC1_LTE_RC_RF_ANTENNA_CONFIG_INVALID_PHYSICAL_ANTENNA_ID		 ( 0x1 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_RF_CONFIG_INVALID_DOWNLINK_EARFCN					 ( 0x2 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_RF_CONFIG_INVALID_UPLINK_EARFCN						 ( 0x3 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_RF_CONFIG_INVALID_DOWNLINK_FREQUENCY_KHZ				 ( 0x4 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_RF_CONFIG_INVALID_UPLINK_FREQUENCY_KHZ				 ( 0x5 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_PHY_SFN_SWITCH_CONFIG_INVALID_SFN_SWITCH_VALUE		 ( 0x6 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_BLACKLIST_CONFIG_INVALID_NUM_PHYSICAL_CELL_ID	 ( 0x7 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CONFIG_INVALID_PHYSICAL_CELL_ID					 ( 0x8 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CONFIG_INVALID_SNR_THRESHOLD					 ( 0x9 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CONFIG_INVALID_TRACKING_PERIOD					 ( 0xA + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CELL_STATS_INVALID_PHYSICAL_CELL_ID				 ( 0xB + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CELL_STATS_INVALID_LINEAR_PDP_POWER				 ( 0xC + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CELL_STATS_INVALID_AVERAGE_FREQUENCY_ERROR		 ( 0xD + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CELL_STATS_INVALID_REL_FRAME_DELAY				 ( 0xE + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_EVENT_CELL_INFO_INVALID_PHYSICAL_CELL_ID		 ( 0xF + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CHANNEL_STATS_INVALID_NUM_CELL					 ( 0x10 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CONTROL_STATS_INVALID_CELL_SOURCE_LOST_CNT		 ( 0x11 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CONTROL_STATS_INVALID_FREQUENCY_CORRECTION_CNT	 ( 0x12 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CONTROL_STATS_INVALID_TRACKING_ERROR_CNT		 ( 0x13 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CONTROL_STATS_INVALID_TRACKING_TOTAL_CNT		 ( 0x14 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_BASS_CONTROL_STATS_INVALID_RX_GAIND_B				 ( 0x15 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )
#define cOCTVC1_LTE_RC_ETM_CONFIG_INVALID_EPRE_INDEX						 ( 0x16 + cOCTVC1_LTE_AUTO_VALIDATE_RC_BASE )

#endif /* OCTVC1_LTE_RC_H__ */

