/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*\

File: octvc1_id2string.h

Copyright (c) 2019 Octasic Technologies Private Limited. All rights reserved.

Description:

This file contains the id2string implementation for package OCTVC1

This source code is Octasic Technologies Confidential. Use of and access to this code
is covered by the Octasic Technologies Device Enabling Software License Agreement.
Acknowledgement of the Octasic Technologies Device Enabling Software License was
required for access to this code. A copy was also provided with the release.

Release: OCTSDR Software Development Kit OCTSDR_GSM-04.02.00-B3135 (2019/03/05)

$Revision:  $

\*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/


#ifndef __OCTVC1_ID2STRING__
#define __OCTVC1_ID2STRING__

#include "../octdev_types.h"
/* -------------------------------------------------------------------------------------
	OCTVC1_ID2STRING
   -------------------------------------------------------------------------------------*/
#define mOCTVC1_ID2STRING( _f_ulId  ) \
	octvc1_id2string( _f_ulId )

#ifndef OCTVC1_ID2STRING_DECLARE
extern const char * octvc1_id2string( tOCT_UINT32 f_ulId );
extern const char * octvc1_moduleid2string( tOCT_UINT32 f_ulId );
#endif 


#ifdef OCTVC1_ID2STRING_DECLARE
#include <stdio.h>
#include "main/octvc1_main_id.h"
#include "job/octvc1_job_id.h"
#include "hw/octvc1_hw_id.h"
#include "irsc/octvc1_irsc_id.h"
#include "rus/octvc1_rus_id.h"
#include "3g_nodeb/octvc1_3g_nodeb_id.h"
#include "octvc1_module.h"
#include "gsm/octvc1_gsm_id.h"
#include "lte/octvc1_lte_id.h"
#include "obm/octvc1_obm_id.h"

#include "octvc1_module.h"
/* -------------------------------------------------------------------------------------
	octvc1_id2string
   -------------------------------------------------------------------------------------*/
const char * octvc1_id2string( tOCT_UINT32 f_ulId )
{
	static char g_szUnknownoctvc1_id2string[32];
	switch( f_ulId & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET ))
	{
		/* OCTVC1_MAIN */
		case ( cOCTVC1_MAIN_MSG_TARGET_RESET_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_TARGET_RESET_CID";
		case ( cOCTVC1_MAIN_MSG_TARGET_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_TARGET_INFO_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_ERASE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_ERASE_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_INFO_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_STATS_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_INFO_TRACE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_INFO_TRACE_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_START_TRACE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_START_TRACE_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_STOP_TRACE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_STOP_TRACE_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_ERASE_TRACE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_ERASE_TRACE_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_STATS_TRACE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_STATS_TRACE_CID";
		case ( cOCTVC1_MAIN_MSG_PROCESS_INFO_CPU_USAGE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_PROCESS_INFO_CPU_USAGE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_OPEN_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_CLOSE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_REMOVE_FILE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_REMOVE_FILE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_WRITE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_WRITE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_READ_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_READ_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_INFO_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_LIST_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_INFO_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_INFO_FILE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_INFO_FILE_CID";
		case ( cOCTVC1_MAIN_MSG_PROCESS_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_PROCESS_INFO_CID";
		case ( cOCTVC1_MAIN_MSG_PROCESS_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_PROCESS_LIST_CID";
		case ( cOCTVC1_MAIN_MSG_PROCESS_MONITOR_CPU_USAGE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_PROCESS_MONITOR_CPU_USAGE_CID";
		case ( cOCTVC1_MAIN_MSG_PROCESS_STATS_CPU_USAGE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_PROCESS_STATS_CPU_USAGE_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_LIST_SESSION_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_LIST_SESSION_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_INFO_SESSION_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_INFO_SESSION_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_INFO_SESSION_EVT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_INFO_SESSION_EVT_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_MODIFY_SESSION_EVT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_MODIFY_SESSION_EVT_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_INFO_SESSION_HEARTBEAT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_INFO_SESSION_HEARTBEAT_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_STATS_SESSION_HEARTBEAT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_STATS_SESSION_HEARTBEAT_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_START_SESSION_HEARTBEAT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_START_SESSION_HEARTBEAT_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_STOP_SESSION_HEARTBEAT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_STOP_SESSION_HEARTBEAT_CID";
		case ( cOCTVC1_MAIN_MSG_API_SYSTEM_MODIFY_SESSION_HEARTBEAT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_MODIFY_SESSION_HEARTBEAT_CID";
		case ( cOCTVC1_MAIN_MSG_APPLICATION_STOP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_STOP_CID";
		case ( cOCTVC1_MAIN_MSG_APPLICATION_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_INFO_CID";
		case ( cOCTVC1_MAIN_MSG_APPLICATION_INFO_SYSTEM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_INFO_SYSTEM_CID";
		case ( cOCTVC1_MAIN_MSG_APPLICATION_LIST_MODULE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_LIST_MODULE_CID";
		case ( cOCTVC1_MAIN_MSG_APPLICATION_INFO_MODULE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_INFO_MODULE_CID";
		case ( cOCTVC1_MAIN_MSG_APPLICATION_STATS_MODULE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_STATS_MODULE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_ADD_FILE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_ADD_FILE_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_INFO_STREAM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_INFO_STREAM_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_START_STREAM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_START_STREAM_CID";
		case ( cOCTVC1_MAIN_MSG_LOG_STOP_STREAM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LOG_STOP_STREAM_CID";
		case ( cOCTVC1_MAIN_MSG_APPLICATION_START_MODULE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_START_MODULE_CID";
		case ( cOCTVC1_MAIN_MSG_APPLICATION_STOP_MODULE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_STOP_MODULE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_LIST_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_OPEN_CID";
		case ( cOCTVC1_MAIN_MSG_LICENSING_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LICENSING_STATS_CID";
		case ( cOCTVC1_MAIN_MSG_LICENSING_INFO_FEATURES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LICENSING_INFO_FEATURES_CID";
		case ( cOCTVC1_MAIN_MSG_LICENSING_LIST_FEATURES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LICENSING_LIST_FEATURES_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_STOP_FILE_TRANSFER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_STOP_FILE_TRANSFER_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_WRITE_FILE_TRANSFER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_WRITE_FILE_TRANSFER_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_READ_FILE_TRANSFER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_READ_FILE_TRANSFER_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_FIND_FILE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_FIND_FILE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_CLOSE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_FIND_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_FIND_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_STATS_FILE_TRANSFER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_STATS_FILE_TRANSFER_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_LIST_FILE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_LIST_FILE_CID";
		case ( cOCTVC1_MAIN_MSG_FILE_SYSTEM_START_FILE_TRANSFER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_START_FILE_TRANSFER_CID";
		case ( cOCTVC1_MAIN_MSG_LICENSING_INFO_MCC_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LICENSING_INFO_MCC_CONFIG_CID";
		case (cOCTVC1_MAIN_MSG_PROCESS_DUMP_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_PROCESS_DUMP_EID";
		case (cOCTVC1_MAIN_MSG_API_SYSTEM_SESSION_HEARTBEAT_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_API_SYSTEM_SESSION_HEARTBEAT_EID";
		case (cOCTVC1_MAIN_MSG_PROCESS_CPU_USAGE_REPORT_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_PROCESS_CPU_USAGE_REPORT_EID";
		case (cOCTVC1_MAIN_MSG_APPLICATION_STATE_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_APPLICATION_STATE_CHANGE_EID";
		case (cOCTVC1_MAIN_MSG_PROCESS_STATE_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_PROCESS_STATE_CHANGE_EID";
		case (cOCTVC1_MAIN_MSG_LICENSING_STATE_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_MAIN_MSG_LICENSING_STATE_CHANGE_EID";
		case (cOCTVC1_MAIN_MSG_LOG_DATA_MID):
			return "cOCTVC1_MAIN_MSG_LOG_DATA_MID";
		case (cOCTVC1_MAIN_MSG_FILE_SYSTEM_REQUEST_FILE_TRANSFER_MID):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_REQUEST_FILE_TRANSFER_MID";
		case (cOCTVC1_MAIN_MSG_FILE_SYSTEM_REQUEST_ACK_FILE_TRANSFER_MID):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_REQUEST_ACK_FILE_TRANSFER_MID";
		case (cOCTVC1_MAIN_MSG_FILE_SYSTEM_ABORT_FILE_TRANSFER_MID):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_ABORT_FILE_TRANSFER_MID";
		case (cOCTVC1_MAIN_MSG_FILE_SYSTEM_DATA_FILE_TRANSFER_MID):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_DATA_FILE_TRANSFER_MID";
		case (cOCTVC1_MAIN_MSG_FILE_SYSTEM_DATA_ACK_FILE_TRANSFER_MID):
			return "cOCTVC1_MAIN_MSG_FILE_SYSTEM_DATA_ACK_FILE_TRANSFER_MID";
		/* OCTVC1_JOB */
		case ( cOCTVC1_JOB_MSG_UNITS_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_LIST_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_START_ALL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_START_ALL_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_INFO_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_FIND_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_FIND_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_START_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_START_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_LIST_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_LIST_CASES_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_INFO_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_INFO_CASES_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_STATS_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_STATS_CASES_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_MODIFY_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_MODIFY_CASES_CID";
		case ( cOCTVC1_JOB_MSG_UNITS_START_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_UNITS_START_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_SEND_CASES_DATA_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_SEND_CASES_DATA_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_STATS_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_PAUSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_PAUSE_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_RESUME_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_RESUME_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_CLEANUP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_CLEANUP_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_ADD_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_ADD_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_LIST_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_LIST_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_REMOVE_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_REMOVE_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_INFO_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_INFO_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_STATS_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_STATS_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_START_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_START_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_STOP_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_STOP_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_PULSE_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_PULSE_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_REMOVE_ALL_CASES_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_REMOVE_ALL_CASES_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_LIST_CASES_EXECUTE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_LIST_CASES_EXECUTE_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_REMOVE_CASES_EXECUTE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_REMOVE_CASES_EXECUTE_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_INFO_CASES_EXECUTE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_INFO_CASES_EXECUTE_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_START_CASES_EXECUTE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_START_CASES_EXECUTE_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_STATS_CASES_EXECUTE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_STATS_CASES_EXECUTE_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_REMOVE_ALL_CASES_EXECUTE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_REMOVE_ALL_CASES_EXECUTE_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_LIST_CASES_ERROR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_LIST_CASES_ERROR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_REMOVE_CASES_ERROR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_REMOVE_CASES_ERROR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_INFO_CASES_ERROR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_INFO_CASES_ERROR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_START_CASES_ERROR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_START_CASES_ERROR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_STATS_CASES_ERROR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_STATS_CASES_ERROR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_REMOVE_ALL_CASES_ERROR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_REMOVE_ALL_CASES_ERROR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_LIST_EXECUTOR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_LIST_EXECUTOR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_INFO_EXECUTOR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_INFO_EXECUTOR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_STATS_EXECUTOR_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_STATS_EXECUTOR_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_INFO_CONFIGURATION_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_INFO_CONFIGURATION_CID";
		case ( cOCTVC1_JOB_MSG_RUNNER_MODIFY_CONFIGURATION_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_MODIFY_CONFIGURATION_CID";
		case (cOCTVC1_JOB_MSG_RUNNER_EXECUTOR_STATE_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_EXECUTOR_STATE_CHANGE_EID";
		case (cOCTVC1_JOB_MSG_RUNNER_EXECUTOR_ITERATION_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_JOB_MSG_RUNNER_EXECUTOR_ITERATION_EID";
		/* OCTVC1_HW */
		case ( cOCTVC1_HW_MSG_PCB_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_PCB_INFO_CID";
		case ( cOCTVC1_HW_MSG_CPU_CORE_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CPU_CORE_STATS_CID";
		case ( cOCTVC1_HW_MSG_CPU_CORE_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CPU_CORE_INFO_CID";
		case ( cOCTVC1_HW_MSG_CPU_CORE_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CPU_CORE_LIST_CID";
		case ( cOCTVC1_HW_MSG_ETH_PORT_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_ETH_PORT_INFO_CID";
		case ( cOCTVC1_HW_MSG_ETH_PORT_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_ETH_PORT_LIST_CID";
		case ( cOCTVC1_HW_MSG_ETH_PORT_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_ETH_PORT_STATS_CID";
		case ( cOCTVC1_HW_MSG_ETH_PORT_MODIFY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_ETH_PORT_MODIFY_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_INFO_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_STATS_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_LIST_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_LIST_ANTENNA_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_LIST_ANTENNA_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_INFO_ANTENNA_RX_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_INFO_ANTENNA_RX_CONFIG_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_INFO_ANTENNA_TX_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_INFO_ANTENNA_TX_CONFIG_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_INFO_ANTENNA_TX_CALIB_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_INFO_ANTENNA_TX_CALIB_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_MODIFY_ANTENNA_TX_CALIB_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_MODIFY_ANTENNA_TX_CALIB_CID";
		case ( cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_INFO_CID";
		case ( cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_STATS_CID";
		case ( cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_START_SYNCHRO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_START_SYNCHRO_CID";
		case ( cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_STOP_SYNCHRO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_STOP_SYNCHRO_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_MODIFY_ANTENNA_RX_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_MODIFY_ANTENNA_RX_CONFIG_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_MODIFY_ANTENNA_TX_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_MODIFY_ANTENNA_TX_CONFIG_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_INFO_ANTENNA_FRONT_END_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_INFO_ANTENNA_FRONT_END_CID";
		case ( cOCTVC1_HW_MSG_RF_PORT_MODIFY_ANTENNA_FRONT_END_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_MODIFY_ANTENNA_FRONT_END_CID";
		case (cOCTVC1_HW_MSG_CPU_CORE_EXEC_REPORT_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CPU_CORE_EXEC_REPORT_EID";
		case (cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_STATUS_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_STATUS_CHANGE_EID";
		case (cOCTVC1_HW_MSG_RF_PORT_STATUS_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_STATUS_CHANGE_EID";
		case (cOCTVC1_HW_MSG_RF_PORT_ANTENNA_RX_CONFIG_STATUS_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_ANTENNA_RX_CONFIG_STATUS_CHANGE_EID";
		case (cOCTVC1_HW_MSG_RF_PORT_ANTENNA_TX_CONFIG_STATUS_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_RF_PORT_ANTENNA_TX_CONFIG_STATUS_CHANGE_EID";
		case (cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_DRIFT_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_HW_MSG_CLOCK_SYNC_MGR_DRIFT_CHANGE_EID";
		/* OCTVC1_OBM */
		case ( cOCTVC1_OBM_MSG_SYSTEM_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_SYSTEM_INFO_CID";
		case ( cOCTVC1_OBM_MSG_SYSTEM_MODIFY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_SYSTEM_MODIFY_CID";
		case ( cOCTVC1_OBM_MSG_LAST_ERROR_DESC_READ_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_LAST_ERROR_DESC_READ_CID";
		case ( cOCTVC1_OBM_MSG_CONFIGURATION_WRITE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_CONFIGURATION_WRITE_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_INFO_DSP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_INFO_DSP_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_RESET_DSP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_RESET_DSP_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_LIST_DSP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_LIST_DSP_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_MODIFY_DSP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_MODIFY_DSP_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_LIST_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_INFO_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_MODIFY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_MODIFY_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_STATS_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_STOP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_STOP_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_UPDATE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_UPDATE_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_ATTACH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_ATTACH_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_DETACH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_DETACH_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_INFO_GPS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_INFO_GPS_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_STATS_GPS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_STATS_GPS_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_RESET_GPS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_RESET_GPS_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_MODIFY_GPS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_MODIFY_GPS_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_LIST_GPS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_LIST_GPS_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_INFO_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_INFO_RF_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_MODIFY_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_MODIFY_RF_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_LIST_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_LIST_RF_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_STATS_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_STATS_RF_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_READ_I2C_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_READ_I2C_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_WRITE_I2C_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_WRITE_I2C_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_LIST_I2C_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_LIST_I2C_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_INFO_POWER_SWITCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_INFO_POWER_SWITCH_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_MODIFY_POWER_SWITCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_MODIFY_POWER_SWITCH_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_LIST_POWER_SWITCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_LIST_POWER_SWITCH_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_STATS_BATTERY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_STATS_BATTERY_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_LIST_BATTERY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_LIST_BATTERY_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_STATS_ETHERNET_SWITCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_STATS_ETHERNET_SWITCH_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_INFO_ETHERNET_SWITCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_INFO_ETHERNET_SWITCH_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_LIST_ETHERNET_SWITCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_LIST_ETHERNET_SWITCH_CID";
		case ( cOCTVC1_OBM_MSG_BOARD_MODIFY_ETHERNET_SWITCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_MODIFY_ETHERNET_SWITCH_CID";
		case (cOCTVC1_OBM_MSG_BOARD_GPS_STATE_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_GPS_STATE_CHANGE_EID";
		case (cOCTVC1_OBM_MSG_BOARD_POWER_SWITCH_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_POWER_SWITCH_CHANGE_EID";
		case (cOCTVC1_OBM_MSG_BOARD_BATTERY_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_BATTERY_CHANGE_EID";
		case (cOCTVC1_OBM_MSG_BOARD_TEMPERATURE_ALARM_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_TEMPERATURE_ALARM_EID";
		case (cOCTVC1_OBM_MSG_BOARD_RF_ALARM_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_RF_ALARM_EID";
		case (cOCTVC1_OBM_MSG_BOARD_FAN_ALARM_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_FAN_ALARM_EID";
		case (cOCTVC1_OBM_MSG_BOARD_DSP_BOOT_PROGRESS_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_DSP_BOOT_PROGRESS_EID";
		case (cOCTVC1_OBM_MSG_BOARD_REF_CLOCK_OVERRIDDEN_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_OBM_MSG_BOARD_REF_CLOCK_OVERRIDDEN_EID";			
		/* OCTVC1_IRSC */
		case ( cOCTVC1_IRSC_MSG_PROCESS_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_INFO_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_STATS_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_LIST_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_INFO_IPC_PORT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_INFO_IPC_PORT_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_STATS_IPC_PORT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_STATS_IPC_PORT_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_LIST_IPC_PORT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_LIST_IPC_PORT_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_INFO_TASK_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_INFO_TASK_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_STATS_TASK_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_STATS_TASK_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_LIST_TASK_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_LIST_TASK_CID";
		case ( cOCTVC1_IRSC_MSG_OBJMGR_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_OBJMGR_INFO_CID";
		case ( cOCTVC1_IRSC_MSG_OBJMGR_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_OBJMGR_STATS_CID";
		case ( cOCTVC1_IRSC_MSG_OBJMGR_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_OBJMGR_LIST_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_START_MONITORING_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_START_MONITORING_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_STOP_MONITORING_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_STOP_MONITORING_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_LIST_COMMAND_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_LIST_COMMAND_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_STATS_COMMAND_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_STATS_COMMAND_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_LIST_SESSION_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_LIST_SESSION_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_INFO_SESSION_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_INFO_SESSION_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_STATS_SESSION_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_STATS_SESSION_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_INFO_SESSION_EVT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_INFO_SESSION_EVT_CID";
		case ( cOCTVC1_IRSC_MSG_API_SYSTEM_STATS_SESSION_EVT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_API_SYSTEM_STATS_SESSION_EVT_CID";
		case ( cOCTVC1_IRSC_MSG_APPLICATION_LIST_TAP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_APPLICATION_LIST_TAP_CID";
		case ( cOCTVC1_IRSC_MSG_APPLICATION_INFO_TAP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_APPLICATION_INFO_TAP_CID";
		case ( cOCTVC1_IRSC_MSG_APPLICATION_STATS_TAP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_APPLICATION_STATS_TAP_CID";
		case ( cOCTVC1_IRSC_MSG_APPLICATION_START_TAP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_APPLICATION_START_TAP_CID";
		case ( cOCTVC1_IRSC_MSG_APPLICATION_STOP_TAP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_APPLICATION_STOP_TAP_CID";
		case ( cOCTVC1_IRSC_MSG_ROUTER_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_ROUTER_INFO_CID";
		case ( cOCTVC1_IRSC_MSG_ROUTER_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_ROUTER_STATS_CID";
		case ( cOCTVC1_IRSC_MSG_ROUTER_INFO_STREAMER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_ROUTER_INFO_STREAMER_CID";
		case ( cOCTVC1_IRSC_MSG_APPLICATION_STATS_SYSTEM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_APPLICATION_STATS_SYSTEM_CID";
		case ( cOCTVC1_IRSC_MSG_ROUTER_MODIFY_STREAMER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_ROUTER_MODIFY_STREAMER_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_STATS_MEMORY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_STATS_MEMORY_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_LIST_RESOURCE_SYSTEM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_LIST_RESOURCE_SYSTEM_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_STATS_RESOURCE_SYSTEM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_STATS_RESOURCE_SYSTEM_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_LIST_RESOURCE_USER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_LIST_RESOURCE_USER_CID";
		case ( cOCTVC1_IRSC_MSG_PROCESS_STATS_RESOURCE_USER_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_STATS_RESOURCE_USER_CID";
		case ( cOCTVC1_IRSC_MSG_APPLICATION_PAUSE_TAP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_APPLICATION_PAUSE_TAP_CID";
		case ( cOCTVC1_IRSC_MSG_APPLICATION_RESUME_TAP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_APPLICATION_RESUME_TAP_CID";
#ifndef OCT_OPTION_OCTVC1_REMOVE_LICENSING_EXTERNAL
		case ( cOCTVC1_IRSC_MSG_LICENSING_EXECUTE_EXTERNAL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_LICENSING_EXECUTE_EXTERNAL_CID";
#endif /* OCT_OPTION_OCTVC1_REMOVE_LICENSING_EXTERNAL */
		case (cOCTVC1_IRSC_MSG_PROCESS_DUMP_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_IRSC_MSG_PROCESS_DUMP_EID";
		case (cOCTVC1_IRSC_MSG_ROUTER_DATA_REQUEST_STREAMER_MID):
			return "cOCTVC1_IRSC_MSG_ROUTER_DATA_REQUEST_STREAMER_MID";
		/* OCTVC1_RUS */
		case ( cOCTVC1_RUS_MSG_RFFI_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_OPEN_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_CLOSE_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_INFO_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_STATS_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_LIST_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_STATS_CAPTURE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_STATS_CAPTURE_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_START_CAPTURE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_START_CAPTURE_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_INFO_UMTS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_INFO_UMTS_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_STATS_UMTS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_STATS_UMTS_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_INFO_GSM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_INFO_GSM_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_STATS_GSM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_STATS_GSM_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_STOP_CAPTURE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_STOP_CAPTURE_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_INFO_LTE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_INFO_LTE_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_STATS_LTE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_STATS_LTE_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_OPEN_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_CLOSE_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_INFO_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_STATS_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_LIST_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_START_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_START_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_STOP_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_STOP_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_MODIFY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_MODIFY_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_ADD_FILE_ENTRY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_ADD_FILE_ENTRY_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_REMOVE_FILE_ENTRY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_REMOVE_FILE_ENTRY_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_INFO_FILE_ENTRY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_INFO_FILE_ENTRY_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_LIST_FILE_ENTRY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_LIST_FILE_ENTRY_CID";
		case ( cOCTVC1_RUS_MSG_PLAYER_MODIFY_FILE_ENTRY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_PLAYER_MODIFY_FILE_ENTRY_CID";
		case ( cOCTVC1_RUS_MSG_WNM_MODIFY_SEARCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_MODIFY_SEARCH_CID";
		case ( cOCTVC1_RUS_MSG_WNM_START_SEARCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_START_SEARCH_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STOP_SEARCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STOP_SEARCH_CID";
		case ( cOCTVC1_RUS_MSG_WNM_RESUME_SEARCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_RESUME_SEARCH_CID";
		case ( cOCTVC1_RUS_MSG_WNM_INFO_SEARCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_INFO_SEARCH_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STATS_SEARCH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STATS_SEARCH_CID";
		case ( cOCTVC1_RUS_MSG_WNM_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_OPEN_CID";
		case ( cOCTVC1_RUS_MSG_WNM_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_CLOSE_CID";
		case ( cOCTVC1_RUS_MSG_WNM_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_INFO_CID";
		case ( cOCTVC1_RUS_MSG_WNM_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_LIST_CID";
		case ( cOCTVC1_RUS_MSG_WNM_INFO_UMTS_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_INFO_UMTS_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STATS_UMTS_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STATS_UMTS_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_LIST_UMTS_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_LIST_UMTS_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_INFO_GSM_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_INFO_GSM_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STATS_GSM_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STATS_GSM_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_LIST_GSM_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_LIST_GSM_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_INFO_LTE_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_INFO_LTE_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STATS_LTE_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STATS_LTE_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_LIST_LTE_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_LIST_LTE_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_INFO_CDMA2000_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_INFO_CDMA2000_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STATS_CDMA2000_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STATS_CDMA2000_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_LIST_CDMA2000_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_LIST_CDMA2000_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STATS_RSSI_BAND_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STATS_RSSI_BAND_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STATS_RSSI_BAND_CHANNELS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STATS_RSSI_BAND_CHANNELS_CID";
		case ( cOCTVC1_RUS_MSG_WNM_INFO_NR_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_INFO_NR_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_STATS_NR_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_STATS_NR_CELL_CID";
		case ( cOCTVC1_RUS_MSG_WNM_LIST_NR_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_LIST_NR_CELL_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_INFO_LOOPBACK_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_INFO_LOOPBACK_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_MODIFY_LOOPBACK_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_MODIFY_LOOPBACK_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_INFO_CDMA2000_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_INFO_CDMA2000_CID";
		case ( cOCTVC1_RUS_MSG_RFFI_STATS_CDMA2000_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_RFFI_STATS_CDMA2000_CID";
		case ( cOCTVC1_RUS_MSG_BASS_MODIFY_ATTACH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_MODIFY_ATTACH_CID";
		case ( cOCTVC1_RUS_MSG_BASS_START_ATTACH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_START_ATTACH_CID";
		case ( cOCTVC1_RUS_MSG_BASS_STOP_ATTACH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_STOP_ATTACH_CID";
		case ( cOCTVC1_RUS_MSG_BASS_INFO_ATTACH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_INFO_ATTACH_CID";
		case ( cOCTVC1_RUS_MSG_BASS_STATS_ATTACH_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_STATS_ATTACH_CID";
		case ( cOCTVC1_RUS_MSG_BASS_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_OPEN_CID";
		case ( cOCTVC1_RUS_MSG_BASS_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_CLOSE_CID";
		case ( cOCTVC1_RUS_MSG_BASS_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_INFO_CID";
		case ( cOCTVC1_RUS_MSG_BASS_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_BASS_LIST_CID";
		case (cOCTVC1_RUS_MSG_WNM_SEARCH_STATS_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_SEARCH_STATS_EID";
		case (cOCTVC1_RUS_MSG_WNM_GSM_CELL_STATS_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_GSM_CELL_STATS_EID";
		case (cOCTVC1_RUS_MSG_WNM_CDMA2000_CELL_STATS_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_CDMA2000_CELL_STATS_EID";
		case (cOCTVC1_RUS_MSG_WNM_UMTS_CELL_STATS_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_UMTS_CELL_STATS_EID";
		case (cOCTVC1_RUS_MSG_WNM_LTE_CELL_STATS_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_LTE_CELL_STATS_EID";
		case (cOCTVC1_RUS_MSG_WNM_MCC_LIC_ERR_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_MCC_LIC_ERR_EID";	
		/* OCTVC1_GSM */
		case ( cOCTVC1_GSM_MSG_TRX_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_OPEN_CID";
		case ( cOCTVC1_GSM_MSG_TRX_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_CLOSE_CID";
		case ( cOCTVC1_GSM_MSG_TRX_STATUS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_STATUS_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_CID";
		case ( cOCTVC1_GSM_MSG_TRX_RESET_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_RESET_CID";
		case ( cOCTVC1_GSM_MSG_TRX_MODIFY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_MODIFY_CID";
		case ( cOCTVC1_GSM_MSG_TRX_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_LIST_CID";
		case ( cOCTVC1_GSM_MSG_TRX_CLOSE_ALL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_CLOSE_ALL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_START_RECORD_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_START_RECORD_CID";
		case ( cOCTVC1_GSM_MSG_TRX_STOP_RECORD_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_STOP_RECORD_CID";
		case ( cOCTVC1_GSM_MSG_TRX_ACTIVATE_LOGICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_ACTIVATE_LOGICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_DEACTIVATE_LOGICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_DEACTIVATE_LOGICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_STATUS_LOGICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_STATUS_LOGICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_LOGICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_LOGICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_LIST_LOGICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_LIST_LOGICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_REQUEST_LOGICAL_CHANNEL_EMPTY_FRAME_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_REQUEST_LOGICAL_CHANNEL_EMPTY_FRAME_CID";
		case ( cOCTVC1_GSM_MSG_TRX_REQUEST_LOGICAL_CHANNEL_DATA_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_REQUEST_LOGICAL_CHANNEL_DATA_CID";
		case ( cOCTVC1_GSM_MSG_TRX_ACTIVATE_PHYSICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_ACTIVATE_PHYSICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_DEACTIVATE_PHYSICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_DEACTIVATE_PHYSICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_STATUS_PHYSICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_STATUS_PHYSICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_RESET_PHYSICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_RESET_PHYSICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_LIST_PHYSICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_LIST_PHYSICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_PHYSICAL_CHANNEL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_PHYSICAL_CHANNEL_CID";
		case ( cOCTVC1_GSM_MSG_TRX_MODIFY_PHYSICAL_CHANNEL_CIPHERING_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_MODIFY_PHYSICAL_CHANNEL_CIPHERING_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_PHYSICAL_CHANNEL_CIPHERING_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_PHYSICAL_CHANNEL_CIPHERING_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_PHYSICAL_CHANNEL_MEASUREMENT_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_PHYSICAL_CHANNEL_MEASUREMENT_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_RF_CID";
		case (cOCTVC1_RUS_MSG_WNM_NR_CELL_STATS_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_NR_CELL_STATS_EID";
		case (cOCTVC1_RUS_MSG_RFFI_RX_CAPTURE_MID):
				return "cOCTVC1_RUS_MSG_RFFI_RX_CAPTURE_MID";
		case (cOCTVC1_RUS_MSG_WNM_NR_CELL_STATS_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_RUS_MSG_WNM_NR_CELL_STATS_EID";
		case ( cOCTVC1_GSM_MSG_TRX_MODIFY_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_MODIFY_RF_CID";
		case ( cOCTVC1_GSM_MSG_TAP_FILTER_LIST_CID &
		 ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TAP_FILTER_LIST_CID";
		case ( cOCTVC1_GSM_MSG_TAP_FILTER_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TAP_FILTER_INFO_CID";
		case ( cOCTVC1_GSM_MSG_TAP_FILTER_STATS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TAP_FILTER_STATS_CID";
		case ( cOCTVC1_GSM_MSG_TAP_FILTER_MODIFY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TAP_FILTER_MODIFY_CID";
		case ( cOCTVC1_GSM_MSG_OVERSAMPLE_SELECT_16X_MODIFY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_OVERSAMPLE_SELECT_16X_MODIFY_CID";
		case ( cOCTVC1_GSM_MSG_OVERSAMPLE_SELECT_16X_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_OVERSAMPLE_SELECT_16X_INFO_CID";
		case ( cOCTVC1_GSM_MSG_TRX_START_LOGICAL_CHANNEL_RAW_DATA_INDICATIONS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_START_LOGICAL_CHANNEL_RAW_DATA_INDICATIONS_CID";
		case ( cOCTVC1_GSM_MSG_TRX_STOP_LOGICAL_CHANNEL_RAW_DATA_INDICATIONS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_STOP_LOGICAL_CHANNEL_RAW_DATA_INDICATIONS_CID";
		case ( cOCTVC1_GSM_MSG_TRX_REQUEST_LOGICAL_CHANNEL_CMU_LOOPBACK_TEST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_REQUEST_LOGICAL_CHANNEL_CMU_LOOPBACK_TEST_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_STUBB_LOOPBACK_TEST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_STUBB_LOOPBACK_TEST_CID";
		case ( cOCTVC1_GSM_MSG_TRX_START_STUBB_LOOPBACK_TEST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_START_STUBB_LOOPBACK_TEST_CID";
		case ( cOCTVC1_GSM_MSG_TRX_STOP_STUBB_LOOPBACK_TEST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_STOP_STUBB_LOOPBACK_TEST_CID";
		case ( cOCTVC1_GSM_MSG_TRX_MODIFY_TEST_MODE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_MODIFY_TEST_MODE_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_TEST_MODE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_TEST_MODE_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_DL_TRACE_BUFF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_DL_TRACE_BUFF_CID";
		case ( cOCTVC1_GSM_MSG_TRX_START_DL_TRACE_BUFF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_START_DL_TRACE_BUFF_CID";
		case ( cOCTVC1_GSM_MSG_TRX_STOP_DL_TRACE_BUFF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_STOP_DL_TRACE_BUFF_CID";
		case ( cOCTVC1_GSM_MSG_TRX_MODIFY_TS_DIGITAL_SCALING_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_MODIFY_TS_DIGITAL_SCALING_CID";
		case ( cOCTVC1_GSM_MSG_TRX_INFO_TS_DIGITAL_SCALING_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_INFO_TS_DIGITAL_SCALING_CID";
		case ( cOCTVC1_GSM_MSG_TRX_RESET_TS_DIGITAL_SCALING_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_GSM_MSG_TRX_RESET_TS_DIGITAL_SCALING_CID";
		case (cOCTVC1_GSM_MSG_TRX_UPLINK_RF_INPUT_DATA_LOGICAL_CHANNEL_MID):
			return "cOCTVC1_GSM_MSG_TRX_UPLINK_RF_INPUT_DATA_LOGICAL_CHANNEL_MID";
		case (cOCTVC1_GSM_MSG_TRX_EMPTY_FRAME_LOGICAL_CHANNEL_MID):
			return "cOCTVC1_GSM_MSG_TRX_EMPTY_FRAME_LOGICAL_CHANNEL_MID";
		case (cOCTVC1_GSM_MSG_TRX_DATA_REQUEST_LOGICAL_CHANNEL_MID):
			return "cOCTVC1_GSM_MSG_TRX_DATA_REQUEST_LOGICAL_CHANNEL_MID";
		case (cOCTVC1_GSM_MSG_TRX_TIME_INDICATION_MID):
			return "cOCTVC1_GSM_MSG_TRX_TIME_INDICATION_MID";
		case (cOCTVC1_GSM_MSG_TRX_STATUS_CHANGE_MID):
			return "cOCTVC1_GSM_MSG_TRX_STATUS_CHANGE_MID";
		case (cOCTVC1_GSM_MSG_TRX_INVALID_MCC_INDICATION_MID):
			return "cOCTVC1_GSM_MSG_TRX_INVALID_MCC_INDICATION_MID";
		case (cOCTVC1_GSM_MSG_TRX_DATA_INDICATION_LOGICAL_CHANNEL_MID):
			return "cOCTVC1_GSM_MSG_TRX_DATA_INDICATION_LOGICAL_CHANNEL_MID";
		case (cOCTVC1_GSM_MSG_TRX_READY_TO_SEND_INDICATION_LOGICAL_CHANNEL_MID):
			return "cOCTVC1_GSM_MSG_TRX_READY_TO_SEND_INDICATION_LOGICAL_CHANNEL_MID";
		case (cOCTVC1_GSM_MSG_TRX_RACH_INDICATION_LOGICAL_CHANNEL_MID):
			return "cOCTVC1_GSM_MSG_TRX_RACH_INDICATION_LOGICAL_CHANNEL_MID";
		case (cOCTVC1_GSM_MSG_TRX_RAW_DATA_INDICATION_LOGICAL_CHANNEL_MID):
			return "cOCTVC1_GSM_MSG_TRX_RAW_DATA_INDICATION_LOGICAL_CHANNEL_MID";
	/* OCTVC1_LTE */
		case ( cOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_MODULE_INFO_CONFIG_CID";
		case ( cOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_MODULE_MODIFY_CONFIG_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_OPEN_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_CLOSE_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_INFO_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_LIST_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_INFO_CELL_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_STATS_CELL_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_MODIFY_CELL_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_START_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_START_CELL_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_STOP_CELL_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_INFO_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_INFO_RF_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_MODIFY_RF_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_INFO_PHY_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_MODIFY_PHY_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_STATS_PHY_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_INFO_ETM_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_MODIFY_ETM_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_INFO_FAPI_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_MODIFY_FAPI_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_INFO_BASS_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_START_BASS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_START_BASS_CID";
		case ( cOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_STATS_BASS_CID";
		case (cOCTVC1_LTE_MSG_ENODEB_CELL_STATE_UPDATE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_CELL_STATE_UPDATE_EID";
		case (cOCTVC1_LTE_MSG_ENODEB_BASS_NEW_CELL_FOUND_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_BASS_NEW_CELL_FOUND_EID";
		case (cOCTVC1_LTE_MSG_ENODEB_BASS_CELL_SYNC_CHANGE_SOURCE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_LTE_MSG_ENODEB_BASS_CELL_SYNC_CHANGE_SOURCE_EID";

		/* OCTVC1_3G_NODEB */
		case ( cOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CID";
		case ( cOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CID";
		case ( cOCTVC1_3G_NODEB_MSG_CELL_OPEN_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_3G_NODEB_MSG_CELL_OPEN_CID";
		case ( cOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CID";
		case ( cOCTVC1_3G_NODEB_MSG_CELL_INFO_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_3G_NODEB_MSG_CELL_INFO_CID";
		case ( cOCTVC1_3G_NODEB_MSG_CELL_LIST_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_3G_NODEB_MSG_CELL_LIST_CID";
		case ( cOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CID";
		case (cOCTVC1_3G_NODEB_MSG_CELL_STATE_CHANGE_EID & ~( cOCTVC1_MSG_FLAGS_BIT_MASK << cOCTVC1_MSG_FLAGS_BIT_OFFSET )):
			return "cOCTVC1_3G_NODEB_MSG_CELL_STATE_CHANGE_EID";

		default:
			break;

	}
	sprintf( g_szUnknownoctvc1_id2string, "0x%.8X", f_ulId ); 
	return g_szUnknownoctvc1_id2string;
}
/* -------------------------------------------------------------------------------------
	octvc1_moduleid2string
   -------------------------------------------------------------------------------------*/
const char * octvc1_moduleid2string( tOCT_UINT32 f_ulId )
{
	static char g_szUnknownoctvc1_modid2string[32];
	switch( f_ulId )
	{
		case cOCTVC1_MODULE_ID_ENUM_GENERIC:
			return "GENERIC";
		case cOCTVC1_MODULE_ID_ENUM_MAIN:
			return "MAIN";
		case cOCTVC1_MODULE_ID_ENUM_PKT_API:
			return "PKT_API";
		case cOCTVC1_MODULE_ID_ENUM_CTRL:
			return "CTRL";
		case cOCTVC1_MODULE_ID_ENUM_RESERVED:
			return "RESERVED";
		case cOCTVC1_MODULE_ID_ENUM_JOB:
			return "JOB";
		case cOCTVC1_MODULE_ID_ENUM_HW:
			return "HW";
		case cOCTVC1_MODULE_ID_ENUM_IRSC:
			return "IRSC";
		case cOCTVC1_MODULE_ID_ENUM_OBM:
			return "OBM";
		case cOCTVC1_MODULE_ID_ENUM_APP_TEST:
			return "APP_TEST";
		case cOCTVC1_MODULE_ID_ENUM_SDR:
			return "SDR";
		case cOCTVC1_MODULE_ID_ENUM_GSM:
			return "GSM";
		case cOCTVC1_MODULE_ID_ENUM_LTE:
			return "LTE";
		case cOCTVC1_MODULE_ID_ENUM_3G_NODEB:
			return "3G_NODEB";
		case cOCTVC1_MODULE_ID_ENUM_RUS:
			return "RUS";
		case cOCTVC1_MODULE_ID_ENUM_LIB_TOOLKIT:
			return "LIB_TOOLKIT";
		case cOCTVC1_MODULE_ID_ENUM_UE3G:
			return "UE3G";
		case cOCTVC1_MODULE_ID_ENUM_TOOLBOX:
			return "TOOLBOX";
		case cOCTVC1_MODULE_ID_ENUM_LTE_UE:
			return "LTE_UE";
		case cOCTVC1_MODULE_ID_ENUM_GSM_UE:
			return "GSM_UE";
		case cOCTVC1_MODULE_ID_ENUM_CDMA2K:
			return "CDMA2K";
		case cOCTVC1_MODULE_ID_ENUM_MGW:
			return "MGW";
		case cOCTVC1_MODULE_ID_ENUM_SDR_SDK:
			return "SDR_SDK";
		case cOCTVC1_MODULE_ID_ENUM_5G:
			return "5G";
		case cOCTVC1_MODULE_ID_ENUM_5G_UE:
			return "5G_UE";
		case cOCTVC1_MODULE_ID_ENUM_USSM:
			return "USSM";
	}
	sprintf( g_szUnknownoctvc1_modid2string, "0x%.8X", f_ulId );
	return g_szUnknownoctvc1_modid2string;
}
#endif 

#endif /* __OCTVC1_ID2STRING__ */
