/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

File: octvc1_3g_nodeb_api_swap.h	

Copyright (c) 2018 Octasic Technologies Private Limited. All rights reserved.	

Description:	

This source code is Octasic Technologies Confidential. Use of and access to this code
is covered by the Octasic Technologies Device Enabling Software License Agreement.
Acknowledgement of the Octasic Technologies Device Enabling Software License was
required for access to this code. A copy was also provided with the release.	

Release: OCTSDR Software Development Kit OCTSDR-SR_3G-03.02.00-B489 (2018/03/20)	

\*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/	
#ifndef __OCTVC1_3G_NODEB_API_SWAP_H__
#define __OCTVC1_3G_NODEB_API_SWAP_H__

#ifdef __cplusplus
extern "C" {
#endif

/*****************************  INCLUDE FILES  *******************************/
#include "../octvc1_swap_hdrs.h"
#include "octvc1_3g_nodeb_api.h"

/*********************************  MACROS  **********************************/


#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_CELL_STATE_ENUM_SWAP( pType ){ \
		*((tOCT_UINT32 *)pType) = mOCT_SWAP32_IF_LE( *((tOCT_UINT32 *)pType) ); }
#else

#define mOCTVC1_3G_NODEB_CELL_STATE_ENUM_SWAP( pType )

#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_CELL_RF_CONFIG_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_CELL_RF_CONFIG * pOCTVC1_3G_NODEB_CELL_RF_CONFIG = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_CELL_RF_CONFIG)\
	{ mOCTVC1_RADIO_STANDARD_FREQ_BAND_UMTS_ENUM_SWAP( &((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulBandId ); }  \
	((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulDlUarfcn = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulDlUarfcn); \
	((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulUlUarfcn = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulUlUarfcn); \
	((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulRxGainDb = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulRxGainDb); \
	((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulTxAttndB = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_CELL_RF_CONFIG *)pOCTVC1_3G_NODEB_CELL_RF_CONFIG)->ulTxAttndB); \
}
#else
#define mOCTVC1_3G_NODEB_CELL_RF_CONFIG_SWAP( pOCTVC1_3G_NODEB_CELL_RF_CONFIG )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CMD_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CMD * pOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CMD *)pOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CMD)->Header ); }  \
}
#else
#define mOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CMD_SWAP( pOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_RSP_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_RSP * pOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_RSP *)pOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_RSP)->Header ); }  \
}
#else
#define mOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_RSP_SWAP( pOCTVC1_3G_NODEB_MSG_MODULE_INFO_CONFIG_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CMD_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CMD * pOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CMD *)pOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CMD)->Header ); }  \
}
#else
#define mOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CMD_SWAP( pOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_RSP_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_RSP * pOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_RSP *)pOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_RSP)->Header ); }  \
}
#else
#define mOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_RSP_SWAP( pOCTVC1_3G_NODEB_MSG_MODULE_MODIFY_CONFIG_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD * pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD)->Header ); }  \
	((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD)->ulRfPortIndex = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD)->ulRfPortIndex); \
	((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD)->ulUserId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD)->ulUserId); \
	{ mOCTVC1_3G_NODEB_CELL_RF_CONFIG_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD)->RfConfig ); }  \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_OPEN_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP * pOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP)->Header ); }  \
	((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP)->hCell = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP)->hCell); \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_OPEN_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD * pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD)->Header ); }  \
	((tOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD)->hCell = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD)->hCell); \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP * pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP)->Header ); }  \
	((tOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP)->hCell = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP)->hCell); \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_CLOSE_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD * pOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD)->Header ); }  \
	((tOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD)->hCell = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD)->hCell); \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_INFO_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP * pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP)->Header ); }  \
	((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP)->hCell = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP)->hCell); \
	((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP)->ulPortIndex = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP)->ulPortIndex); \
	((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP)->ulUserId = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP)->ulUserId); \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_INFO_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD * pOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD)->Header ); }  \
	{ mOCTVC1_CURSOR_HANDLE_OBJECT_GET_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD)->ObjectCursor ); }  \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_LIST_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP * pOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP)->Header ); }  \
	{ mOCTVC1_CURSOR_HANDLE_OBJECT_GET_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP)->ObjectCursor ); }  \
	{ mOCTVC1_LIST_HANDLE_OBJECT_GET_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP)->ObjectList ); }  \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_LIST_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD * pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD)->Header ); }  \
	((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD)->hCell = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD)->hCell); \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_CMD )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#if defined( _OCT_ENDIAN_TYPE_LE_ )
#define mOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP_SWAP( _f_pParms ){ 	tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP * pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP = (_f_pParms); SWAP_UNUSED(pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP)\
	{ mOCTVC1_MSG_HEADER_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP)->Header ); }  \
	((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP)->hCell = \
		mOCT_SWAP32_IF_LE(((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP)->hCell); \
	{ mOCTVC1_3G_NODEB_CELL_RF_CONFIG_SWAP( &((tOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP *)pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP)->Config ); }  \
}
#else
#define mOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP_SWAP( pOCTVC1_3G_NODEB_MSG_CELL_INFO_RF_RSP )
#endif /* _OCT_ENDIAN_TYPE_LE_ */

#ifdef __cplusplus
}

#endif

#endif /* __OCTVC1_3G_NODEB_API_SWAP_H__ */
